$axure.loadCurrentPage({
  "url":"支付成功_1.html",
  "generationDate":new Date(1496903836660.76),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"sfz",
"sfz_n"],
  "page":{
    "packageId":"db0d18312a3742428476a3ce4224198c",
    "type":"Axure:Page",
    "name":"支付成功",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"286e70e66f7146b2ac792ec64b5af52a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "size":{
              "width":320,
              "height":470},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"13a0671584334408a04ade8a3778c8df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "size":{
                  "width":320,
                  "height":470},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付订单/u0.png"}},
{
          "id":"1aaa255bc1ea4d9683ddb9eab312670d",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "fixedHorizontal":"left",
          "fixedMarginHorizontal":0,
          "fixedVertical":"top",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"03c22d7b586141da836c965094e8964d",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"eefae0feb1bc406986c33600d6b2fb48",
                  "label":"",
                  "parentDynamicPanel":"1aaa255bc1ea4d9683ddb9eab312670d",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF1C222E},
                    "size":{
                      "width":320,
                      "height":64},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2a3e1de269e34f80ac27b6ed71b78e85",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1aaa255bc1ea4d9683ddb9eab312670d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF1C222E},
                        "size":{
                          "width":320,
                          "height":64},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u3.png"}},
{
                  "id":"55ad663a6bec4e268f49016151534a39",
                  "label":"",
                  "parentDynamicPanel":"1aaa255bc1ea4d9683ddb9eab312670d",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Heiti SC Regular', 'Heiti SC'",
                    "fontSize":"18px",
                    "fontWeight":"200",
                    "horizontalAlignment":"center",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":78,
                      "y":35},
                    "size":{
                      "width":163,
                      "height":22},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a4b77b801a4c44f08b19929960588531",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1aaa255bc1ea4d9683ddb9eab312670d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Heiti SC Regular', 'Heiti SC'",
                        "fontSize":"18px",
                        "fontWeight":"200",
                        "horizontalAlignment":"center",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":78,
                          "y":35},
                        "size":{
                          "width":163,
                          "height":22},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f778db588883492a803b21c5d481d906",
                  "label":"",
                  "parentDynamicPanel":"1aaa255bc1ea4d9683ddb9eab312670d",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":320,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"eacd9f878b724ccf9aecffb900887646",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1aaa255bc1ea4d9683ddb9eab312670d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":320,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u7.png"}},
{
                  "id":"1a7fe671246a466ab7274757f0da5897",
                  "label":"",
                  "parentDynamicPanel":"1aaa255bc1ea4d9683ddb9eab312670d",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Heiti SC Regular', 'Heiti SC'",
                    "fontSize":"16px",
                    "fontWeight":"200",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":27,
                      "y":36},
                    "size":{
                      "width":63,
                      "height":19},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e08ddbb22bb14a468bc5af3106c2b693",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1aaa255bc1ea4d9683ddb9eab312670d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Heiti SC Regular', 'Heiti SC'",
                        "fontSize":"16px",
                        "fontWeight":"200",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":27,
                          "y":36},
                        "size":{
                          "width":63,
                          "height":19},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"c60b17e2cdf942b3acf3546c12f43569",
                  "label":"",
                  "parentDynamicPanel":"1aaa255bc1ea4d9683ddb9eab312670d",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Lucida Grande Regular', 'Lucida Grande'",
                    "fontSize":"20px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":9,
                      "y":31},
                    "size":{
                      "width":22,
                      "height":29}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"377d9a61aa494a55b4e73425fb4814f7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1aaa255bc1ea4d9683ddb9eab312670d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Lucida Grande Regular', 'Lucida Grande'",
                        "fontSize":"20px",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":9,
                          "y":31},
                        "size":{
                          "width":22,
                          "height":29}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"5c5071af51ab46b8bbd2519c0f656e18",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":100},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea43922aebcc40258b61843daa6581ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":100},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付成功/u13.png"}},
{
          "id":"cc0d42684612480eac0724cc4799a894",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":111.5,
              "y":221},
            "size":{
              "width":97,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"664934b270784f2a88b9dfb660f2dcaf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":111.5,
                  "y":221},
                "size":{
                  "width":97,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"796a59b7ce224bc08543b465d86b9f54",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":20,
              "y":330},
            "size":{
              "width":100,
              "height":35}},
          "adaptiveStyles":{
}},
{
          "id":"ac7fd292d4eb417cb985cbe345067ac7",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":180,
              "y":330},
            "size":{
              "width":100,
              "height":35}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "286e70e66f7146b2ac792ec64b5af52a":{
      "scriptId":"u0"},
    "13a0671584334408a04ade8a3778c8df":{
      "scriptId":"u1"},
    "1aaa255bc1ea4d9683ddb9eab312670d":{
      "scriptId":"u2"},
    "eefae0feb1bc406986c33600d6b2fb48":{
      "scriptId":"u3"},
    "2a3e1de269e34f80ac27b6ed71b78e85":{
      "scriptId":"u4"},
    "55ad663a6bec4e268f49016151534a39":{
      "scriptId":"u5"},
    "a4b77b801a4c44f08b19929960588531":{
      "scriptId":"u6"},
    "f778db588883492a803b21c5d481d906":{
      "scriptId":"u7"},
    "eacd9f878b724ccf9aecffb900887646":{
      "scriptId":"u8"},
    "1a7fe671246a466ab7274757f0da5897":{
      "scriptId":"u9"},
    "e08ddbb22bb14a468bc5af3106c2b693":{
      "scriptId":"u10"},
    "c60b17e2cdf942b3acf3546c12f43569":{
      "scriptId":"u11"},
    "377d9a61aa494a55b4e73425fb4814f7":{
      "scriptId":"u12"},
    "5c5071af51ab46b8bbd2519c0f656e18":{
      "scriptId":"u13"},
    "ea43922aebcc40258b61843daa6581ae":{
      "scriptId":"u14"},
    "cc0d42684612480eac0724cc4799a894":{
      "scriptId":"u15"},
    "664934b270784f2a88b9dfb660f2dcaf":{
      "scriptId":"u16"},
    "796a59b7ce224bc08543b465d86b9f54":{
      "scriptId":"u17"},
    "ac7fd292d4eb417cb985cbe345067ac7":{
      "scriptId":"u18"}}});