$axure.loadCurrentPage({
  "url":"邀请好友.html",
  "generationDate":new Date(1496903835732.76),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"sfz",
"sfz_n"],
  "page":{
    "packageId":"2aebdc45407c46d8ba3b2255116607b4",
    "type":"Axure:Page",
    "name":"邀请好友",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a886024c0f3949578e3efc31905853b9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "size":{
              "width":320,
              "height":500},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"84e602829a614c098d2f127a3f7add33",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "size":{
                  "width":320,
                  "height":500},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/钱包/u0.png"}},
{
          "id":"d687ecb1b8b44a9e9b5af4a4c2750873",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "fixedHorizontal":"left",
          "fixedMarginHorizontal":0,
          "fixedVertical":"top",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"816e2f89401949f09eab3e8929d43f57",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"8adb89abf6754421912a208cd026fb5f",
                  "label":"",
                  "parentDynamicPanel":"d687ecb1b8b44a9e9b5af4a4c2750873",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF1C222E},
                    "size":{
                      "width":320,
                      "height":64},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"87b9527e607948299d37edde0aa89e71",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d687ecb1b8b44a9e9b5af4a4c2750873",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF1C222E},
                        "size":{
                          "width":320,
                          "height":64},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u3.png"}},
{
                  "id":"ff5ffd341dae46ec9160c979e654cc7b",
                  "label":"",
                  "parentDynamicPanel":"d687ecb1b8b44a9e9b5af4a4c2750873",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Heiti SC Regular', 'Heiti SC'",
                    "fontSize":"18px",
                    "fontWeight":"200",
                    "horizontalAlignment":"center",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":78,
                      "y":35},
                    "size":{
                      "width":163,
                      "height":22},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e76127a50cfd4cb080120753a59c8f0a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d687ecb1b8b44a9e9b5af4a4c2750873",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Heiti SC Regular', 'Heiti SC'",
                        "fontSize":"18px",
                        "fontWeight":"200",
                        "horizontalAlignment":"center",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":78,
                          "y":35},
                        "size":{
                          "width":163,
                          "height":22},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"4ce21eb78a124ed5a461271d292eab04",
                  "label":"",
                  "parentDynamicPanel":"d687ecb1b8b44a9e9b5af4a4c2750873",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":320,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"418add9c94ae472d80d1015551f88cdf",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d687ecb1b8b44a9e9b5af4a4c2750873",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":320,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u7.png"}},
{
                  "id":"124844f6c5464634ba863ad9f707bcc6",
                  "label":"",
                  "parentDynamicPanel":"d687ecb1b8b44a9e9b5af4a4c2750873",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Heiti SC Regular', 'Heiti SC'",
                    "fontSize":"16px",
                    "fontWeight":"200",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":27,
                      "y":36},
                    "size":{
                      "width":63,
                      "height":19},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7e96b2c7b62546b8aacf11542734d6f2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d687ecb1b8b44a9e9b5af4a4c2750873",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Heiti SC Regular', 'Heiti SC'",
                        "fontSize":"16px",
                        "fontWeight":"200",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":27,
                          "y":36},
                        "size":{
                          "width":63,
                          "height":19},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"d7b324fbe1444558bec22acbbc8adf2c",
                  "label":"",
                  "parentDynamicPanel":"d687ecb1b8b44a9e9b5af4a4c2750873",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Lucida Grande Regular', 'Lucida Grande'",
                    "fontSize":"20px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":9,
                      "y":31},
                    "size":{
                      "width":22,
                      "height":29}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"906378e978734f1eb3b8dc9e8c36fcd0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d687ecb1b8b44a9e9b5af4a4c2750873",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Lucida Grande Regular', 'Lucida Grande'",
                        "fontSize":"20px",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":9,
                          "y":31},
                        "size":{
                          "width":22,
                          "height":29}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]}]}},
  "masters":{
},
  "objectPaths":{
    "a886024c0f3949578e3efc31905853b9":{
      "scriptId":"u0"},
    "84e602829a614c098d2f127a3f7add33":{
      "scriptId":"u1"},
    "d687ecb1b8b44a9e9b5af4a4c2750873":{
      "scriptId":"u2"},
    "8adb89abf6754421912a208cd026fb5f":{
      "scriptId":"u3"},
    "87b9527e607948299d37edde0aa89e71":{
      "scriptId":"u4"},
    "ff5ffd341dae46ec9160c979e654cc7b":{
      "scriptId":"u5"},
    "e76127a50cfd4cb080120753a59c8f0a":{
      "scriptId":"u6"},
    "4ce21eb78a124ed5a461271d292eab04":{
      "scriptId":"u7"},
    "418add9c94ae472d80d1015551f88cdf":{
      "scriptId":"u8"},
    "124844f6c5464634ba863ad9f707bcc6":{
      "scriptId":"u9"},
    "7e96b2c7b62546b8aacf11542734d6f2":{
      "scriptId":"u10"},
    "d7b324fbe1444558bec22acbbc8adf2c":{
      "scriptId":"u11"},
    "906378e978734f1eb3b8dc9e8c36fcd0":{
      "scriptId":"u12"}}});