$axure.loadCurrentPage({
  "url":"交易记录.html",
  "generationDate":new Date(1496903830496.76),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"sfz",
"sfz_n"],
  "page":{
    "packageId":"2baad7e530744a19bb80980a1de66556",
    "type":"Axure:Page",
    "name":"交易记录",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4b39fa4a94e54e72b5420bae787e670f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "size":{
              "width":320,
              "height":800},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e490b9ac0ad74254adfc2b4ad6577088",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "size":{
                  "width":320,
                  "height":800},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/交易记录/u0.png"}},
{
          "id":"c2ec4e67d88b4afea9029fe794c74210",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "fixedHorizontal":"left",
          "fixedMarginHorizontal":0,
          "fixedVertical":"top",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"d5e1420d1dc043449c06244a3ca7165e",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"c6c79d3c590e4757b555cf3ad705bbf0",
                  "label":"",
                  "parentDynamicPanel":"c2ec4e67d88b4afea9029fe794c74210",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF1C222E},
                    "size":{
                      "width":320,
                      "height":64},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"049ac0619ce743c59c3746da55fe7b8f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c2ec4e67d88b4afea9029fe794c74210",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF1C222E},
                        "size":{
                          "width":320,
                          "height":64},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u3.png"}},
{
                  "id":"6c9086bc71d34cb1a74a018b4282a699",
                  "label":"",
                  "parentDynamicPanel":"c2ec4e67d88b4afea9029fe794c74210",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Heiti SC Regular', 'Heiti SC'",
                    "fontSize":"18px",
                    "fontWeight":"200",
                    "horizontalAlignment":"center",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":78,
                      "y":35},
                    "size":{
                      "width":163,
                      "height":22},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e323b60598d6471cb284c80bbdd079de",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c2ec4e67d88b4afea9029fe794c74210",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Heiti SC Regular', 'Heiti SC'",
                        "fontSize":"18px",
                        "fontWeight":"200",
                        "horizontalAlignment":"center",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":78,
                          "y":35},
                        "size":{
                          "width":163,
                          "height":22},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"2f99e9ab15374cf98f513b17371c2cdc",
                  "label":"",
                  "parentDynamicPanel":"c2ec4e67d88b4afea9029fe794c74210",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":320,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e1a7dea7e02b465c9fe1ad80962bfd1a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c2ec4e67d88b4afea9029fe794c74210",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":320,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u7.png"}},
{
                  "id":"c2aa2ac1a1974e5b9d34cde4cb91c751",
                  "label":"",
                  "parentDynamicPanel":"c2ec4e67d88b4afea9029fe794c74210",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Heiti SC Regular', 'Heiti SC'",
                    "fontSize":"16px",
                    "fontWeight":"200",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":27,
                      "y":36},
                    "size":{
                      "width":63,
                      "height":19},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"26c4e482c1cf400fac169d059cef7bbb",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c2ec4e67d88b4afea9029fe794c74210",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Heiti SC Regular', 'Heiti SC'",
                        "fontSize":"16px",
                        "fontWeight":"200",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":27,
                          "y":36},
                        "size":{
                          "width":63,
                          "height":19},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f3b07fb4c98a489ab47a819cd6b9e152",
                  "label":"",
                  "parentDynamicPanel":"c2ec4e67d88b4afea9029fe794c74210",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Lucida Grande Regular', 'Lucida Grande'",
                    "fontSize":"20px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":9,
                      "y":31},
                    "size":{
                      "width":22,
                      "height":29}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0a6377082c474761b85fb492c216bf33",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c2ec4e67d88b4afea9029fe794c74210",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Lucida Grande Regular', 'Lucida Grande'",
                        "fontSize":"20px",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":9,
                          "y":31},
                        "size":{
                          "width":22,
                          "height":29}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"ced9992eea9645d5801a62922eb6d4a0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":1,
              "y":63},
            "size":{
              "width":107,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5f05ec9e7e847fbad522de961312616",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":1,
                  "y":63},
                "size":{
                  "width":107,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/交易记录/u13.png"}},
{
          "id":"b32a880d10794d97aefe4d6fd35ddf37",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":107,
              "y":63},
            "size":{
              "width":107,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d31d4601e11846edace11d7362d43826",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":107,
                  "y":63},
                "size":{
                  "width":107,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/交易记录/u13.png"}},
{
          "id":"2c3539d109ab4cfdb3ec577f5d0f5f30",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":213,
              "y":63},
            "size":{
              "width":107,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a262b73dbe44c839a25e67eedfa41d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":213,
                  "y":63},
                "size":{
                  "width":107,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/交易记录/u13.png"}},
{
          "id":"100651ada57149aa8d0c78f2c7522c9c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":0,
              "y":109},
            "size":{
              "width":320,
              "height":81}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7fa6704826994125b46686d0f8a163c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":0,
                  "y":109},
                "size":{
                  "width":320,
                  "height":81}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/交易记录/u19.png"}},
{
          "id":"acc6af3db2544f3b83695e6ed7169d87",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":11,
              "y":154},
            "size":{
              "width":159,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d910cf89f9a4f9eb31f2f0d6aa36c25",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":11,
                  "y":154},
                "size":{
                  "width":159,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1b12405a7bc24072b869b5c2a88441a4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":11,
              "y":126},
            "size":{
              "width":80,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"503f3c3ff7a0439fa20fb903e971b086",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":11,
                  "y":126},
                "size":{
                  "width":80,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"34127eb9fc5140b799a5a044c30e8835",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":226,
              "y":121},
            "size":{
              "width":80,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44555cdb998b4428908c2f2529504f8f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":226,
                  "y":121},
                "size":{
                  "width":80,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"df7784b3ec46462da54023d0c2d0de5a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":147,
              "y":155},
            "size":{
              "width":159,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a7399fc2b6c745cd90f4578a24a7a8a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":147,
                  "y":155},
                "size":{
                  "width":159,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0fb392c71e254ba6936263be87918241",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":0,
              "y":194},
            "size":{
              "width":320,
              "height":81}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23ad006d991947e6b75b02a29114c8d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":0,
                  "y":194},
                "size":{
                  "width":320,
                  "height":81}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/交易记录/u19.png"}},
{
          "id":"1aa7561df6dc4848833eecaef8567c35",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":11,
              "y":239},
            "size":{
              "width":159,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b65c61339cc408abff5030a2650f174",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":11,
                  "y":239},
                "size":{
                  "width":159,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5ce38b4f1e3940c99a9c051917457d6d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":11,
              "y":211},
            "size":{
              "width":80,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f72c815dd6c0480298340b0e59f26446",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":11,
                  "y":211},
                "size":{
                  "width":80,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0662e9cad54c463686d2d8f3ecb0332e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF008000,
              "opacity":1},
            "location":{
              "x":226,
              "y":206},
            "size":{
              "width":80,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95d6e89b1cd54c08b77ed8206fdfa800",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF008000,
                  "opacity":1},
                "location":{
                  "x":226,
                  "y":206},
                "size":{
                  "width":80,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5456fd8878eb4db89df06cc42ca78ab9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":147,
              "y":240},
            "size":{
              "width":159,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"253d90f332f44f5e9f4a7530efcb9139",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":147,
                  "y":240},
                "size":{
                  "width":159,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4f0fab635ced4e44a963a3367fce9806",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":0,
              "y":283},
            "size":{
              "width":320,
              "height":81}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"93fd67b2f07e41728dced0aef3cb849f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":0,
                  "y":283},
                "size":{
                  "width":320,
                  "height":81}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/交易记录/u19.png"}},
{
          "id":"65af0e9d941d48edb0eec44ec95ef56a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":11,
              "y":328},
            "size":{
              "width":159,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"121c1da0d341491bb833a4a9a87fe2fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":11,
                  "y":328},
                "size":{
                  "width":159,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"26fbcd10018649968263791cf379221a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":11,
              "y":300},
            "size":{
              "width":80,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47275b2f00e04f10a2369a556008ed6c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":11,
                  "y":300},
                "size":{
                  "width":80,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6c0eb09e0ea94a59ad8bd4581c0b68fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":226,
              "y":295},
            "size":{
              "width":80,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e607665585a4dc88866cde7cd34e49e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":226,
                  "y":295},
                "size":{
                  "width":80,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5a2b4c3fa09144e19dd2f85c5cdb62ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":147,
              "y":329},
            "size":{
              "width":159,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b01f76617153457ea7de5ca385ba7bb0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":147,
                  "y":329},
                "size":{
                  "width":159,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5d8555a582aa405d9e8ee95d93cb3c05",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":0,
              "y":374},
            "size":{
              "width":320,
              "height":81}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d79bb191d392459cb803985816f9951b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":0,
                  "y":374},
                "size":{
                  "width":320,
                  "height":81}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/交易记录/u19.png"}},
{
          "id":"39e9298f882848109602c3e08e2d36a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":11,
              "y":419},
            "size":{
              "width":159,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab5509c9e06748cfb7afc483b9a87209",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":11,
                  "y":419},
                "size":{
                  "width":159,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c4ba884452c34d2aaa74e77a1c145309",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":11,
              "y":391},
            "size":{
              "width":80,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"55cad1786d3f4e40ab855da2265f2224",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":11,
                  "y":391},
                "size":{
                  "width":80,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b7134190e8e647d69ea8c975f485978b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":226,
              "y":386},
            "size":{
              "width":80,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a2dba3e9d4c45d4920eff89ebfe4dcb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":226,
                  "y":386},
                "size":{
                  "width":80,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6971d4f622914212844834804096aac7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":147,
              "y":420},
            "size":{
              "width":159,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a38ef28e57c745d8baf17db18f5dfc40",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":147,
                  "y":420},
                "size":{
                  "width":159,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a6a5b0c273234e2597b8391510fea893",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":0,
              "y":465},
            "size":{
              "width":320,
              "height":81}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f58297bec6d4c34899a053b3e430973",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":0,
                  "y":465},
                "size":{
                  "width":320,
                  "height":81}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/交易记录/u19.png"}},
{
          "id":"f642bda127e3483f8292ffcff0464f84",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":11,
              "y":510},
            "size":{
              "width":159,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90a6322248e2493ab8bb2d0fa507d255",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":11,
                  "y":510},
                "size":{
                  "width":159,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c238200bf65f4dae86c3b6f4ff18984d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":11,
              "y":482},
            "size":{
              "width":80,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0fd654ba13f94256b673fa117c1da11a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":11,
                  "y":482},
                "size":{
                  "width":80,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7e0abba3a46b4c7e837004a387ad13a6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":226,
              "y":477},
            "size":{
              "width":80,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8fb964c13a79405ca1e63badc3e0aef7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":226,
                  "y":477},
                "size":{
                  "width":80,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f0b7c68bb88844d18dbf7c7fe18cb70e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":147,
              "y":511},
            "size":{
              "width":159,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf09a4c4ddf2406b8cef83222c8fd5b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":147,
                  "y":511},
                "size":{
                  "width":159,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"450114e1637942f5b5032419a0c80392",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":0,
              "y":556},
            "size":{
              "width":320,
              "height":81}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a3ce819e4784acfb6302f54d4584dbb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":0,
                  "y":556},
                "size":{
                  "width":320,
                  "height":81}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/交易记录/u19.png"}},
{
          "id":"0acfb9f732714a9591ce35eaddc43883",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":11,
              "y":601},
            "size":{
              "width":159,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b97e29bb1d2f4270b6f6decb76783bdc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":11,
                  "y":601},
                "size":{
                  "width":159,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d4360b377f414af197b8169f90d17887",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":11,
              "y":573},
            "size":{
              "width":80,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c12cfc973c464ec58f342ec37edf7aa9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":11,
                  "y":573},
                "size":{
                  "width":80,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6a405de398a84ab29f66198793ce1d1c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF008000,
              "opacity":1},
            "location":{
              "x":226,
              "y":568},
            "size":{
              "width":80,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41193646fa864c68933097fc411b7860",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF008000,
                  "opacity":1},
                "location":{
                  "x":226,
                  "y":568},
                "size":{
                  "width":80,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"657615f8aef14148ad733a1cd506b4c9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":147,
              "y":602},
            "size":{
              "width":159,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb446f59d79c4267bdba862af74fba41",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":147,
                  "y":602},
                "size":{
                  "width":159,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7921aab1a58c4de5bfb7f179130912d0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":0,
              "y":647},
            "size":{
              "width":320,
              "height":81}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ea32a136e374aada80181481df49a3b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":0,
                  "y":647},
                "size":{
                  "width":320,
                  "height":81}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/交易记录/u19.png"}},
{
          "id":"034144a559dd47d4abed9f0df33000dd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":11,
              "y":692},
            "size":{
              "width":159,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4807d43620044f75bfcf4f55cca3442a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":11,
                  "y":692},
                "size":{
                  "width":159,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0477721038b34d3799cc5d4e78de1f7f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":11,
              "y":664},
            "size":{
              "width":80,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"123268658dac4e44b3ea3ed83dc797ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":11,
                  "y":664},
                "size":{
                  "width":80,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ff03ffd8bf7f4ee8819bb9ddc9584d28",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF008000,
              "opacity":1},
            "location":{
              "x":226,
              "y":659},
            "size":{
              "width":80,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"854d6fcdc17a4eaa8947c406c7c0cf88",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF008000,
                  "opacity":1},
                "location":{
                  "x":226,
                  "y":659},
                "size":{
                  "width":80,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dddfe3a62a7145e2ae6ecd7dfbd73194",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":147,
              "y":693},
            "size":{
              "width":159,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"041849537d3647cdafa0c5098563b08d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":147,
                  "y":693},
                "size":{
                  "width":159,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4527bc5c70464faabe40fbf064e3b327",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":104,
              "y":754},
            "size":{
              "width":111,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76617930d0e5439db027d4ce861cf124",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":104,
                  "y":754},
                "size":{
                  "width":111,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "4b39fa4a94e54e72b5420bae787e670f":{
      "scriptId":"u0"},
    "e490b9ac0ad74254adfc2b4ad6577088":{
      "scriptId":"u1"},
    "c2ec4e67d88b4afea9029fe794c74210":{
      "scriptId":"u2"},
    "c6c79d3c590e4757b555cf3ad705bbf0":{
      "scriptId":"u3"},
    "049ac0619ce743c59c3746da55fe7b8f":{
      "scriptId":"u4"},
    "6c9086bc71d34cb1a74a018b4282a699":{
      "scriptId":"u5"},
    "e323b60598d6471cb284c80bbdd079de":{
      "scriptId":"u6"},
    "2f99e9ab15374cf98f513b17371c2cdc":{
      "scriptId":"u7"},
    "e1a7dea7e02b465c9fe1ad80962bfd1a":{
      "scriptId":"u8"},
    "c2aa2ac1a1974e5b9d34cde4cb91c751":{
      "scriptId":"u9"},
    "26c4e482c1cf400fac169d059cef7bbb":{
      "scriptId":"u10"},
    "f3b07fb4c98a489ab47a819cd6b9e152":{
      "scriptId":"u11"},
    "0a6377082c474761b85fb492c216bf33":{
      "scriptId":"u12"},
    "ced9992eea9645d5801a62922eb6d4a0":{
      "scriptId":"u13"},
    "b5f05ec9e7e847fbad522de961312616":{
      "scriptId":"u14"},
    "b32a880d10794d97aefe4d6fd35ddf37":{
      "scriptId":"u15"},
    "d31d4601e11846edace11d7362d43826":{
      "scriptId":"u16"},
    "2c3539d109ab4cfdb3ec577f5d0f5f30":{
      "scriptId":"u17"},
    "0a262b73dbe44c839a25e67eedfa41d8":{
      "scriptId":"u18"},
    "100651ada57149aa8d0c78f2c7522c9c":{
      "scriptId":"u19"},
    "7fa6704826994125b46686d0f8a163c8":{
      "scriptId":"u20"},
    "acc6af3db2544f3b83695e6ed7169d87":{
      "scriptId":"u21"},
    "2d910cf89f9a4f9eb31f2f0d6aa36c25":{
      "scriptId":"u22"},
    "1b12405a7bc24072b869b5c2a88441a4":{
      "scriptId":"u23"},
    "503f3c3ff7a0439fa20fb903e971b086":{
      "scriptId":"u24"},
    "34127eb9fc5140b799a5a044c30e8835":{
      "scriptId":"u25"},
    "44555cdb998b4428908c2f2529504f8f":{
      "scriptId":"u26"},
    "df7784b3ec46462da54023d0c2d0de5a":{
      "scriptId":"u27"},
    "a7399fc2b6c745cd90f4578a24a7a8a9":{
      "scriptId":"u28"},
    "0fb392c71e254ba6936263be87918241":{
      "scriptId":"u29"},
    "23ad006d991947e6b75b02a29114c8d0":{
      "scriptId":"u30"},
    "1aa7561df6dc4848833eecaef8567c35":{
      "scriptId":"u31"},
    "8b65c61339cc408abff5030a2650f174":{
      "scriptId":"u32"},
    "5ce38b4f1e3940c99a9c051917457d6d":{
      "scriptId":"u33"},
    "f72c815dd6c0480298340b0e59f26446":{
      "scriptId":"u34"},
    "0662e9cad54c463686d2d8f3ecb0332e":{
      "scriptId":"u35"},
    "95d6e89b1cd54c08b77ed8206fdfa800":{
      "scriptId":"u36"},
    "5456fd8878eb4db89df06cc42ca78ab9":{
      "scriptId":"u37"},
    "253d90f332f44f5e9f4a7530efcb9139":{
      "scriptId":"u38"},
    "4f0fab635ced4e44a963a3367fce9806":{
      "scriptId":"u39"},
    "93fd67b2f07e41728dced0aef3cb849f":{
      "scriptId":"u40"},
    "65af0e9d941d48edb0eec44ec95ef56a":{
      "scriptId":"u41"},
    "121c1da0d341491bb833a4a9a87fe2fe":{
      "scriptId":"u42"},
    "26fbcd10018649968263791cf379221a":{
      "scriptId":"u43"},
    "47275b2f00e04f10a2369a556008ed6c":{
      "scriptId":"u44"},
    "6c0eb09e0ea94a59ad8bd4581c0b68fb":{
      "scriptId":"u45"},
    "7e607665585a4dc88866cde7cd34e49e":{
      "scriptId":"u46"},
    "5a2b4c3fa09144e19dd2f85c5cdb62ef":{
      "scriptId":"u47"},
    "b01f76617153457ea7de5ca385ba7bb0":{
      "scriptId":"u48"},
    "5d8555a582aa405d9e8ee95d93cb3c05":{
      "scriptId":"u49"},
    "d79bb191d392459cb803985816f9951b":{
      "scriptId":"u50"},
    "39e9298f882848109602c3e08e2d36a1":{
      "scriptId":"u51"},
    "ab5509c9e06748cfb7afc483b9a87209":{
      "scriptId":"u52"},
    "c4ba884452c34d2aaa74e77a1c145309":{
      "scriptId":"u53"},
    "55cad1786d3f4e40ab855da2265f2224":{
      "scriptId":"u54"},
    "b7134190e8e647d69ea8c975f485978b":{
      "scriptId":"u55"},
    "2a2dba3e9d4c45d4920eff89ebfe4dcb":{
      "scriptId":"u56"},
    "6971d4f622914212844834804096aac7":{
      "scriptId":"u57"},
    "a38ef28e57c745d8baf17db18f5dfc40":{
      "scriptId":"u58"},
    "a6a5b0c273234e2597b8391510fea893":{
      "scriptId":"u59"},
    "0f58297bec6d4c34899a053b3e430973":{
      "scriptId":"u60"},
    "f642bda127e3483f8292ffcff0464f84":{
      "scriptId":"u61"},
    "90a6322248e2493ab8bb2d0fa507d255":{
      "scriptId":"u62"},
    "c238200bf65f4dae86c3b6f4ff18984d":{
      "scriptId":"u63"},
    "0fd654ba13f94256b673fa117c1da11a":{
      "scriptId":"u64"},
    "7e0abba3a46b4c7e837004a387ad13a6":{
      "scriptId":"u65"},
    "8fb964c13a79405ca1e63badc3e0aef7":{
      "scriptId":"u66"},
    "f0b7c68bb88844d18dbf7c7fe18cb70e":{
      "scriptId":"u67"},
    "cf09a4c4ddf2406b8cef83222c8fd5b2":{
      "scriptId":"u68"},
    "450114e1637942f5b5032419a0c80392":{
      "scriptId":"u69"},
    "0a3ce819e4784acfb6302f54d4584dbb":{
      "scriptId":"u70"},
    "0acfb9f732714a9591ce35eaddc43883":{
      "scriptId":"u71"},
    "b97e29bb1d2f4270b6f6decb76783bdc":{
      "scriptId":"u72"},
    "d4360b377f414af197b8169f90d17887":{
      "scriptId":"u73"},
    "c12cfc973c464ec58f342ec37edf7aa9":{
      "scriptId":"u74"},
    "6a405de398a84ab29f66198793ce1d1c":{
      "scriptId":"u75"},
    "41193646fa864c68933097fc411b7860":{
      "scriptId":"u76"},
    "657615f8aef14148ad733a1cd506b4c9":{
      "scriptId":"u77"},
    "eb446f59d79c4267bdba862af74fba41":{
      "scriptId":"u78"},
    "7921aab1a58c4de5bfb7f179130912d0":{
      "scriptId":"u79"},
    "0ea32a136e374aada80181481df49a3b":{
      "scriptId":"u80"},
    "034144a559dd47d4abed9f0df33000dd":{
      "scriptId":"u81"},
    "4807d43620044f75bfcf4f55cca3442a":{
      "scriptId":"u82"},
    "0477721038b34d3799cc5d4e78de1f7f":{
      "scriptId":"u83"},
    "123268658dac4e44b3ea3ed83dc797ef":{
      "scriptId":"u84"},
    "ff03ffd8bf7f4ee8819bb9ddc9584d28":{
      "scriptId":"u85"},
    "854d6fcdc17a4eaa8947c406c7c0cf88":{
      "scriptId":"u86"},
    "dddfe3a62a7145e2ae6ecd7dfbd73194":{
      "scriptId":"u87"},
    "041849537d3647cdafa0c5098563b08d":{
      "scriptId":"u88"},
    "4527bc5c70464faabe40fbf064e3b327":{
      "scriptId":"u89"},
    "76617930d0e5439db027d4ce861cf124":{
      "scriptId":"u90"}}});