$axure.loadCurrentPage({
  "url":"钱包.html",
  "generationDate":new Date(1496903830271.76),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"sfz",
"sfz_n"],
  "page":{
    "packageId":"9bfa496cbf444ea6bc890e441de13308",
    "type":"Axure:Page",
    "name":"钱包",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f9f93137def349f495fe05660298af11",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "size":{
              "width":320,
              "height":500},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5bfcbc4a1cd0433da5f260ef0a2c6d11",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "size":{
                  "width":320,
                  "height":500},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/钱包/u0.png"}},
{
          "id":"7f8ce0ce6c20452b833ae807a7911b93",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "fixedHorizontal":"left",
          "fixedMarginHorizontal":0,
          "fixedVertical":"top",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"eb4cabd4dc0940629e7d0a2a892df170",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"978e5ec7a1a9459d82dfb6cc74268c4c",
                  "label":"",
                  "parentDynamicPanel":"7f8ce0ce6c20452b833ae807a7911b93",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF1C222E},
                    "size":{
                      "width":320,
                      "height":64},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"da4e50264e234226850c290c29b8cc0c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7f8ce0ce6c20452b833ae807a7911b93",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF1C222E},
                        "size":{
                          "width":320,
                          "height":64},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u3.png"}},
{
                  "id":"14f894c65e674ba2ab3f3ae996504a2f",
                  "label":"",
                  "parentDynamicPanel":"7f8ce0ce6c20452b833ae807a7911b93",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Heiti SC Regular', 'Heiti SC'",
                    "fontSize":"18px",
                    "fontWeight":"200",
                    "horizontalAlignment":"center",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":78,
                      "y":35},
                    "size":{
                      "width":163,
                      "height":22},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"887aafbbcfd047beb16dbaad9e27a528",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7f8ce0ce6c20452b833ae807a7911b93",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Heiti SC Regular', 'Heiti SC'",
                        "fontSize":"18px",
                        "fontWeight":"200",
                        "horizontalAlignment":"center",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":78,
                          "y":35},
                        "size":{
                          "width":163,
                          "height":22},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"72db434a09b74846adf4f68b07e2e919",
                  "label":"",
                  "parentDynamicPanel":"7f8ce0ce6c20452b833ae807a7911b93",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":320,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"214cdfd763a34966ae29fc1781e45204",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7f8ce0ce6c20452b833ae807a7911b93",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":320,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u7.png"}},
{
                  "id":"9da86c82347348a9ac405eb2b30f8c67",
                  "label":"",
                  "parentDynamicPanel":"7f8ce0ce6c20452b833ae807a7911b93",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Heiti SC Regular', 'Heiti SC'",
                    "fontSize":"16px",
                    "fontWeight":"200",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":27,
                      "y":36},
                    "size":{
                      "width":63,
                      "height":19},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"eaae0cd6ec5b486fad5053f5f508b7e9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7f8ce0ce6c20452b833ae807a7911b93",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Heiti SC Regular', 'Heiti SC'",
                        "fontSize":"16px",
                        "fontWeight":"200",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":27,
                          "y":36},
                        "size":{
                          "width":63,
                          "height":19},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"01dab217ca6f42229de0ce6c40d077e3",
                  "label":"",
                  "parentDynamicPanel":"7f8ce0ce6c20452b833ae807a7911b93",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Lucida Grande Regular', 'Lucida Grande'",
                    "fontSize":"20px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":9,
                      "y":31},
                    "size":{
                      "width":22,
                      "height":29}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c65b4a1a86cd4220a22c1b83e1ddb3b9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7f8ce0ce6c20452b833ae807a7911b93",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Lucida Grande Regular', 'Lucida Grande'",
                        "fontSize":"20px",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":9,
                          "y":31},
                        "size":{
                          "width":22,
                          "height":29}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"a94fe34ecc20426dbc651851f01693fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":15,
              "y":90},
            "size":{
              "width":285,
              "height":370}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1627b74cb6a24ffb81fe165a7d459f0d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":15,
                  "y":90},
                "size":{
                  "width":285,
                  "height":370}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/钱包/u13.png"}},
{
          "id":"d90c26f6fede423fa581a2ee7e717b29",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "location":{
              "x":133,
              "y":140},
            "size":{
              "width":49,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5da64f5ae44e4f0d91d76d2bafb72794",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "location":{
                  "x":133,
                  "y":140},
                "size":{
                  "width":49,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2c964caff197431fb38f4271fd87a73c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"48px",
            "fontWeight":"400",
            "location":{
              "x":86,
              "y":178},
            "size":{
              "width":143,
              "height":57}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b6ad4e351a849bf80f6169d251153c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"48px",
                "fontWeight":"400",
                "location":{
                  "x":86,
                  "y":178},
                "size":{
                  "width":143,
                  "height":57}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2ccd0e9350e44de7aff4c14dc2e9b66b",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":40,
              "y":270},
            "size":{
              "width":240,
              "height":43}},
          "adaptiveStyles":{
}},
{
          "id":"a74deff40afc4daab45157befa24120f",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":40,
              "y":330},
            "size":{
              "width":240,
              "height":43}},
          "adaptiveStyles":{
}},
{
          "id":"f344b460f78c4e14bf22d0678c324fb1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "underline":true,
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":112,
              "y":401},
            "size":{
              "width":97,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54ee8bed0a6c4e6e9c1c1079409c7553",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":112,
                  "y":401},
                "size":{
                  "width":97,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "f9f93137def349f495fe05660298af11":{
      "scriptId":"u0"},
    "5bfcbc4a1cd0433da5f260ef0a2c6d11":{
      "scriptId":"u1"},
    "7f8ce0ce6c20452b833ae807a7911b93":{
      "scriptId":"u2"},
    "978e5ec7a1a9459d82dfb6cc74268c4c":{
      "scriptId":"u3"},
    "da4e50264e234226850c290c29b8cc0c":{
      "scriptId":"u4"},
    "14f894c65e674ba2ab3f3ae996504a2f":{
      "scriptId":"u5"},
    "887aafbbcfd047beb16dbaad9e27a528":{
      "scriptId":"u6"},
    "72db434a09b74846adf4f68b07e2e919":{
      "scriptId":"u7"},
    "214cdfd763a34966ae29fc1781e45204":{
      "scriptId":"u8"},
    "9da86c82347348a9ac405eb2b30f8c67":{
      "scriptId":"u9"},
    "eaae0cd6ec5b486fad5053f5f508b7e9":{
      "scriptId":"u10"},
    "01dab217ca6f42229de0ce6c40d077e3":{
      "scriptId":"u11"},
    "c65b4a1a86cd4220a22c1b83e1ddb3b9":{
      "scriptId":"u12"},
    "a94fe34ecc20426dbc651851f01693fb":{
      "scriptId":"u13"},
    "1627b74cb6a24ffb81fe165a7d459f0d":{
      "scriptId":"u14"},
    "d90c26f6fede423fa581a2ee7e717b29":{
      "scriptId":"u15"},
    "5da64f5ae44e4f0d91d76d2bafb72794":{
      "scriptId":"u16"},
    "2c964caff197431fb38f4271fd87a73c":{
      "scriptId":"u17"},
    "2b6ad4e351a849bf80f6169d251153c4":{
      "scriptId":"u18"},
    "2ccd0e9350e44de7aff4c14dc2e9b66b":{
      "scriptId":"u19"},
    "a74deff40afc4daab45157befa24120f":{
      "scriptId":"u20"},
    "f344b460f78c4e14bf22d0678c324fb1":{
      "scriptId":"u21"},
    "54ee8bed0a6c4e6e9c1c1079409c7553":{
      "scriptId":"u22"}}});