$axure.loadCurrentPage({
  "url":"a-01_版本说明.html",
  "generationDate":new Date(1496903818999.76),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"sfz",
"sfz_n"],
  "page":{
    "packageId":"fff1ede2d6c04051b5bd8a6753b55cff",
    "type":"Axure:Page",
    "name":"A-01 版本说明",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"736c0e3feb9647eb9f1a452827179d3f",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":150},
            "size":{
              "width":830,
              "height":215}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"89aecb2cc4db4146ac1da170c5d02d6a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEEEEEE},
                "size":{
                  "width":126,
                  "height":37},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD6DEE3}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f54a9b5f370041e493d5ed9effab3efd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontSize":"16px",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFEEEEEE},
                    "size":{
                      "width":126,
                      "height":37},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD6DEE3}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/a-01_版本说明/u1.png"}},
{
              "id":"a4804e92eb044704bad6c22757f0e235",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "stateStyles":{
                  "mouseDown":{
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF009DDA}}},
                "location":{
                  "x":0,
                  "y":37},
                "size":{
                  "width":126,
                  "height":34},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD6DEE3}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a272b86e28154ef9803039d5776153cd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "stateStyles":{
                      "mouseDown":{
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF009DDA}}},
                    "location":{
                      "x":0,
                      "y":37},
                    "size":{
                      "width":126,
                      "height":34},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD6DEE3}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/a-01_版本说明/u9.png",
                "mouseDown~":"images/a-01_版本说明/u9.png"}},
{
              "id":"888836bb53f343a6806f6930dbac3835",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"right",
                "verticalAlignment":"middle",
                "stateStyles":{
                  "mouseDown":{
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF009DDA}}},
                "location":{
                  "x":0,
                  "y":71},
                "size":{
                  "width":126,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD6DEE3}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5a535bfb382e4e698e4945b23ab59baa",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "horizontalAlignment":"right",
                    "verticalAlignment":"middle",
                    "stateStyles":{
                      "mouseDown":{
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF009DDA}}},
                    "location":{
                      "x":0,
                      "y":71},
                    "size":{
                      "width":126,
                      "height":36},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD6DEE3}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/a-01_版本说明/u17.png",
                "mouseDown~":"images/a-01_版本说明/u17.png"}},
{
              "id":"eb55cfb957cf46cba6ebbe1a8e0d0427",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEEEEEE},
                "location":{
                  "x":521,
                  "y":0},
                "size":{
                  "width":162,
                  "height":37},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD6DEE3}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1096dac800584befb33e35a7705654e2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontSize":"16px",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFEEEEEE},
                    "location":{
                      "x":521,
                      "y":0},
                    "size":{
                      "width":162,
                      "height":37},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD6DEE3}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/a-01_版本说明/u5.png"}},
{
              "id":"a54b94aba10d4d0ca2411f7b12abc1ff",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":521,
                  "y":37},
                "size":{
                  "width":162,
                  "height":34},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD6DEE3}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a93c32a2fc0847e3bee31e627756aa79",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":521,
                      "y":37},
                    "size":{
                      "width":162,
                      "height":34},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD6DEE3}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/a-01_版本说明/u13.png"}},
{
              "id":"94e3106f99664e19b233c407d610b83a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":521,
                  "y":71},
                "size":{
                  "width":162,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD6DEE3}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0759b22b62044bd3bfe3fd748f04a7ba",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":521,
                      "y":71},
                    "size":{
                      "width":162,
                      "height":36},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD6DEE3}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/a-01_版本说明/u21.png"}},
{
              "id":"c17494a2e71a4dc997d7290d4bcca65d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "horizontalAlignment":"right",
                "verticalAlignment":"middle",
                "stateStyles":{
                  "mouseDown":{
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF009DDA}}},
                "location":{
                  "x":0,
                  "y":107},
                "size":{
                  "width":126,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD6DEE3}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"014bbe8c1c6b4494b22627a40f664475",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontSize":"14px",
                    "fontWeight":"700",
                    "horizontalAlignment":"right",
                    "verticalAlignment":"middle",
                    "stateStyles":{
                      "mouseDown":{
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF009DDA}}},
                    "location":{
                      "x":0,
                      "y":107},
                    "size":{
                      "width":126,
                      "height":36},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD6DEE3}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/a-01_版本说明/u17.png",
                "mouseDown~":"images/a-01_版本说明/u17.png"}},
{
              "id":"6f3b9c05bd75414881bfe4ee6fdb99cc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":521,
                  "y":107},
                "size":{
                  "width":162,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD6DEE3}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2c5e73755f644723988a3491b0104011",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":521,
                      "y":107},
                    "size":{
                      "width":162,
                      "height":36},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD6DEE3}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/a-01_版本说明/u21.png"}},
{
              "id":"5353db1c27404b09a80d5391c12aec72",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEEEEEE},
                "location":{
                  "x":126,
                  "y":0},
                "size":{
                  "width":395,
                  "height":37},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD6DEE3}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5e138da814ac4ec39e2a6f560057988e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontSize":"16px",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFEEEEEE},
                    "location":{
                      "x":126,
                      "y":0},
                    "size":{
                      "width":395,
                      "height":37},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD6DEE3}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/a-01_版本说明/u3.png"}},
{
              "id":"9e79c9c0e4504d4287a817f391853a35",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "stateStyles":{
                  "mouseDown":{
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF009DDA}}},
                "location":{
                  "x":126,
                  "y":37},
                "size":{
                  "width":395,
                  "height":34},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD6DEE3}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"273d3719b9de41d6822c64bb00bff469",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "stateStyles":{
                      "mouseDown":{
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF009DDA}}},
                    "location":{
                      "x":126,
                      "y":37},
                    "size":{
                      "width":395,
                      "height":34},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD6DEE3}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/a-01_版本说明/u11.png",
                "mouseDown~":"images/a-01_版本说明/u11.png"}},
{
              "id":"9d8a54ae193042f4947e73db454f72a7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"right",
                "verticalAlignment":"middle",
                "stateStyles":{
                  "mouseDown":{
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF009DDA}}},
                "location":{
                  "x":126,
                  "y":71},
                "size":{
                  "width":395,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD6DEE3}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1fa16ccd00db4629bce58a9c9d785d91",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "horizontalAlignment":"right",
                    "verticalAlignment":"middle",
                    "stateStyles":{
                      "mouseDown":{
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF009DDA}}},
                    "location":{
                      "x":126,
                      "y":71},
                    "size":{
                      "width":395,
                      "height":36},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD6DEE3}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/a-01_版本说明/u19.png",
                "mouseDown~":"images/a-01_版本说明/u19.png"}},
{
              "id":"00bb0a16a90a494dafe16c5cb95ac6c6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "horizontalAlignment":"right",
                "verticalAlignment":"middle",
                "stateStyles":{
                  "mouseDown":{
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF009DDA}}},
                "location":{
                  "x":126,
                  "y":107},
                "size":{
                  "width":395,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD6DEE3}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"20b0c9ae3ea84257acbd4571709b9352",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontSize":"14px",
                    "fontWeight":"700",
                    "horizontalAlignment":"right",
                    "verticalAlignment":"middle",
                    "stateStyles":{
                      "mouseDown":{
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF009DDA}}},
                    "location":{
                      "x":126,
                      "y":107},
                    "size":{
                      "width":395,
                      "height":36},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD6DEE3}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/a-01_版本说明/u19.png",
                "mouseDown~":"images/a-01_版本说明/u19.png"}},
{
              "id":"567bc5e6c1d5471e90ebde8dadcddfd6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "horizontalAlignment":"right",
                "verticalAlignment":"middle",
                "stateStyles":{
                  "mouseDown":{
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF009DDA}}},
                "location":{
                  "x":0,
                  "y":143},
                "size":{
                  "width":126,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD6DEE3}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"014abcbfa8ff4ccb9c5cda0cfffc78fd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontSize":"14px",
                    "fontWeight":"700",
                    "horizontalAlignment":"right",
                    "verticalAlignment":"middle",
                    "stateStyles":{
                      "mouseDown":{
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF009DDA}}},
                    "location":{
                      "x":0,
                      "y":143},
                    "size":{
                      "width":126,
                      "height":36},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD6DEE3}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/a-01_版本说明/u17.png",
                "mouseDown~":"images/a-01_版本说明/u17.png"}},
{
              "id":"9b6c54f9e15a4e8e9b1426e072f3adab",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "horizontalAlignment":"right",
                "verticalAlignment":"middle",
                "stateStyles":{
                  "mouseDown":{
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF009DDA}}},
                "location":{
                  "x":126,
                  "y":143},
                "size":{
                  "width":395,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD6DEE3}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c90542140eb842ebb871567632167c9a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontSize":"14px",
                    "fontWeight":"700",
                    "horizontalAlignment":"right",
                    "verticalAlignment":"middle",
                    "stateStyles":{
                      "mouseDown":{
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF009DDA}}},
                    "location":{
                      "x":126,
                      "y":143},
                    "size":{
                      "width":395,
                      "height":36},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD6DEE3}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/a-01_版本说明/u19.png",
                "mouseDown~":"images/a-01_版本说明/u19.png"}},
{
              "id":"fd2cfeda11cb4723b3d1733782ee1744",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":521,
                  "y":143},
                "size":{
                  "width":162,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD6DEE3}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e005101f14174399a81d505c765f6f14",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":521,
                      "y":143},
                    "size":{
                      "width":162,
                      "height":36},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD6DEE3}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/a-01_版本说明/u21.png"}},
{
              "id":"0d74f29f780a4e8db3132e88e40e0740",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "horizontalAlignment":"right",
                "verticalAlignment":"middle",
                "stateStyles":{
                  "mouseDown":{
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF009DDA}}},
                "location":{
                  "x":0,
                  "y":179},
                "size":{
                  "width":126,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD6DEE3}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c281f23f03204925b889918fb728866c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontSize":"14px",
                    "fontWeight":"700",
                    "horizontalAlignment":"right",
                    "verticalAlignment":"middle",
                    "stateStyles":{
                      "mouseDown":{
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF009DDA}}},
                    "location":{
                      "x":0,
                      "y":179},
                    "size":{
                      "width":126,
                      "height":36},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD6DEE3}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/a-01_版本说明/u41.png",
                "mouseDown~":"images/a-01_版本说明/u41.png"}},
{
              "id":"d4c578d0cb7e46b4ac6300bf417f2b4d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "horizontalAlignment":"right",
                "verticalAlignment":"middle",
                "stateStyles":{
                  "mouseDown":{
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF009DDA}}},
                "location":{
                  "x":126,
                  "y":179},
                "size":{
                  "width":395,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD6DEE3}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a5cb02cab2534b99a63426aff74c7fc5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontSize":"14px",
                    "fontWeight":"700",
                    "horizontalAlignment":"right",
                    "verticalAlignment":"middle",
                    "stateStyles":{
                      "mouseDown":{
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF009DDA}}},
                    "location":{
                      "x":126,
                      "y":179},
                    "size":{
                      "width":395,
                      "height":36},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD6DEE3}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/a-01_版本说明/u43.png",
                "mouseDown~":"images/a-01_版本说明/u43.png"}},
{
              "id":"ddca30a1e7924d7d8c63f974a18da84b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":521,
                  "y":179},
                "size":{
                  "width":162,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD6DEE3}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"69de74cdac354001acc548adc98a8a5b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":521,
                      "y":179},
                    "size":{
                      "width":162,
                      "height":36},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD6DEE3}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/a-01_版本说明/u45.png"}},
{
              "id":"47b5423ffbdd4515b9e7c4729196f506",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEEEEEE},
                "location":{
                  "x":683,
                  "y":0},
                "size":{
                  "width":147,
                  "height":37},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD6DEE3}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b1a17f3170424c1eb19e705f91fb1fed",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontSize":"16px",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFEEEEEE},
                    "location":{
                      "x":683,
                      "y":0},
                    "size":{
                      "width":147,
                      "height":37},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD6DEE3}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/a-01_版本说明/u7.png"}},
{
              "id":"a236e4fd185b405698794727c52ef236",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":683,
                  "y":37},
                "size":{
                  "width":147,
                  "height":34},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD6DEE3}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5b538f4fdcc644d98dc481634c666127",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":683,
                      "y":37},
                    "size":{
                      "width":147,
                      "height":34},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD6DEE3}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/a-01_版本说明/u15.png"}},
{
              "id":"81e75c8f8db54cf78402be694b2f43ba",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":683,
                  "y":71},
                "size":{
                  "width":147,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD6DEE3}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c87dd0fdeb7f4392a2d72ab46d3d1da6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":683,
                      "y":71},
                    "size":{
                      "width":147,
                      "height":36},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD6DEE3}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/a-01_版本说明/u23.png"}},
{
              "id":"df7fa7f0d10147fda8f9d0a5481b175e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":683,
                  "y":107},
                "size":{
                  "width":147,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD6DEE3}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2f4cef6b717d479ea0ff45f270165e06",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":683,
                      "y":107},
                    "size":{
                      "width":147,
                      "height":36},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD6DEE3}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/a-01_版本说明/u23.png"}},
{
              "id":"a245298876794f8f9f6d692bc4c5cfa6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":683,
                  "y":143},
                "size":{
                  "width":147,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD6DEE3}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"91d01ce5f5994faea01b4fa1ce6d4f95",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":683,
                      "y":143},
                    "size":{
                      "width":147,
                      "height":36},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD6DEE3}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/a-01_版本说明/u23.png"}},
{
              "id":"4b0e6a3d84a44d18b73767aeb87a457d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":683,
                  "y":179},
                "size":{
                  "width":147,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD6DEE3}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f285f36dd2884d4e88520692f5800df4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":683,
                      "y":179},
                    "size":{
                      "width":147,
                      "height":36},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD6DEE3}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/a-01_版本说明/u47.png"}}]}]}},
  "masters":{
},
  "objectPaths":{
    "736c0e3feb9647eb9f1a452827179d3f":{
      "scriptId":"u0"},
    "89aecb2cc4db4146ac1da170c5d02d6a":{
      "scriptId":"u1"},
    "f54a9b5f370041e493d5ed9effab3efd":{
      "scriptId":"u2"},
    "5353db1c27404b09a80d5391c12aec72":{
      "scriptId":"u3"},
    "5e138da814ac4ec39e2a6f560057988e":{
      "scriptId":"u4"},
    "eb55cfb957cf46cba6ebbe1a8e0d0427":{
      "scriptId":"u5"},
    "1096dac800584befb33e35a7705654e2":{
      "scriptId":"u6"},
    "47b5423ffbdd4515b9e7c4729196f506":{
      "scriptId":"u7"},
    "b1a17f3170424c1eb19e705f91fb1fed":{
      "scriptId":"u8"},
    "a4804e92eb044704bad6c22757f0e235":{
      "scriptId":"u9"},
    "a272b86e28154ef9803039d5776153cd":{
      "scriptId":"u10"},
    "9e79c9c0e4504d4287a817f391853a35":{
      "scriptId":"u11"},
    "273d3719b9de41d6822c64bb00bff469":{
      "scriptId":"u12"},
    "a54b94aba10d4d0ca2411f7b12abc1ff":{
      "scriptId":"u13"},
    "a93c32a2fc0847e3bee31e627756aa79":{
      "scriptId":"u14"},
    "a236e4fd185b405698794727c52ef236":{
      "scriptId":"u15"},
    "5b538f4fdcc644d98dc481634c666127":{
      "scriptId":"u16"},
    "888836bb53f343a6806f6930dbac3835":{
      "scriptId":"u17"},
    "5a535bfb382e4e698e4945b23ab59baa":{
      "scriptId":"u18"},
    "9d8a54ae193042f4947e73db454f72a7":{
      "scriptId":"u19"},
    "1fa16ccd00db4629bce58a9c9d785d91":{
      "scriptId":"u20"},
    "94e3106f99664e19b233c407d610b83a":{
      "scriptId":"u21"},
    "0759b22b62044bd3bfe3fd748f04a7ba":{
      "scriptId":"u22"},
    "81e75c8f8db54cf78402be694b2f43ba":{
      "scriptId":"u23"},
    "c87dd0fdeb7f4392a2d72ab46d3d1da6":{
      "scriptId":"u24"},
    "c17494a2e71a4dc997d7290d4bcca65d":{
      "scriptId":"u25"},
    "014bbe8c1c6b4494b22627a40f664475":{
      "scriptId":"u26"},
    "00bb0a16a90a494dafe16c5cb95ac6c6":{
      "scriptId":"u27"},
    "20b0c9ae3ea84257acbd4571709b9352":{
      "scriptId":"u28"},
    "6f3b9c05bd75414881bfe4ee6fdb99cc":{
      "scriptId":"u29"},
    "2c5e73755f644723988a3491b0104011":{
      "scriptId":"u30"},
    "df7fa7f0d10147fda8f9d0a5481b175e":{
      "scriptId":"u31"},
    "2f4cef6b717d479ea0ff45f270165e06":{
      "scriptId":"u32"},
    "567bc5e6c1d5471e90ebde8dadcddfd6":{
      "scriptId":"u33"},
    "014abcbfa8ff4ccb9c5cda0cfffc78fd":{
      "scriptId":"u34"},
    "9b6c54f9e15a4e8e9b1426e072f3adab":{
      "scriptId":"u35"},
    "c90542140eb842ebb871567632167c9a":{
      "scriptId":"u36"},
    "fd2cfeda11cb4723b3d1733782ee1744":{
      "scriptId":"u37"},
    "e005101f14174399a81d505c765f6f14":{
      "scriptId":"u38"},
    "a245298876794f8f9f6d692bc4c5cfa6":{
      "scriptId":"u39"},
    "91d01ce5f5994faea01b4fa1ce6d4f95":{
      "scriptId":"u40"},
    "0d74f29f780a4e8db3132e88e40e0740":{
      "scriptId":"u41"},
    "c281f23f03204925b889918fb728866c":{
      "scriptId":"u42"},
    "d4c578d0cb7e46b4ac6300bf417f2b4d":{
      "scriptId":"u43"},
    "a5cb02cab2534b99a63426aff74c7fc5":{
      "scriptId":"u44"},
    "ddca30a1e7924d7d8c63f974a18da84b":{
      "scriptId":"u45"},
    "69de74cdac354001acc548adc98a8a5b":{
      "scriptId":"u46"},
    "4b0e6a3d84a44d18b73767aeb87a457d":{
      "scriptId":"u47"},
    "f285f36dd2884d4e88520692f5800df4":{
      "scriptId":"u48"}}});