$axure.loadCurrentPage({
  "url":"充值_1.html",
  "generationDate":new Date(1496903835958.76),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"sfz",
"sfz_n"],
  "page":{
    "packageId":"06dd029d81c74db09434619d16d4e7da",
    "type":"Axure:Page",
    "name":"充值",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f7a3dd3c635d45cbb35139d79e478570",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "size":{
              "width":320,
              "height":500},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1af40f2034154056ae392681f2e13b1f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "size":{
                  "width":320,
                  "height":500},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/钱包/u0.png"}},
{
          "id":"c21c6229864a42f296978676f1219075",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "fixedHorizontal":"left",
          "fixedMarginHorizontal":0,
          "fixedVertical":"top",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"994b8ff631b44f9a89473610de3c14f8",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"a08c428377fd4ad0b133923f1670153c",
                  "label":"",
                  "parentDynamicPanel":"c21c6229864a42f296978676f1219075",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF1C222E},
                    "size":{
                      "width":320,
                      "height":64},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"050c9ab9a9864f73bd11b554f1f94c44",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c21c6229864a42f296978676f1219075",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF1C222E},
                        "size":{
                          "width":320,
                          "height":64},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u3.png"}},
{
                  "id":"e423a3fbf9564e878d2ca341686200cf",
                  "label":"",
                  "parentDynamicPanel":"c21c6229864a42f296978676f1219075",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Heiti SC Regular', 'Heiti SC'",
                    "fontSize":"18px",
                    "fontWeight":"200",
                    "horizontalAlignment":"center",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":78,
                      "y":35},
                    "size":{
                      "width":163,
                      "height":22},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"440aff83608946a1bf4582c218f610a8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c21c6229864a42f296978676f1219075",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Heiti SC Regular', 'Heiti SC'",
                        "fontSize":"18px",
                        "fontWeight":"200",
                        "horizontalAlignment":"center",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":78,
                          "y":35},
                        "size":{
                          "width":163,
                          "height":22},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"4bdf709977e64b30b303b7c7ac98c2ae",
                  "label":"",
                  "parentDynamicPanel":"c21c6229864a42f296978676f1219075",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":320,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f15dd0ae60f140ea84d7b6431aa6fc20",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c21c6229864a42f296978676f1219075",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":320,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u7.png"}},
{
                  "id":"706f723237ca4166bb83edd7a1580812",
                  "label":"",
                  "parentDynamicPanel":"c21c6229864a42f296978676f1219075",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Heiti SC Regular', 'Heiti SC'",
                    "fontSize":"16px",
                    "fontWeight":"200",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":27,
                      "y":36},
                    "size":{
                      "width":63,
                      "height":19},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0b1bb700343a47149e4c5727bd71e438",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c21c6229864a42f296978676f1219075",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Heiti SC Regular', 'Heiti SC'",
                        "fontSize":"16px",
                        "fontWeight":"200",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":27,
                          "y":36},
                        "size":{
                          "width":63,
                          "height":19},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"2d2ea2b5aef44033bd2ec58446e4a092",
                  "label":"",
                  "parentDynamicPanel":"c21c6229864a42f296978676f1219075",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Lucida Grande Regular', 'Lucida Grande'",
                    "fontSize":"20px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":9,
                      "y":31},
                    "size":{
                      "width":22,
                      "height":29}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2ef38583a0ef4da59bf5a7fe085ea95b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c21c6229864a42f296978676f1219075",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Lucida Grande Regular', 'Lucida Grande'",
                        "fontSize":"20px",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":9,
                          "y":31},
                        "size":{
                          "width":22,
                          "height":29}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"108a163f0bc148cd8dc0d159ef626e50",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "location":{
              "x":0,
              "y":150},
            "size":{
              "width":320,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"63186c0d962541d4b2f6767d74f0000b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "location":{
                  "x":0,
                  "y":150},
                "size":{
                  "width":320,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择号码-双色球/u137.png"}},
{
          "id":"d2bb111cba28467ead11ed75116e4652",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "stateStyles":{
              "hint":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1}}},
            "location":{
              "x":60,
              "y":157.5},
            "size":{
              "width":200,
              "height":35}},
          "adaptiveStyles":{
},
          "placeholderText":"请输入充值金额"},
{
          "id":"33cf8fb3af1b45b3b07e403d2edb06fc",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":10,
              "y":240},
            "size":{
              "width":280,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"0019c8f5e3dc4f0a9f24fbd199a233a7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":10,
              "y":210},
            "size":{
              "width":290,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a702e16e21a4d0580f0877d5f9550e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":10,
                  "y":210},
                "size":{
                  "width":290,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1fcc0b46636e4f2baafed0825152b133",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":0,
              "y":74},
            "size":{
              "width":320,
              "height":66}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ce224390a7042489601958eb2a63169",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":0,
                  "y":74},
                "size":{
                  "width":320,
                  "height":66}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值/u19.png"}},
{
          "id":"8c1f9c4abc6c4509b141321cd6057828",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":10,
              "y":80},
            "size":{
              "width":60,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"32f2262e6b2a417a807b89bec9fec136",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":10,
                  "y":80},
                "size":{
                  "width":60,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值/u21.png"}},
{
          "id":"41de213e3a62437cb8b8e0d94a55184f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":80,
              "y":80},
            "size":{
              "width":100,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"56b6359db80a48b688ce52de86c5d974",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":80,
                  "y":80},
                "size":{
                  "width":100,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e0edec62e5b04497a5d351f628a8774e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":80,
              "y":114},
            "size":{
              "width":120,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1f2b0459a374a069ade7f6161a1cf90",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":80,
                  "y":114},
                "size":{
                  "width":120,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"97b74ce0d68f4687b70601f3b99153e0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "opacity":"0.7",
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":200,
              "y":530},
            "size":{
              "width":120,
              "height":100},
            "cornerRadiusTopLeft":"16"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77209fa225424b33813aabbc690add22",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "opacity":"0.7",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":200,
                  "y":530},
                "size":{
                  "width":120,
                  "height":100},
                "cornerRadiusTopLeft":"16"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值_1/u27.png"}},
{
          "id":"68d9d9ff60b64bf2b44a0cdc09b6ba97",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":208,
              "y":540},
            "size":{
              "width":102,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b31d604652a04f63a787f485244a7eb3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":208,
                  "y":540},
                "size":{
                  "width":102,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "f7a3dd3c635d45cbb35139d79e478570":{
      "scriptId":"u0"},
    "1af40f2034154056ae392681f2e13b1f":{
      "scriptId":"u1"},
    "c21c6229864a42f296978676f1219075":{
      "scriptId":"u2"},
    "a08c428377fd4ad0b133923f1670153c":{
      "scriptId":"u3"},
    "050c9ab9a9864f73bd11b554f1f94c44":{
      "scriptId":"u4"},
    "e423a3fbf9564e878d2ca341686200cf":{
      "scriptId":"u5"},
    "440aff83608946a1bf4582c218f610a8":{
      "scriptId":"u6"},
    "4bdf709977e64b30b303b7c7ac98c2ae":{
      "scriptId":"u7"},
    "f15dd0ae60f140ea84d7b6431aa6fc20":{
      "scriptId":"u8"},
    "706f723237ca4166bb83edd7a1580812":{
      "scriptId":"u9"},
    "0b1bb700343a47149e4c5727bd71e438":{
      "scriptId":"u10"},
    "2d2ea2b5aef44033bd2ec58446e4a092":{
      "scriptId":"u11"},
    "2ef38583a0ef4da59bf5a7fe085ea95b":{
      "scriptId":"u12"},
    "108a163f0bc148cd8dc0d159ef626e50":{
      "scriptId":"u13"},
    "63186c0d962541d4b2f6767d74f0000b":{
      "scriptId":"u14"},
    "d2bb111cba28467ead11ed75116e4652":{
      "scriptId":"u15"},
    "33cf8fb3af1b45b3b07e403d2edb06fc":{
      "scriptId":"u16"},
    "0019c8f5e3dc4f0a9f24fbd199a233a7":{
      "scriptId":"u17"},
    "4a702e16e21a4d0580f0877d5f9550e0":{
      "scriptId":"u18"},
    "1fcc0b46636e4f2baafed0825152b133":{
      "scriptId":"u19"},
    "3ce224390a7042489601958eb2a63169":{
      "scriptId":"u20"},
    "8c1f9c4abc6c4509b141321cd6057828":{
      "scriptId":"u21"},
    "32f2262e6b2a417a807b89bec9fec136":{
      "scriptId":"u22"},
    "41de213e3a62437cb8b8e0d94a55184f":{
      "scriptId":"u23"},
    "56b6359db80a48b688ce52de86c5d974":{
      "scriptId":"u24"},
    "e0edec62e5b04497a5d351f628a8774e":{
      "scriptId":"u25"},
    "d1f2b0459a374a069ade7f6161a1cf90":{
      "scriptId":"u26"},
    "97b74ce0d68f4687b70601f3b99153e0":{
      "scriptId":"u27"},
    "77209fa225424b33813aabbc690add22":{
      "scriptId":"u28"},
    "68d9d9ff60b64bf2b44a0cdc09b6ba97":{
      "scriptId":"u29"},
    "b31d604652a04f63a787f485244a7eb3":{
      "scriptId":"u30"}}});