$axure.loadCurrentPage({
  "url":"委托兑奖.html",
  "generationDate":new Date(1496903836394.76),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"sfz",
"sfz_n"],
  "page":{
    "packageId":"a5d7a8fffe35477b9444c89216bed98a",
    "type":"Axure:Page",
    "name":"委托兑奖",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"196151baf21d42819ed2246024b07470",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "size":{
              "width":320,
              "height":780},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d5c61e63f084849ae8018eb559b5f00",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "size":{
                  "width":320,
                  "height":780},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/委托兑奖/u0.png"}},
{
          "id":"f6461b04085a426b9b16f5fa19a8800a",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "fixedHorizontal":"left",
          "fixedMarginHorizontal":0,
          "fixedVertical":"top",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"841646f6ec4c4e1081aeb02e9a99f768",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"1c14c94148244c44b595715e32350b94",
                  "label":"",
                  "parentDynamicPanel":"f6461b04085a426b9b16f5fa19a8800a",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF1C222E},
                    "size":{
                      "width":320,
                      "height":64},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"45baeb451863478da554ee76771b2039",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f6461b04085a426b9b16f5fa19a8800a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF1C222E},
                        "size":{
                          "width":320,
                          "height":64},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u3.png"}},
{
                  "id":"5e90fb423c2a4b05ac74edd900b07c39",
                  "label":"",
                  "parentDynamicPanel":"f6461b04085a426b9b16f5fa19a8800a",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Heiti SC Regular', 'Heiti SC'",
                    "fontSize":"18px",
                    "fontWeight":"200",
                    "horizontalAlignment":"center",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":78,
                      "y":35},
                    "size":{
                      "width":163,
                      "height":22},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"57ef88ee5043405f8f97e73af66cef26",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f6461b04085a426b9b16f5fa19a8800a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Heiti SC Regular', 'Heiti SC'",
                        "fontSize":"18px",
                        "fontWeight":"200",
                        "horizontalAlignment":"center",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":78,
                          "y":35},
                        "size":{
                          "width":163,
                          "height":22},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"d8c0034cd8ce40e9b56e0124641aea52",
                  "label":"",
                  "parentDynamicPanel":"f6461b04085a426b9b16f5fa19a8800a",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":320,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ccfccefa554b4694bd195703dac485ad",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f6461b04085a426b9b16f5fa19a8800a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":320,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u7.png"}},
{
                  "id":"c806c6c75f7a4048abcd51fc4f23fbc3",
                  "label":"",
                  "parentDynamicPanel":"f6461b04085a426b9b16f5fa19a8800a",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Heiti SC Regular', 'Heiti SC'",
                    "fontSize":"16px",
                    "fontWeight":"200",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":27,
                      "y":36},
                    "size":{
                      "width":63,
                      "height":19},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1ff463645687494598c2a7ac9b6d6e2b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f6461b04085a426b9b16f5fa19a8800a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Heiti SC Regular', 'Heiti SC'",
                        "fontSize":"16px",
                        "fontWeight":"200",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":27,
                          "y":36},
                        "size":{
                          "width":63,
                          "height":19},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f80aa5e8cdff4474902fcfc82e895d27",
                  "label":"",
                  "parentDynamicPanel":"f6461b04085a426b9b16f5fa19a8800a",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Lucida Grande Regular', 'Lucida Grande'",
                    "fontSize":"20px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":9,
                      "y":31},
                    "size":{
                      "width":22,
                      "height":29}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ac687abdb44540b8b69653d1333fe973",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f6461b04085a426b9b16f5fa19a8800a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Lucida Grande Regular', 'Lucida Grande'",
                        "fontSize":"20px",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":9,
                          "y":31},
                        "size":{
                          "width":22,
                          "height":29}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"70418f89314a499eb5c8063c6eaed12a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"left",
            "location":{
              "x":108,
              "y":63},
            "size":{
              "width":108,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"81357a21f34343079e973ad6ba5734f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"left",
                "location":{
                  "x":108,
                  "y":63},
                "size":{
                  "width":108,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/委托兑奖/u13.png"}},
{
          "id":"54054d4d27734b7982664b1ff7003f4a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":212,
              "y":63},
            "size":{
              "width":108,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21664e88af1b46b2a702935cd2c4780a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":212,
                  "y":63},
                "size":{
                  "width":108,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/委托兑奖/u13.png"}},
{
          "id":"5fa12cfce8b145e783e8d5466eff58ea",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":0,
              "y":109},
            "size":{
              "width":320,
              "height":181}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cfb9b7793a3447edaa9be87fa67aae9a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":0,
                  "y":109},
                "size":{
                  "width":320,
                  "height":181}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/委托兑奖/u17.png"}},
{
          "id":"4d2bce5a0b4a4b319233e5d36c153b37",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":10,
              "y":125},
            "size":{
              "width":226,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7dbb8ee8545c404cb7ba009718e22ad7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":10,
                  "y":125},
                "size":{
                  "width":226,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fe068f137d5d45cea3cc9b22a69f8a45",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":67,
              "y":128},
            "size":{
              "width":186,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73c3dc26692b4d03bffaf34f7dbe0856",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":67,
                  "y":128},
                "size":{
                  "width":186,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"be31b7dddcef426baef21943d17425b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "location":{
              "x":179,
              "y":69.5},
            "size":{
              "width":23,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96f206d203e1437e98be7167a317a4ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "location":{
                  "x":179,
                  "y":69.5},
                "size":{
                  "width":23,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/打票任务/u127.png"}},
{
          "id":"53782f2d63f542b0a27320bc4b36e42a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":150},
            "size":{
              "width":320,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/合买详情/u49_line.png"}},
{
          "id":"11a0ab2a82594b2586ecb84da0c910a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"left",
            "location":{
              "x":0,
              "y":63},
            "size":{
              "width":108,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"39d607473ea1427abe73dbfbb79cfdf0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"left",
                "location":{
                  "x":0,
                  "y":63},
                "size":{
                  "width":108,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/委托兑奖/u13.png"}},
{
          "id":"574493c35ddf456fab7dffd7fec18e57",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":10,
              "y":170},
            "size":{
              "width":226,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3aed8259026f4a94aa6d0c14effe8c5e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":10,
                  "y":170},
                "size":{
                  "width":226,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cf31d615b17d481fb152673ef2f0774f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":10,
              "y":213},
            "size":{
              "width":226,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"673dfa98a12b46c4af03caa78951c2cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":10,
                  "y":213},
                "size":{
                  "width":226,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e78800f200d54b0d8ea4615c497296ea",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":10,
              "y":253},
            "size":{
              "width":226,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec3657d330d24aeea493e4408d4deb61",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":10,
                  "y":253},
                "size":{
                  "width":226,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6ec1538e83f843b58c1043064a806426",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":226,
              "y":120},
            "size":{
              "width":80,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46548031d87744b4b7502436dd4bd6fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":226,
                  "y":120},
                "size":{
                  "width":80,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单中心/u26.png"}},
{
          "id":"96dcbbd1634b4bb69b4c667226a1e7a6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":0,
              "y":300},
            "size":{
              "width":320,
              "height":181}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f3e09eaecdb845029caa80d6a0ad80c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":0,
                  "y":300},
                "size":{
                  "width":320,
                  "height":181}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/委托兑奖/u17.png"}},
{
          "id":"6c29d3b2f5764984a44d781554cd374f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":10,
              "y":316},
            "size":{
              "width":226,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5dbf62b7c64e45abb928378366f69510",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":10,
                  "y":316},
                "size":{
                  "width":226,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"85b52890cde9447f94ce229d781e8f05",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":67,
              "y":319},
            "size":{
              "width":186,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29200691ff70452786ec384a4940bdad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":67,
                  "y":319},
                "size":{
                  "width":186,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b13c274ae07d4152b1b0d27565448c24",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":341},
            "size":{
              "width":320,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/合买详情/u49_line.png"}},
{
          "id":"c233a57008b94d338f54fc90ab9ce58c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":10,
              "y":361},
            "size":{
              "width":226,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"763564e9c25542b9b92dfb27ac04e2bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":10,
                  "y":361},
                "size":{
                  "width":226,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"68e6dbe449e040bab565ee52d09399c7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":10,
              "y":404},
            "size":{
              "width":226,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4346ec0004314e17b715cee7a14b310e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":10,
                  "y":404},
                "size":{
                  "width":226,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"284db4c8570f45d683ae84d51b878575",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":10,
              "y":444},
            "size":{
              "width":226,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c7d212a366a4f9f83077bac155103fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":10,
                  "y":444},
                "size":{
                  "width":226,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6c3970f7d9b5417da94f973f7ad15dbc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":226,
              "y":311},
            "size":{
              "width":80,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b2caec491a445d3a9d842c05a7462ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":226,
                  "y":311},
                "size":{
                  "width":80,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单中心/u26.png"}},
{
          "id":"4188d45ff35e47d6b05a856f328f460c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":0,
              "y":491},
            "size":{
              "width":320,
              "height":181}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e43e3b1959f6477583f3cb14359b1b84",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":0,
                  "y":491},
                "size":{
                  "width":320,
                  "height":181}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/委托兑奖/u17.png"}},
{
          "id":"08f30ad455c041d3bcb2a53bc578715c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":10,
              "y":507},
            "size":{
              "width":226,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"392e11ba37584a50a662ad7374487a2d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":10,
                  "y":507},
                "size":{
                  "width":226,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7f4f25e022064e60928d12cb77f4d229",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":67,
              "y":510},
            "size":{
              "width":186,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e18c13f17a804ad6a5be2132b1fefc5f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":67,
                  "y":510},
                "size":{
                  "width":186,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9f7281a7c3f24a6c91611829f67b38d7",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":532},
            "size":{
              "width":320,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/合买详情/u49_line.png"}},
{
          "id":"afc04a3b2ad6410e9b9fb22f47c818bf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":10,
              "y":552},
            "size":{
              "width":226,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a65f734e9ae146cfbedc09bb0deaa50e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":10,
                  "y":552},
                "size":{
                  "width":226,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5bde6db1d8c24b60bf787be148047480",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":10,
              "y":595},
            "size":{
              "width":226,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0cbbddf469e74a5cb7b3ae0558aaf5f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":10,
                  "y":595},
                "size":{
                  "width":226,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"63867d07283c4396ad66333420fb8bf3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":10,
              "y":635},
            "size":{
              "width":226,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a7146c3640f3477d9ca1acf7f053f981",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":10,
                  "y":635},
                "size":{
                  "width":226,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"85389724e03441a9b5e9458a8e739451",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":226,
              "y":502},
            "size":{
              "width":80,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0adf8e0eeaee4f83bfa56de6038c8d46",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":226,
                  "y":502},
                "size":{
                  "width":80,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单中心/u26.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "196151baf21d42819ed2246024b07470":{
      "scriptId":"u0"},
    "8d5c61e63f084849ae8018eb559b5f00":{
      "scriptId":"u1"},
    "f6461b04085a426b9b16f5fa19a8800a":{
      "scriptId":"u2"},
    "1c14c94148244c44b595715e32350b94":{
      "scriptId":"u3"},
    "45baeb451863478da554ee76771b2039":{
      "scriptId":"u4"},
    "5e90fb423c2a4b05ac74edd900b07c39":{
      "scriptId":"u5"},
    "57ef88ee5043405f8f97e73af66cef26":{
      "scriptId":"u6"},
    "d8c0034cd8ce40e9b56e0124641aea52":{
      "scriptId":"u7"},
    "ccfccefa554b4694bd195703dac485ad":{
      "scriptId":"u8"},
    "c806c6c75f7a4048abcd51fc4f23fbc3":{
      "scriptId":"u9"},
    "1ff463645687494598c2a7ac9b6d6e2b":{
      "scriptId":"u10"},
    "f80aa5e8cdff4474902fcfc82e895d27":{
      "scriptId":"u11"},
    "ac687abdb44540b8b69653d1333fe973":{
      "scriptId":"u12"},
    "70418f89314a499eb5c8063c6eaed12a":{
      "scriptId":"u13"},
    "81357a21f34343079e973ad6ba5734f8":{
      "scriptId":"u14"},
    "54054d4d27734b7982664b1ff7003f4a":{
      "scriptId":"u15"},
    "21664e88af1b46b2a702935cd2c4780a":{
      "scriptId":"u16"},
    "5fa12cfce8b145e783e8d5466eff58ea":{
      "scriptId":"u17"},
    "cfb9b7793a3447edaa9be87fa67aae9a":{
      "scriptId":"u18"},
    "4d2bce5a0b4a4b319233e5d36c153b37":{
      "scriptId":"u19"},
    "7dbb8ee8545c404cb7ba009718e22ad7":{
      "scriptId":"u20"},
    "fe068f137d5d45cea3cc9b22a69f8a45":{
      "scriptId":"u21"},
    "73c3dc26692b4d03bffaf34f7dbe0856":{
      "scriptId":"u22"},
    "be31b7dddcef426baef21943d17425b3":{
      "scriptId":"u23"},
    "96f206d203e1437e98be7167a317a4ce":{
      "scriptId":"u24"},
    "53782f2d63f542b0a27320bc4b36e42a":{
      "scriptId":"u25"},
    "11a0ab2a82594b2586ecb84da0c910a5":{
      "scriptId":"u26"},
    "39d607473ea1427abe73dbfbb79cfdf0":{
      "scriptId":"u27"},
    "574493c35ddf456fab7dffd7fec18e57":{
      "scriptId":"u28"},
    "3aed8259026f4a94aa6d0c14effe8c5e":{
      "scriptId":"u29"},
    "cf31d615b17d481fb152673ef2f0774f":{
      "scriptId":"u30"},
    "673dfa98a12b46c4af03caa78951c2cb":{
      "scriptId":"u31"},
    "e78800f200d54b0d8ea4615c497296ea":{
      "scriptId":"u32"},
    "ec3657d330d24aeea493e4408d4deb61":{
      "scriptId":"u33"},
    "6ec1538e83f843b58c1043064a806426":{
      "scriptId":"u34"},
    "46548031d87744b4b7502436dd4bd6fd":{
      "scriptId":"u35"},
    "96dcbbd1634b4bb69b4c667226a1e7a6":{
      "scriptId":"u36"},
    "f3e09eaecdb845029caa80d6a0ad80c1":{
      "scriptId":"u37"},
    "6c29d3b2f5764984a44d781554cd374f":{
      "scriptId":"u38"},
    "5dbf62b7c64e45abb928378366f69510":{
      "scriptId":"u39"},
    "85b52890cde9447f94ce229d781e8f05":{
      "scriptId":"u40"},
    "29200691ff70452786ec384a4940bdad":{
      "scriptId":"u41"},
    "b13c274ae07d4152b1b0d27565448c24":{
      "scriptId":"u42"},
    "c233a57008b94d338f54fc90ab9ce58c":{
      "scriptId":"u43"},
    "763564e9c25542b9b92dfb27ac04e2bb":{
      "scriptId":"u44"},
    "68e6dbe449e040bab565ee52d09399c7":{
      "scriptId":"u45"},
    "4346ec0004314e17b715cee7a14b310e":{
      "scriptId":"u46"},
    "284db4c8570f45d683ae84d51b878575":{
      "scriptId":"u47"},
    "9c7d212a366a4f9f83077bac155103fa":{
      "scriptId":"u48"},
    "6c3970f7d9b5417da94f973f7ad15dbc":{
      "scriptId":"u49"},
    "4b2caec491a445d3a9d842c05a7462ac":{
      "scriptId":"u50"},
    "4188d45ff35e47d6b05a856f328f460c":{
      "scriptId":"u51"},
    "e43e3b1959f6477583f3cb14359b1b84":{
      "scriptId":"u52"},
    "08f30ad455c041d3bcb2a53bc578715c":{
      "scriptId":"u53"},
    "392e11ba37584a50a662ad7374487a2d":{
      "scriptId":"u54"},
    "7f4f25e022064e60928d12cb77f4d229":{
      "scriptId":"u55"},
    "e18c13f17a804ad6a5be2132b1fefc5f":{
      "scriptId":"u56"},
    "9f7281a7c3f24a6c91611829f67b38d7":{
      "scriptId":"u57"},
    "afc04a3b2ad6410e9b9fb22f47c818bf":{
      "scriptId":"u58"},
    "a65f734e9ae146cfbedc09bb0deaa50e":{
      "scriptId":"u59"},
    "5bde6db1d8c24b60bf787be148047480":{
      "scriptId":"u60"},
    "0cbbddf469e74a5cb7b3ae0558aaf5f0":{
      "scriptId":"u61"},
    "63867d07283c4396ad66333420fb8bf3":{
      "scriptId":"u62"},
    "a7146c3640f3477d9ca1acf7f053f981":{
      "scriptId":"u63"},
    "85389724e03441a9b5e9458a8e739451":{
      "scriptId":"u64"},
    "0adf8e0eeaee4f83bfa56de6038c8d46":{
      "scriptId":"u65"}}});