$axure.loadCurrentPage({
  "url":"店主公告.html",
  "generationDate":new Date(1496903836688.76),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"sfz",
"sfz_n"],
  "page":{
    "packageId":"06bf6030411846708ce3e75da5b18688",
    "type":"Axure:Page",
    "name":"店主公告",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a7d03c4d4b754565b05f94c56cc8cf1b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "size":{
              "width":320,
              "height":500},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2fc1ec97264d43cba6060b61ced8ce5b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "size":{
                  "width":320,
                  "height":500},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/钱包/u0.png"}},
{
          "id":"6535e6038ff74b7e940b1823293a7891",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "fixedHorizontal":"left",
          "fixedMarginHorizontal":0,
          "fixedVertical":"top",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"5d228e67cf6544feb33aa951fb7f32b1",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"02860697225443e0b84ae8a28762b1fc",
                  "label":"",
                  "parentDynamicPanel":"6535e6038ff74b7e940b1823293a7891",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF1C222E},
                    "size":{
                      "width":320,
                      "height":64},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8954e59e891f42d0bf0ef3523efd923c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6535e6038ff74b7e940b1823293a7891",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF1C222E},
                        "size":{
                          "width":320,
                          "height":64},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u3.png"}},
{
                  "id":"5f2e1965301547d3987aa326c4f14f41",
                  "label":"",
                  "parentDynamicPanel":"6535e6038ff74b7e940b1823293a7891",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Heiti SC Regular', 'Heiti SC'",
                    "fontSize":"18px",
                    "fontWeight":"200",
                    "horizontalAlignment":"center",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":78,
                      "y":35},
                    "size":{
                      "width":163,
                      "height":22},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"24e6fe76a5be4f3eb6a00dea1b52f57f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6535e6038ff74b7e940b1823293a7891",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Heiti SC Regular', 'Heiti SC'",
                        "fontSize":"18px",
                        "fontWeight":"200",
                        "horizontalAlignment":"center",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":78,
                          "y":35},
                        "size":{
                          "width":163,
                          "height":22},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"d5897866625d43198d858ccbcd26bb7f",
                  "label":"",
                  "parentDynamicPanel":"6535e6038ff74b7e940b1823293a7891",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":320,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"89eea40f3c584c10a1a0b6d195e94f48",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6535e6038ff74b7e940b1823293a7891",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":320,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u7.png"}},
{
                  "id":"1448f84fe07d4c818e9574e2d0d5ae1c",
                  "label":"",
                  "parentDynamicPanel":"6535e6038ff74b7e940b1823293a7891",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Heiti SC Regular', 'Heiti SC'",
                    "fontSize":"16px",
                    "fontWeight":"200",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":27,
                      "y":36},
                    "size":{
                      "width":63,
                      "height":19},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1c9e9fbdd73b4e92adacdbdf35ca0573",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6535e6038ff74b7e940b1823293a7891",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Heiti SC Regular', 'Heiti SC'",
                        "fontSize":"16px",
                        "fontWeight":"200",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":27,
                          "y":36},
                        "size":{
                          "width":63,
                          "height":19},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f23243d964ba48ffa4e6ba5fcb8fa2e4",
                  "label":"",
                  "parentDynamicPanel":"6535e6038ff74b7e940b1823293a7891",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Lucida Grande Regular', 'Lucida Grande'",
                    "fontSize":"20px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":9,
                      "y":31},
                    "size":{
                      "width":22,
                      "height":29}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8d884e5709864b1db3a5c5c8e35d483b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6535e6038ff74b7e940b1823293a7891",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Lucida Grande Regular', 'Lucida Grande'",
                        "fontSize":"20px",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":9,
                          "y":31},
                        "size":{
                          "width":22,
                          "height":29}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"9faa91bfcbe849a3ab4ead88a600b6fb",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "stateStyles":{
              "hint":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1}}},
            "location":{
              "x":20,
              "y":80},
            "size":{
              "width":280,
              "height":130}},
          "adaptiveStyles":{
},
          "placeholderText":"在这里编辑你想说的公告"},
{
          "id":"c180ab9887cb4ab09d367d57d44627cf",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":20,
              "y":275},
            "size":{
              "width":270,
              "height":45}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "a7d03c4d4b754565b05f94c56cc8cf1b":{
      "scriptId":"u0"},
    "2fc1ec97264d43cba6060b61ced8ce5b":{
      "scriptId":"u1"},
    "6535e6038ff74b7e940b1823293a7891":{
      "scriptId":"u2"},
    "02860697225443e0b84ae8a28762b1fc":{
      "scriptId":"u3"},
    "8954e59e891f42d0bf0ef3523efd923c":{
      "scriptId":"u4"},
    "5f2e1965301547d3987aa326c4f14f41":{
      "scriptId":"u5"},
    "24e6fe76a5be4f3eb6a00dea1b52f57f":{
      "scriptId":"u6"},
    "d5897866625d43198d858ccbcd26bb7f":{
      "scriptId":"u7"},
    "89eea40f3c584c10a1a0b6d195e94f48":{
      "scriptId":"u8"},
    "1448f84fe07d4c818e9574e2d0d5ae1c":{
      "scriptId":"u9"},
    "1c9e9fbdd73b4e92adacdbdf35ca0573":{
      "scriptId":"u10"},
    "f23243d964ba48ffa4e6ba5fcb8fa2e4":{
      "scriptId":"u11"},
    "8d884e5709864b1db3a5c5c8e35d483b":{
      "scriptId":"u12"},
    "9faa91bfcbe849a3ab4ead88a600b6fb":{
      "scriptId":"u13"},
    "c180ab9887cb4ab09d367d57d44627cf":{
      "scriptId":"u14"}}});