$axure.loadCurrentPage({
  "url":"我的.html",
  "generationDate":new Date(1496903830177.76),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"sfz",
"sfz_n"],
  "page":{
    "packageId":"64ed0d37bdc145eb97af93eebf571744",
    "type":"Axure:Page",
    "name":"我的",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c7753e4381a9437ab8dd08d4f8fc36e4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "size":{
              "width":320,
              "height":590},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f9ddf6154c5492db85f4b5c5c9e83f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "size":{
                  "width":320,
                  "height":590},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的/u0.png"}},
{
          "id":"e5c22c8c84b44e7ab86b7173f6bd7a21",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "fixedHorizontal":"left",
          "fixedMarginHorizontal":0,
          "fixedVertical":"top",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"cd1fe8fd68064e06b8bbc6dedbe9d802",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"7b5521fff54b4d7889e3a243af163f20",
                  "label":"",
                  "parentDynamicPanel":"e5c22c8c84b44e7ab86b7173f6bd7a21",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF1C222E},
                    "size":{
                      "width":320,
                      "height":64},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a595ee0787a24f749f0621ac8625034d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e5c22c8c84b44e7ab86b7173f6bd7a21",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF1C222E},
                        "size":{
                          "width":320,
                          "height":64},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u3.png"}},
{
                  "id":"9643a1ac88514ea0983ae4805102dc1f",
                  "label":"",
                  "parentDynamicPanel":"e5c22c8c84b44e7ab86b7173f6bd7a21",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Heiti SC Regular', 'Heiti SC'",
                    "fontSize":"18px",
                    "fontWeight":"200",
                    "horizontalAlignment":"center",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":78,
                      "y":35},
                    "size":{
                      "width":163,
                      "height":22},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4a7db3a23f3549aaa3b995bc7396dd75",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e5c22c8c84b44e7ab86b7173f6bd7a21",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Heiti SC Regular', 'Heiti SC'",
                        "fontSize":"18px",
                        "fontWeight":"200",
                        "horizontalAlignment":"center",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":78,
                          "y":35},
                        "size":{
                          "width":163,
                          "height":22},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"89cffce467ae4e408b95fdaad85ecb9e",
                  "label":"",
                  "parentDynamicPanel":"e5c22c8c84b44e7ab86b7173f6bd7a21",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":320,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c723e8ec84f04f7a9146dc7135701991",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e5c22c8c84b44e7ab86b7173f6bd7a21",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":320,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u7.png"}},
{
                  "id":"0e745ba3b5d446c7b9e72cfa16e17148",
                  "label":"",
                  "parentDynamicPanel":"e5c22c8c84b44e7ab86b7173f6bd7a21",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Heiti SC Regular', 'Heiti SC'",
                    "fontSize":"16px",
                    "fontWeight":"200",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":27,
                      "y":36},
                    "size":{
                      "width":63,
                      "height":19},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f1746f4abd854a8d947453a94ea40ea7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e5c22c8c84b44e7ab86b7173f6bd7a21",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Heiti SC Regular', 'Heiti SC'",
                        "fontSize":"16px",
                        "fontWeight":"200",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":27,
                          "y":36},
                        "size":{
                          "width":63,
                          "height":19},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"bd3aca2c885140b9b23f1ebd4c21017d",
                  "label":"",
                  "parentDynamicPanel":"e5c22c8c84b44e7ab86b7173f6bd7a21",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Lucida Grande Regular', 'Lucida Grande'",
                    "fontSize":"20px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":9,
                      "y":31},
                    "size":{
                      "width":22,
                      "height":29}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6d38d4b220cf4fceb00eb0f29a4e386f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e5c22c8c84b44e7ab86b7173f6bd7a21",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Lucida Grande Regular', 'Lucida Grande'",
                        "fontSize":"20px",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":9,
                          "y":31},
                        "size":{
                          "width":22,
                          "height":29}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"cb1fe98fd6114c7eae4152c44faa78ea",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":0,
              "y":540},
            "size":{
              "width":81,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e46397a98d5f409ebd1b5e39cf67b754",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":0,
                  "y":540},
                "size":{
                  "width":81,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u13.png"}},
{
          "id":"50e1ce4912f149a88b59c5de2d970d19",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":80,
              "y":540},
            "size":{
              "width":81,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2235dcf2b6da49858c3c14c4a65037c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":80,
                  "y":540},
                "size":{
                  "width":81,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u13.png"}},
{
          "id":"d26f04bef28d4897957d7a12d659a7e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":160,
              "y":540},
            "size":{
              "width":81,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"579c392ded1f4fe3a3dc40b65d6f86f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":160,
                  "y":540},
                "size":{
                  "width":81,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u13.png"}},
{
          "id":"e13def76b871499f9620785835b82eee",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009DD9,
              "opacity":1},
            "location":{
              "x":240,
              "y":540},
            "size":{
              "width":80,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f0fb70a80724e828753e95c0e203868",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009DD9,
                  "opacity":1},
                "location":{
                  "x":240,
                  "y":540},
                "size":{
                  "width":80,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u19.png"}},
{
          "id":"d235121a4b65479d9ee76ad463028707",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":0,
              "y":63},
            "size":{
              "width":320,
              "height":96}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f816e5f4cb294c01a9083d20a8e4b9c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":0,
                  "y":63},
                "size":{
                  "width":320,
                  "height":96}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的/u21.png"}},
{
          "id":"1f664057a57348c2b7eedbf117e7dc5a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":10,
              "y":74},
            "size":{
              "width":71,
              "height":66}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4cd45e0e7bbd4e61a57988187592801f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":10,
                  "y":74},
                "size":{
                  "width":71,
                  "height":66}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的/u23.png"}},
{
          "id":"3194d38ac349425ab0fab7b964b0465f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":91,
              "y":74},
            "size":{
              "width":99,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"85b72fc2cd9c46f0b5acceda034292f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":91,
                  "y":74},
                "size":{
                  "width":99,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a5dedb72fce94e0e989d9ae76542f358",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":94,
              "y":124},
            "size":{
              "width":166,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"821f9fd71d514454adfe1af991db6f13",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":94,
                  "y":124},
                "size":{
                  "width":166,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e5d7c024013b463cae7ca399c000341c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":170.5,
              "y":71},
            "size":{
              "width":60,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc02694cba544903bb0d7d0451feced0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":170.5,
                  "y":71},
                "size":{
                  "width":60,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的/u29.png"}},
{
          "id":"5718fd2619a34e8f921bc01576e015e4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "location":{
              "x":0,
              "y":169},
            "size":{
              "width":320,
              "height":51}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a1f3ca578cd4ccba896447ae51732e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "location":{
                  "x":0,
                  "y":169},
                "size":{
                  "width":320,
                  "height":51}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/确认订单-双色球/u25.png"}},
{
          "id":"e5606d231440438a822be4f8ddf5da68",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "location":{
              "x":0,
              "y":232},
            "size":{
              "width":320,
              "height":51}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a434f7201c5492991b7e65496cceda7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "location":{
                  "x":0,
                  "y":232},
                "size":{
                  "width":320,
                  "height":51}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/确认订单-双色球/u25.png"}},
{
          "id":"486ce02cf56e4ca18bb74389fae27b81",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "location":{
              "x":0,
              "y":360},
            "size":{
              "width":320,
              "height":51}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a9befb466c3a4d9f8b9980db4b77ec7c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "location":{
                  "x":0,
                  "y":360},
                "size":{
                  "width":320,
                  "height":51}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/确认订单-双色球/u25.png"}},
{
          "id":"e1771d58ac434d979f54d171e9867105",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "location":{
              "x":0,
              "y":421},
            "size":{
              "width":320,
              "height":51}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8bcc33aa0fc34a52bcd18f8588f65f01",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "location":{
                  "x":0,
                  "y":421},
                "size":{
                  "width":320,
                  "height":51}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/确认订单-双色球/u25.png"}},
{
          "id":"2e0006403aa24d1292679e5284bccf97",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "location":{
              "x":0,
              "y":299},
            "size":{
              "width":320,
              "height":51}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"57e927942cc94523af58b8491354bbab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "location":{
                  "x":0,
                  "y":299},
                "size":{
                  "width":320,
                  "height":51}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/确认订单-双色球/u25.png"}},
{
          "id":"f758db84f0f94bc09562a460ef98677c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":179.5},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"476f1cfe558c4191a39074c4e706fa12",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":179.5},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u262.png"}},
{
          "id":"c828e6ab0aa2431d987cce14a083e4aa",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":242},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"444ac419a7984ffaac5b50601c632517",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":242},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u262.png"}},
{
          "id":"81117d12d791459091e8d8d7f0096c56",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":310},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24d95d5b86b14e069d3fa7441e561bb8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":310},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u262.png"}},
{
          "id":"662d41a9f26e4d0682e04c418de907e2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":370},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c91b33d5e2e148189729f071a1b2b198",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":370},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u262.png"}},
{
          "id":"f3c289b8a0e94d209d0019edeb53a9e0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":432},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee5ccc942bcb447da3109acca44dec91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":432},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u262.png"}},
{
          "id":"ff8760eb15e442d8bc737c49c8a36015",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":230,
              "y":186},
            "size":{
              "width":48,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"86bb3b03d8e841099ac92ed1807f33d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":230,
                  "y":186},
                "size":{
                  "width":48,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "c7753e4381a9437ab8dd08d4f8fc36e4":{
      "scriptId":"u0"},
    "1f9ddf6154c5492db85f4b5c5c9e83f5":{
      "scriptId":"u1"},
    "e5c22c8c84b44e7ab86b7173f6bd7a21":{
      "scriptId":"u2"},
    "7b5521fff54b4d7889e3a243af163f20":{
      "scriptId":"u3"},
    "a595ee0787a24f749f0621ac8625034d":{
      "scriptId":"u4"},
    "9643a1ac88514ea0983ae4805102dc1f":{
      "scriptId":"u5"},
    "4a7db3a23f3549aaa3b995bc7396dd75":{
      "scriptId":"u6"},
    "89cffce467ae4e408b95fdaad85ecb9e":{
      "scriptId":"u7"},
    "c723e8ec84f04f7a9146dc7135701991":{
      "scriptId":"u8"},
    "0e745ba3b5d446c7b9e72cfa16e17148":{
      "scriptId":"u9"},
    "f1746f4abd854a8d947453a94ea40ea7":{
      "scriptId":"u10"},
    "bd3aca2c885140b9b23f1ebd4c21017d":{
      "scriptId":"u11"},
    "6d38d4b220cf4fceb00eb0f29a4e386f":{
      "scriptId":"u12"},
    "cb1fe98fd6114c7eae4152c44faa78ea":{
      "scriptId":"u13"},
    "e46397a98d5f409ebd1b5e39cf67b754":{
      "scriptId":"u14"},
    "50e1ce4912f149a88b59c5de2d970d19":{
      "scriptId":"u15"},
    "2235dcf2b6da49858c3c14c4a65037c3":{
      "scriptId":"u16"},
    "d26f04bef28d4897957d7a12d659a7e9":{
      "scriptId":"u17"},
    "579c392ded1f4fe3a3dc40b65d6f86f9":{
      "scriptId":"u18"},
    "e13def76b871499f9620785835b82eee":{
      "scriptId":"u19"},
    "0f0fb70a80724e828753e95c0e203868":{
      "scriptId":"u20"},
    "d235121a4b65479d9ee76ad463028707":{
      "scriptId":"u21"},
    "f816e5f4cb294c01a9083d20a8e4b9c3":{
      "scriptId":"u22"},
    "1f664057a57348c2b7eedbf117e7dc5a":{
      "scriptId":"u23"},
    "4cd45e0e7bbd4e61a57988187592801f":{
      "scriptId":"u24"},
    "3194d38ac349425ab0fab7b964b0465f":{
      "scriptId":"u25"},
    "85b72fc2cd9c46f0b5acceda034292f2":{
      "scriptId":"u26"},
    "a5dedb72fce94e0e989d9ae76542f358":{
      "scriptId":"u27"},
    "821f9fd71d514454adfe1af991db6f13":{
      "scriptId":"u28"},
    "e5d7c024013b463cae7ca399c000341c":{
      "scriptId":"u29"},
    "dc02694cba544903bb0d7d0451feced0":{
      "scriptId":"u30"},
    "5718fd2619a34e8f921bc01576e015e4":{
      "scriptId":"u31"},
    "7a1f3ca578cd4ccba896447ae51732e7":{
      "scriptId":"u32"},
    "e5606d231440438a822be4f8ddf5da68":{
      "scriptId":"u33"},
    "2a434f7201c5492991b7e65496cceda7":{
      "scriptId":"u34"},
    "486ce02cf56e4ca18bb74389fae27b81":{
      "scriptId":"u35"},
    "a9befb466c3a4d9f8b9980db4b77ec7c":{
      "scriptId":"u36"},
    "e1771d58ac434d979f54d171e9867105":{
      "scriptId":"u37"},
    "8bcc33aa0fc34a52bcd18f8588f65f01":{
      "scriptId":"u38"},
    "2e0006403aa24d1292679e5284bccf97":{
      "scriptId":"u39"},
    "57e927942cc94523af58b8491354bbab":{
      "scriptId":"u40"},
    "f758db84f0f94bc09562a460ef98677c":{
      "scriptId":"u41"},
    "476f1cfe558c4191a39074c4e706fa12":{
      "scriptId":"u42"},
    "c828e6ab0aa2431d987cce14a083e4aa":{
      "scriptId":"u43"},
    "444ac419a7984ffaac5b50601c632517":{
      "scriptId":"u44"},
    "81117d12d791459091e8d8d7f0096c56":{
      "scriptId":"u45"},
    "24d95d5b86b14e069d3fa7441e561bb8":{
      "scriptId":"u46"},
    "662d41a9f26e4d0682e04c418de907e2":{
      "scriptId":"u47"},
    "c91b33d5e2e148189729f071a1b2b198":{
      "scriptId":"u48"},
    "f3c289b8a0e94d209d0019edeb53a9e0":{
      "scriptId":"u49"},
    "ee5ccc942bcb447da3109acca44dec91":{
      "scriptId":"u50"},
    "ff8760eb15e442d8bc737c49c8a36015":{
      "scriptId":"u51"},
    "86bb3b03d8e841099ac92ed1807f33d5":{
      "scriptId":"u52"}}});