$axure.loadCurrentPage({
  "url":"合买方案.html",
  "generationDate":new Date(1496903829433.76),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"sfz",
"sfz_n"],
  "page":{
    "packageId":"8becaa2d196044f584cc1db5bb14b87c",
    "type":"Axure:Page",
    "name":"合买方案",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"cde78bc0b8ad4cfab0e06ea65bb17ffa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "size":{
              "width":320,
              "height":470},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7bd5164cdbcb4c3f8c55d77448683806",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "size":{
                  "width":320,
                  "height":470},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付订单/u0.png"}},
{
          "id":"a19730c7c6cf4cbc97ef3f7d104a6383",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "fixedHorizontal":"left",
          "fixedMarginHorizontal":0,
          "fixedVertical":"top",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"4ef2f8a06a0649e2a5b05541d4ad97f2",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"e0ba9ee07ed54d2abd7760321ee8db62",
                  "label":"",
                  "parentDynamicPanel":"a19730c7c6cf4cbc97ef3f7d104a6383",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF1C222E},
                    "size":{
                      "width":320,
                      "height":64},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8943680e2acf42fdb967e23967726f94",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a19730c7c6cf4cbc97ef3f7d104a6383",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF1C222E},
                        "size":{
                          "width":320,
                          "height":64},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u3.png"}},
{
                  "id":"973c9acca72f4cc58fd00210d583d9ef",
                  "label":"",
                  "parentDynamicPanel":"a19730c7c6cf4cbc97ef3f7d104a6383",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Heiti SC Regular', 'Heiti SC'",
                    "fontSize":"18px",
                    "fontWeight":"200",
                    "horizontalAlignment":"center",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":78,
                      "y":35},
                    "size":{
                      "width":163,
                      "height":22},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e0de7705aa5744f4a1d0daa86aaa593b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a19730c7c6cf4cbc97ef3f7d104a6383",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Heiti SC Regular', 'Heiti SC'",
                        "fontSize":"18px",
                        "fontWeight":"200",
                        "horizontalAlignment":"center",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":78,
                          "y":35},
                        "size":{
                          "width":163,
                          "height":22},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"7f42607d7310442f8f8e12ba692af442",
                  "label":"",
                  "parentDynamicPanel":"a19730c7c6cf4cbc97ef3f7d104a6383",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":320,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7a98f48ac1cf4c06994a4e4f0e04db65",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a19730c7c6cf4cbc97ef3f7d104a6383",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":320,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u7.png"}},
{
                  "id":"1a68fd17cfe047128b911ed34192cdca",
                  "label":"",
                  "parentDynamicPanel":"a19730c7c6cf4cbc97ef3f7d104a6383",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Heiti SC Regular', 'Heiti SC'",
                    "fontSize":"16px",
                    "fontWeight":"200",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":27,
                      "y":36},
                    "size":{
                      "width":63,
                      "height":19},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9eed0576f1504e9496c5c53b1324bea4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a19730c7c6cf4cbc97ef3f7d104a6383",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Heiti SC Regular', 'Heiti SC'",
                        "fontSize":"16px",
                        "fontWeight":"200",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":27,
                          "y":36},
                        "size":{
                          "width":63,
                          "height":19},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f86880d8bd4b448aad32c77d56721463",
                  "label":"",
                  "parentDynamicPanel":"a19730c7c6cf4cbc97ef3f7d104a6383",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Lucida Grande Regular', 'Lucida Grande'",
                    "fontSize":"20px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":9,
                      "y":31},
                    "size":{
                      "width":22,
                      "height":29}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"029f106b10b044788f850b93019ddb0b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a19730c7c6cf4cbc97ef3f7d104a6383",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Lucida Grande Regular', 'Lucida Grande'",
                        "fontSize":"20px",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":9,
                          "y":31},
                        "size":{
                          "width":22,
                          "height":29}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"9020b9aa1a9e4b27bdac8fd2cbf2c1ac",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":0,
              "y":62},
            "size":{
              "width":320,
              "height":138}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b70291188eb44400b5d67419a18390fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":0,
                  "y":62},
                "size":{
                  "width":320,
                  "height":138}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/合买方案/u13.png"}},
{
          "id":"77da7340094040ee9b42fe9ca4eb9cff",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":17,
              "y":80},
            "size":{
              "width":286,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a0d221739ed64789a439d4a820056f40",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":17,
                  "y":80},
                "size":{
                  "width":286,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"adc5956a690d43e0b8174ffc0d87c2e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":17,
              "y":121},
            "size":{
              "width":266,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8acb1503f0d244ac9c468cc19ca2749e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":17,
                  "y":121},
                "size":{
                  "width":266,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c1d69de4939b461cb4a091522ed7ec2a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":17,
              "y":159},
            "size":{
              "width":266,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd0b2c1d59644effb7f084d8fe077401",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":17,
                  "y":159},
                "size":{
                  "width":266,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b755273a6d7445aba40b86da41d2246c",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":28,
              "y":255},
            "size":{
              "width":82,
              "height":35}},
          "adaptiveStyles":{
}},
{
          "id":"714f7dce2a4b47e991c0476ffa840401",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":201,
              "y":255},
            "size":{
              "width":82,
              "height":35}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "cde78bc0b8ad4cfab0e06ea65bb17ffa":{
      "scriptId":"u0"},
    "7bd5164cdbcb4c3f8c55d77448683806":{
      "scriptId":"u1"},
    "a19730c7c6cf4cbc97ef3f7d104a6383":{
      "scriptId":"u2"},
    "e0ba9ee07ed54d2abd7760321ee8db62":{
      "scriptId":"u3"},
    "8943680e2acf42fdb967e23967726f94":{
      "scriptId":"u4"},
    "973c9acca72f4cc58fd00210d583d9ef":{
      "scriptId":"u5"},
    "e0de7705aa5744f4a1d0daa86aaa593b":{
      "scriptId":"u6"},
    "7f42607d7310442f8f8e12ba692af442":{
      "scriptId":"u7"},
    "7a98f48ac1cf4c06994a4e4f0e04db65":{
      "scriptId":"u8"},
    "1a68fd17cfe047128b911ed34192cdca":{
      "scriptId":"u9"},
    "9eed0576f1504e9496c5c53b1324bea4":{
      "scriptId":"u10"},
    "f86880d8bd4b448aad32c77d56721463":{
      "scriptId":"u11"},
    "029f106b10b044788f850b93019ddb0b":{
      "scriptId":"u12"},
    "9020b9aa1a9e4b27bdac8fd2cbf2c1ac":{
      "scriptId":"u13"},
    "b70291188eb44400b5d67419a18390fd":{
      "scriptId":"u14"},
    "77da7340094040ee9b42fe9ca4eb9cff":{
      "scriptId":"u15"},
    "a0d221739ed64789a439d4a820056f40":{
      "scriptId":"u16"},
    "adc5956a690d43e0b8174ffc0d87c2e9":{
      "scriptId":"u17"},
    "8acb1503f0d244ac9c468cc19ca2749e":{
      "scriptId":"u18"},
    "c1d69de4939b461cb4a091522ed7ec2a":{
      "scriptId":"u19"},
    "cd0b2c1d59644effb7f084d8fe077401":{
      "scriptId":"u20"},
    "b755273a6d7445aba40b86da41d2246c":{
      "scriptId":"u21"},
    "714f7dce2a4b47e991c0476ffa840401":{
      "scriptId":"u22"}}});