$axure.loadCurrentPage({
  "url":"订单详情-订单取消.html",
  "generationDate":new Date(1496903835660.76),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"sfz",
"sfz_n"],
  "page":{
    "packageId":"fbf55880d2fb4d59b91dce9806666e81",
    "type":"Axure:Page",
    "name":"订单详情-订单取消",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"826ef866d0994b2387c588ca2dc75a34",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "size":{
              "width":320,
              "height":740},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21ee0b75038c48cf9fe4efd48d909945",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "size":{
                  "width":320,
                  "height":740},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单详情-待退款/u0.png"}},
{
          "id":"4ba02173c313429eb253abea60922d80",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "fixedHorizontal":"left",
          "fixedMarginHorizontal":0,
          "fixedVertical":"top",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"f301f80877c344ecb9aaaf29eee82e6b",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"9b1c4cc7bbd3415cab579dc531fa2c0c",
                  "label":"",
                  "parentDynamicPanel":"4ba02173c313429eb253abea60922d80",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF1C222E},
                    "size":{
                      "width":320,
                      "height":64},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c70b2c837e7b4ff4ac7136fba44e1a4f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4ba02173c313429eb253abea60922d80",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF1C222E},
                        "size":{
                          "width":320,
                          "height":64},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u3.png"}},
{
                  "id":"d2bd842331624799ab145295310b14fa",
                  "label":"",
                  "parentDynamicPanel":"4ba02173c313429eb253abea60922d80",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Heiti SC Regular', 'Heiti SC'",
                    "fontSize":"18px",
                    "fontWeight":"200",
                    "horizontalAlignment":"center",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":78,
                      "y":35},
                    "size":{
                      "width":163,
                      "height":22},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6e168ab7010145e5b41891e0ccd76cd0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4ba02173c313429eb253abea60922d80",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Heiti SC Regular', 'Heiti SC'",
                        "fontSize":"18px",
                        "fontWeight":"200",
                        "horizontalAlignment":"center",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":78,
                          "y":35},
                        "size":{
                          "width":163,
                          "height":22},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"08160d8095974a6890e076b73abd020a",
                  "label":"",
                  "parentDynamicPanel":"4ba02173c313429eb253abea60922d80",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":320,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"572612e87e584af98f985f7753c87d2e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4ba02173c313429eb253abea60922d80",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":320,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u7.png"}},
{
                  "id":"528ad499738045bfbb39113d0422c20b",
                  "label":"",
                  "parentDynamicPanel":"4ba02173c313429eb253abea60922d80",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Heiti SC Regular', 'Heiti SC'",
                    "fontSize":"16px",
                    "fontWeight":"200",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":27,
                      "y":36},
                    "size":{
                      "width":63,
                      "height":19},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ac0de871940040cca3801abf9c52af8d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4ba02173c313429eb253abea60922d80",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Heiti SC Regular', 'Heiti SC'",
                        "fontSize":"16px",
                        "fontWeight":"200",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":27,
                          "y":36},
                        "size":{
                          "width":63,
                          "height":19},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"1c300411bc564136a5e8eee120b38202",
                  "label":"",
                  "parentDynamicPanel":"4ba02173c313429eb253abea60922d80",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Lucida Grande Regular', 'Lucida Grande'",
                    "fontSize":"20px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":9,
                      "y":31},
                    "size":{
                      "width":22,
                      "height":29}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"52e4cbddbb7b478eb53949052093a2ed",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4ba02173c313429eb253abea60922d80",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Lucida Grande Regular', 'Lucida Grande'",
                        "fontSize":"20px",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":9,
                          "y":31},
                        "size":{
                          "width":22,
                          "height":29}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"58dd7240f6eb459898edfda4a53469ce",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":0,
              "y":63},
            "size":{
              "width":320,
              "height":96}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b572efbd96f442b1a4fc9b222bc12a11",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":0,
                  "y":63},
                "size":{
                  "width":320,
                  "height":96}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的/u21.png"}},
{
          "id":"296099330fbc4df6bee0d74d277f8d67",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":74},
            "size":{
              "width":97,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c41d3c6c1454b0ba6b51df98af0b36d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":74},
                "size":{
                  "width":97,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"19a1f04330dc4dc4a93337d1fd157c16",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":10,
              "y":124},
            "size":{
              "width":290,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b2079b5f6f8428da69874901f61d08a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":10,
                  "y":124},
                "size":{
                  "width":290,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a11d17c27c28413ab13e009ff9e9fc0e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":390,
              "y":0},
            "size":{
              "width":320,
              "height":770},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eaba115819de42a2ad383feff9ec11b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":390,
                  "y":0},
                "size":{
                  "width":320,
                  "height":770},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单详情-订单取消/u19.png"}},
{
          "id":"65fcf943251e4e8ca3ef0721d5d3b35e",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":390,
              "y":0},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "fixedHorizontal":"left",
          "fixedMarginHorizontal":390,
          "fixedVertical":"top",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"5d35ac11031844a08636f5e16095729a",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"e81d4a23a987459b90ed2eb1d9b1e92a",
                  "label":"",
                  "parentDynamicPanel":"65fcf943251e4e8ca3ef0721d5d3b35e",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF1C222E},
                    "size":{
                      "width":320,
                      "height":64},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7609f7e0b3b343329232cb35a11afde9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"65fcf943251e4e8ca3ef0721d5d3b35e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF1C222E},
                        "size":{
                          "width":320,
                          "height":64},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u3.png"}},
{
                  "id":"84b8470c30ad40bca26a54c2bb3cce72",
                  "label":"",
                  "parentDynamicPanel":"65fcf943251e4e8ca3ef0721d5d3b35e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Heiti SC Regular', 'Heiti SC'",
                    "fontSize":"18px",
                    "fontWeight":"200",
                    "horizontalAlignment":"center",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":78,
                      "y":35},
                    "size":{
                      "width":163,
                      "height":22},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f0f404ad67de40c78070c8f2b735eeef",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"65fcf943251e4e8ca3ef0721d5d3b35e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Heiti SC Regular', 'Heiti SC'",
                        "fontSize":"18px",
                        "fontWeight":"200",
                        "horizontalAlignment":"center",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":78,
                          "y":35},
                        "size":{
                          "width":163,
                          "height":22},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"5ce9c02f6ed140cbb2f2f23fb27e7e3f",
                  "label":"",
                  "parentDynamicPanel":"65fcf943251e4e8ca3ef0721d5d3b35e",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":320,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"edc519cb0d064d8baa40223b270ad703",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"65fcf943251e4e8ca3ef0721d5d3b35e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":320,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u7.png"}},
{
                  "id":"89af71d6431a4b4098efab5cb5f6a738",
                  "label":"",
                  "parentDynamicPanel":"65fcf943251e4e8ca3ef0721d5d3b35e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Heiti SC Regular', 'Heiti SC'",
                    "fontSize":"16px",
                    "fontWeight":"200",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":27,
                      "y":36},
                    "size":{
                      "width":63,
                      "height":19},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"77997d97a5264d1cacf5172c2088a053",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"65fcf943251e4e8ca3ef0721d5d3b35e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Heiti SC Regular', 'Heiti SC'",
                        "fontSize":"16px",
                        "fontWeight":"200",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":27,
                          "y":36},
                        "size":{
                          "width":63,
                          "height":19},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"7787550ac4eb4c059d170e3c039d84df",
                  "label":"",
                  "parentDynamicPanel":"65fcf943251e4e8ca3ef0721d5d3b35e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Lucida Grande Regular', 'Lucida Grande'",
                    "fontSize":"20px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":9,
                      "y":31},
                    "size":{
                      "width":22,
                      "height":29}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e74a383cc5d747b6bb89ed27016765c6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"65fcf943251e4e8ca3ef0721d5d3b35e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Lucida Grande Regular', 'Lucida Grande'",
                        "fontSize":"20px",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":9,
                          "y":31},
                        "size":{
                          "width":22,
                          "height":29}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"f06985db2b234ef6b1e1f4f77ebd0c64",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":390,
              "y":63},
            "size":{
              "width":320,
              "height":96}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64c64088b36c4bee8a397ba38503855c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":390,
                  "y":63},
                "size":{
                  "width":320,
                  "height":96}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的/u21.png"}},
{
          "id":"c07ff666dad54dc7a3e1385be24c3cf5",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":400,
              "y":74},
            "size":{
              "width":97,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e0b289368d34123ba420b6ce0c61070",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":400,
                  "y":74},
                "size":{
                  "width":97,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"538a3bc972ab42d397dd1866153858f0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":400,
              "y":124},
            "size":{
              "width":301,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e02171589bd487c906fc08f0e0a0c6c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":400,
                  "y":124},
                "size":{
                  "width":301,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"44633425b774435b93adfc7dce5fc4e8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "location":{
              "x":0,
              "y":440},
            "size":{
              "width":320,
              "height":112}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba07346250a0409d847e450068d6f3fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "location":{
                  "x":0,
                  "y":440},
                "size":{
                  "width":320,
                  "height":112}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单详情-订单取消/u38.png"}},
{
          "id":"ffbf4a0581d24ace8f426ff837d32dc9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "location":{
              "x":390,
              "y":520},
            "size":{
              "width":320,
              "height":111}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b15002864e24653966f17cca4290a3b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "location":{
                  "x":390,
                  "y":520},
                "size":{
                  "width":320,
                  "height":111}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单详情-待开奖/u60.png"}},
{
          "id":"52f16b8c80a84d42821dc2f80d9e430e",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":116,
              "y":692},
            "size":{
              "width":88,
              "height":35}},
          "adaptiveStyles":{
}},
{
          "id":"5f523c8a475343b597343751b650c49b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":0,
              "y":169},
            "size":{
              "width":320,
              "height":91}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"50c6b09f6607448fac48155304913ed8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":0,
                  "y":169},
                "size":{
                  "width":320,
                  "height":91}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单详情-待支付/u19.png"}},
{
          "id":"06349cca12374f4b8aff9cfe585ab91a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":9,
              "y":180},
            "size":{
              "width":66,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1db289d4354e403e865bd2358f01679c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":9,
                  "y":180},
                "size":{
                  "width":66,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单中心/u28.png"}},
{
          "id":"c54d2d55bf0946eb9b5cb64392cc0917",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":85,
              "y":180},
            "size":{
              "width":226,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7591e6ea9dce4baeafeebdd75be9099f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":85,
                  "y":180},
                "size":{
                  "width":226,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2d70de1b43f54986ae9461afb8cc43ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":85,
              "y":234},
            "size":{
              "width":226,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f09ba71e4f5845a39a8fa2e526b84d86",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":85,
                  "y":234},
                "size":{
                  "width":226,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6a45fd2d5f104f049e2dc4ba6f8594c0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":144,
              "y":183},
            "size":{
              "width":186,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d1ae25d2d59489e99af6fe45d4e0ef7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":144,
                  "y":183},
                "size":{
                  "width":186,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"96587f9c73e248efa49f58ad4a6a795d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":0,
              "y":259},
            "size":{
              "width":320,
              "height":117}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8dd531f2f4a3454ea659a88755e71973",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":259},
                "size":{
                  "width":320,
                  "height":117}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单详情-待支付/u35.png"}},
{
          "id":"62fcc44fcd4d41d9aa2354e813bcd4c0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":0,
              "y":277},
            "size":{
              "width":259,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"17f926dba8bf4dd0bf48eecf3d634687",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":0,
                  "y":277},
                "size":{
                  "width":259,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5684ba50f3514ff58015bc2365ae4c5a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":0,
              "y":309},
            "size":{
              "width":255,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"457e3bd1ee85440ba5a660283b483c9f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":0,
                  "y":309},
                "size":{
                  "width":255,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9bb4e38531374600a810b7358c01a213",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":0,
              "y":343},
            "size":{
              "width":312,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1f6e3e3330642a585cba3d11496e016",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":0,
                  "y":343},
                "size":{
                  "width":312,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e2b686f521584656933bcb99a79fcbf2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":0,
              "y":375},
            "size":{
              "width":320,
              "height":55}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"808f111b2c224c1f98cab3a298d14fba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":375},
                "size":{
                  "width":320,
                  "height":55}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单详情-待支付/u43.png"}},
{
          "id":"c3194125b03e4d389d8c6ac8445fb5b8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "horizontalAlignment":"right",
            "location":{
              "x":99,
              "y":393},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e5bcf3f4ed8a4d20a00676730d96c26d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "horizontalAlignment":"right",
                "location":{
                  "x":99,
                  "y":393},
                "size":{
                  "width":200,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"99682373bd2c48a3a0f263b03d4837fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":390,
              "y":165},
            "size":{
              "width":320,
              "height":91}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8fe3eac01ea64b23bf641e654c03f9dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":390,
                  "y":165},
                "size":{
                  "width":320,
                  "height":91}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单详情-待支付/u19.png"}},
{
          "id":"207c28f900fe42339820c54d28a0184b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":399,
              "y":176},
            "size":{
              "width":66,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41b261decfe5487a90644761b5754901",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":399,
                  "y":176},
                "size":{
                  "width":66,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单中心/u28.png"}},
{
          "id":"f50da1235b93412889cdc783cb772227",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":475,
              "y":176},
            "size":{
              "width":226,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8263c1998ba044f7950282c1507c05fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":475,
                  "y":176},
                "size":{
                  "width":226,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"18877a99b668475baa4c5151fcc4ee29",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":475,
              "y":230},
            "size":{
              "width":226,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a5481836f88a4d308efa821204cc6f8a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":475,
                  "y":230},
                "size":{
                  "width":226,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"efc060c77bfa4c09a17b8db9ef91350e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":534,
              "y":179},
            "size":{
              "width":186,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1f3a23e91684b14b55433d033006d46",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":534,
                  "y":179},
                "size":{
                  "width":186,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3e8f2afda26043f5823c544ec9fe2ded",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":390,
              "y":255},
            "size":{
              "width":320,
              "height":117}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a0f7ae280c43438caf7416c6010a1ab5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":390,
                  "y":255},
                "size":{
                  "width":320,
                  "height":117}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单详情-待支付/u35.png"}},
{
          "id":"b9fe0625713c4f8baecfcc62e8ca86a0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":390,
              "y":273},
            "size":{
              "width":259,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7eeb349e98c4f958673d6de3a187aea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":390,
                  "y":273},
                "size":{
                  "width":259,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c21a3717b84a467ba992f7813a5e7e9c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":390,
              "y":305},
            "size":{
              "width":255,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f3f891993bd4d0c8c3b11efe3d40ec4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":390,
                  "y":305},
                "size":{
                  "width":255,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"27d1dfc5f8994c38815f619f2f3176d0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":390,
              "y":371},
            "size":{
              "width":320,
              "height":94}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"017dfc2b47ac489ba04dac305d345e8c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":390,
                  "y":371},
                "size":{
                  "width":320,
                  "height":94}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单详情-合买中/u35.png"}},
{
          "id":"a6c2e323b8e44135856303db0b97805f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"left",
            "location":{
              "x":390,
              "y":464},
            "size":{
              "width":320,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a3956d90b4243ae8444a39edce2f847",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"left",
                "location":{
                  "x":390,
                  "y":464},
                "size":{
                  "width":320,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单详情-合买中/u231.png"}},
{
          "id":"23ef91ab001e45cf9b4122fa29dc4114",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":390,
              "y":339},
            "size":{
              "width":312,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1505e58c34d4ed9b10de598ac88de78",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":390,
                  "y":339},
                "size":{
                  "width":312,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"16391d8f9cf14e60a6b2282ee3af7ed9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":489,
              "y":414},
            "size":{
              "width":200,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8624a4e440bd40229f2fc57940829499",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":489,
                  "y":414},
                "size":{
                  "width":200,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e2b3838d96054082b776f870b8ac8ba2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "horizontalAlignment":"right",
            "location":{
              "x":489,
              "y":382},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9324e2bca3d843ff8be77db434437156",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "horizontalAlignment":"right",
                "location":{
                  "x":489,
                  "y":382},
                "size":{
                  "width":200,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a3d8c9646e12499eb6927a7224d51166",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":639,
              "y":475},
            "size":{
              "width":22,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8fbe0203e69840568358072c91b3e57f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":639,
                  "y":475},
                "size":{
                  "width":22,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单详情-合买中/u281.png"}},
{
          "id":"bbf6948c4f11406abf2b7d44dcdee23f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":0,
              "y":680},
            "size":{
              "width":320,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ad6762afb674ee487db14ccce291828",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":0,
                  "y":680},
                "size":{
                  "width":320,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单详情-待支付/u31.png"}},
{
          "id":"9d9ca3eb84da46f6876f6e388412e54d",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":218,
              "y":692},
            "size":{
              "width":88,
              "height":35}},
          "adaptiveStyles":{
}},
{
          "id":"f6a5d67679314befa06baa6d4c6e360a",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":116,
              "y":692},
            "size":{
              "width":88,
              "height":35}},
          "adaptiveStyles":{
}},
{
          "id":"2a5c585ef9014f4bba3d34830a972607",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":390,
              "y":710},
            "size":{
              "width":320,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"88f4f924a20249da8b8d3f5dc25c5513",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":390,
                  "y":710},
                "size":{
                  "width":320,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单详情-待支付/u31.png"}},
{
          "id":"cdae8ad6ad8e45438dd8c60240b2fc92",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":608,
              "y":722},
            "size":{
              "width":88,
              "height":35}},
          "adaptiveStyles":{
}},
{
          "id":"77f34a603cb541b18f4000e3b3bd0764",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":506,
              "y":722},
            "size":{
              "width":88,
              "height":35}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "826ef866d0994b2387c588ca2dc75a34":{
      "scriptId":"u0"},
    "21ee0b75038c48cf9fe4efd48d909945":{
      "scriptId":"u1"},
    "4ba02173c313429eb253abea60922d80":{
      "scriptId":"u2"},
    "9b1c4cc7bbd3415cab579dc531fa2c0c":{
      "scriptId":"u3"},
    "c70b2c837e7b4ff4ac7136fba44e1a4f":{
      "scriptId":"u4"},
    "d2bd842331624799ab145295310b14fa":{
      "scriptId":"u5"},
    "6e168ab7010145e5b41891e0ccd76cd0":{
      "scriptId":"u6"},
    "08160d8095974a6890e076b73abd020a":{
      "scriptId":"u7"},
    "572612e87e584af98f985f7753c87d2e":{
      "scriptId":"u8"},
    "528ad499738045bfbb39113d0422c20b":{
      "scriptId":"u9"},
    "ac0de871940040cca3801abf9c52af8d":{
      "scriptId":"u10"},
    "1c300411bc564136a5e8eee120b38202":{
      "scriptId":"u11"},
    "52e4cbddbb7b478eb53949052093a2ed":{
      "scriptId":"u12"},
    "58dd7240f6eb459898edfda4a53469ce":{
      "scriptId":"u13"},
    "b572efbd96f442b1a4fc9b222bc12a11":{
      "scriptId":"u14"},
    "296099330fbc4df6bee0d74d277f8d67":{
      "scriptId":"u15"},
    "1c41d3c6c1454b0ba6b51df98af0b36d":{
      "scriptId":"u16"},
    "19a1f04330dc4dc4a93337d1fd157c16":{
      "scriptId":"u17"},
    "3b2079b5f6f8428da69874901f61d08a":{
      "scriptId":"u18"},
    "a11d17c27c28413ab13e009ff9e9fc0e":{
      "scriptId":"u19"},
    "eaba115819de42a2ad383feff9ec11b1":{
      "scriptId":"u20"},
    "65fcf943251e4e8ca3ef0721d5d3b35e":{
      "scriptId":"u21"},
    "e81d4a23a987459b90ed2eb1d9b1e92a":{
      "scriptId":"u22"},
    "7609f7e0b3b343329232cb35a11afde9":{
      "scriptId":"u23"},
    "84b8470c30ad40bca26a54c2bb3cce72":{
      "scriptId":"u24"},
    "f0f404ad67de40c78070c8f2b735eeef":{
      "scriptId":"u25"},
    "5ce9c02f6ed140cbb2f2f23fb27e7e3f":{
      "scriptId":"u26"},
    "edc519cb0d064d8baa40223b270ad703":{
      "scriptId":"u27"},
    "89af71d6431a4b4098efab5cb5f6a738":{
      "scriptId":"u28"},
    "77997d97a5264d1cacf5172c2088a053":{
      "scriptId":"u29"},
    "7787550ac4eb4c059d170e3c039d84df":{
      "scriptId":"u30"},
    "e74a383cc5d747b6bb89ed27016765c6":{
      "scriptId":"u31"},
    "f06985db2b234ef6b1e1f4f77ebd0c64":{
      "scriptId":"u32"},
    "64c64088b36c4bee8a397ba38503855c":{
      "scriptId":"u33"},
    "c07ff666dad54dc7a3e1385be24c3cf5":{
      "scriptId":"u34"},
    "5e0b289368d34123ba420b6ce0c61070":{
      "scriptId":"u35"},
    "538a3bc972ab42d397dd1866153858f0":{
      "scriptId":"u36"},
    "2e02171589bd487c906fc08f0e0a0c6c":{
      "scriptId":"u37"},
    "44633425b774435b93adfc7dce5fc4e8":{
      "scriptId":"u38"},
    "ba07346250a0409d847e450068d6f3fe":{
      "scriptId":"u39"},
    "ffbf4a0581d24ace8f426ff837d32dc9":{
      "scriptId":"u40"},
    "3b15002864e24653966f17cca4290a3b":{
      "scriptId":"u41"},
    "52f16b8c80a84d42821dc2f80d9e430e":{
      "scriptId":"u42"},
    "5f523c8a475343b597343751b650c49b":{
      "scriptId":"u43"},
    "50c6b09f6607448fac48155304913ed8":{
      "scriptId":"u44"},
    "06349cca12374f4b8aff9cfe585ab91a":{
      "scriptId":"u45"},
    "1db289d4354e403e865bd2358f01679c":{
      "scriptId":"u46"},
    "c54d2d55bf0946eb9b5cb64392cc0917":{
      "scriptId":"u47"},
    "7591e6ea9dce4baeafeebdd75be9099f":{
      "scriptId":"u48"},
    "2d70de1b43f54986ae9461afb8cc43ab":{
      "scriptId":"u49"},
    "f09ba71e4f5845a39a8fa2e526b84d86":{
      "scriptId":"u50"},
    "6a45fd2d5f104f049e2dc4ba6f8594c0":{
      "scriptId":"u51"},
    "4d1ae25d2d59489e99af6fe45d4e0ef7":{
      "scriptId":"u52"},
    "96587f9c73e248efa49f58ad4a6a795d":{
      "scriptId":"u53"},
    "8dd531f2f4a3454ea659a88755e71973":{
      "scriptId":"u54"},
    "62fcc44fcd4d41d9aa2354e813bcd4c0":{
      "scriptId":"u55"},
    "17f926dba8bf4dd0bf48eecf3d634687":{
      "scriptId":"u56"},
    "5684ba50f3514ff58015bc2365ae4c5a":{
      "scriptId":"u57"},
    "457e3bd1ee85440ba5a660283b483c9f":{
      "scriptId":"u58"},
    "9bb4e38531374600a810b7358c01a213":{
      "scriptId":"u59"},
    "d1f6e3e3330642a585cba3d11496e016":{
      "scriptId":"u60"},
    "e2b686f521584656933bcb99a79fcbf2":{
      "scriptId":"u61"},
    "808f111b2c224c1f98cab3a298d14fba":{
      "scriptId":"u62"},
    "c3194125b03e4d389d8c6ac8445fb5b8":{
      "scriptId":"u63"},
    "e5bcf3f4ed8a4d20a00676730d96c26d":{
      "scriptId":"u64"},
    "99682373bd2c48a3a0f263b03d4837fa":{
      "scriptId":"u65"},
    "8fe3eac01ea64b23bf641e654c03f9dd":{
      "scriptId":"u66"},
    "207c28f900fe42339820c54d28a0184b":{
      "scriptId":"u67"},
    "41b261decfe5487a90644761b5754901":{
      "scriptId":"u68"},
    "f50da1235b93412889cdc783cb772227":{
      "scriptId":"u69"},
    "8263c1998ba044f7950282c1507c05fa":{
      "scriptId":"u70"},
    "18877a99b668475baa4c5151fcc4ee29":{
      "scriptId":"u71"},
    "a5481836f88a4d308efa821204cc6f8a":{
      "scriptId":"u72"},
    "efc060c77bfa4c09a17b8db9ef91350e":{
      "scriptId":"u73"},
    "b1f3a23e91684b14b55433d033006d46":{
      "scriptId":"u74"},
    "3e8f2afda26043f5823c544ec9fe2ded":{
      "scriptId":"u75"},
    "a0f7ae280c43438caf7416c6010a1ab5":{
      "scriptId":"u76"},
    "b9fe0625713c4f8baecfcc62e8ca86a0":{
      "scriptId":"u77"},
    "b7eeb349e98c4f958673d6de3a187aea":{
      "scriptId":"u78"},
    "c21a3717b84a467ba992f7813a5e7e9c":{
      "scriptId":"u79"},
    "6f3f891993bd4d0c8c3b11efe3d40ec4":{
      "scriptId":"u80"},
    "27d1dfc5f8994c38815f619f2f3176d0":{
      "scriptId":"u81"},
    "017dfc2b47ac489ba04dac305d345e8c":{
      "scriptId":"u82"},
    "a6c2e323b8e44135856303db0b97805f":{
      "scriptId":"u83"},
    "4a3956d90b4243ae8444a39edce2f847":{
      "scriptId":"u84"},
    "23ef91ab001e45cf9b4122fa29dc4114":{
      "scriptId":"u85"},
    "f1505e58c34d4ed9b10de598ac88de78":{
      "scriptId":"u86"},
    "16391d8f9cf14e60a6b2282ee3af7ed9":{
      "scriptId":"u87"},
    "8624a4e440bd40229f2fc57940829499":{
      "scriptId":"u88"},
    "e2b3838d96054082b776f870b8ac8ba2":{
      "scriptId":"u89"},
    "9324e2bca3d843ff8be77db434437156":{
      "scriptId":"u90"},
    "a3d8c9646e12499eb6927a7224d51166":{
      "scriptId":"u91"},
    "8fbe0203e69840568358072c91b3e57f":{
      "scriptId":"u92"},
    "bbf6948c4f11406abf2b7d44dcdee23f":{
      "scriptId":"u93"},
    "4ad6762afb674ee487db14ccce291828":{
      "scriptId":"u94"},
    "9d9ca3eb84da46f6876f6e388412e54d":{
      "scriptId":"u95"},
    "f6a5d67679314befa06baa6d4c6e360a":{
      "scriptId":"u96"},
    "2a5c585ef9014f4bba3d34830a972607":{
      "scriptId":"u97"},
    "88f4f924a20249da8b8d3f5dc25c5513":{
      "scriptId":"u98"},
    "cdae8ad6ad8e45438dd8c60240b2fc92":{
      "scriptId":"u99"},
    "77f34a603cb541b18f4000e3b3bd0764":{
      "scriptId":"u100"}}});