$axure.loadCurrentPage({
  "url":"提现.html",
  "generationDate":new Date(1496903830364.76),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"sfz",
"sfz_n"],
  "page":{
    "packageId":"2ea5df1ed62742fda9ab9baa7ee7494d",
    "type":"Axure:Page",
    "name":"提现",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"94ffec0e070e4397953d8fb8c4d34147",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "size":{
              "width":320,
              "height":500},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b86101514b6c4eacb8a255a02760afaf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "size":{
                  "width":320,
                  "height":500},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/钱包/u0.png"}},
{
          "id":"e51eaf74ea9c41428a330792390714fd",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "fixedHorizontal":"left",
          "fixedMarginHorizontal":0,
          "fixedVertical":"top",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"34b29ac71d234f95a385ea56c23469fa",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"dcba0ad79ef2496a8436285ac1f00b54",
                  "label":"",
                  "parentDynamicPanel":"e51eaf74ea9c41428a330792390714fd",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF1C222E},
                    "size":{
                      "width":320,
                      "height":64},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"173d9d5884364164b1f021d65e67ff3c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e51eaf74ea9c41428a330792390714fd",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF1C222E},
                        "size":{
                          "width":320,
                          "height":64},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u3.png"}},
{
                  "id":"f6d2e9fd24354e728f70ae920d28eece",
                  "label":"",
                  "parentDynamicPanel":"e51eaf74ea9c41428a330792390714fd",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Heiti SC Regular', 'Heiti SC'",
                    "fontSize":"18px",
                    "fontWeight":"200",
                    "horizontalAlignment":"center",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":78,
                      "y":35},
                    "size":{
                      "width":163,
                      "height":22},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"aa01f7e008cb4e99b383ee41c8be7af6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e51eaf74ea9c41428a330792390714fd",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Heiti SC Regular', 'Heiti SC'",
                        "fontSize":"18px",
                        "fontWeight":"200",
                        "horizontalAlignment":"center",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":78,
                          "y":35},
                        "size":{
                          "width":163,
                          "height":22},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"156ec34216df426c97ebaef4d4a5c92e",
                  "label":"",
                  "parentDynamicPanel":"e51eaf74ea9c41428a330792390714fd",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":320,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"308b426ba5994a89a5bde8b26e169863",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e51eaf74ea9c41428a330792390714fd",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":320,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u7.png"}},
{
                  "id":"d628ad00b39a4035a3ec2f6a2dfa3d72",
                  "label":"",
                  "parentDynamicPanel":"e51eaf74ea9c41428a330792390714fd",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Heiti SC Regular', 'Heiti SC'",
                    "fontSize":"16px",
                    "fontWeight":"200",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":27,
                      "y":36},
                    "size":{
                      "width":63,
                      "height":19},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c3aee1a1b5a946fe945eb8c5bab7b314",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e51eaf74ea9c41428a330792390714fd",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Heiti SC Regular', 'Heiti SC'",
                        "fontSize":"16px",
                        "fontWeight":"200",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":27,
                          "y":36},
                        "size":{
                          "width":63,
                          "height":19},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"63bc6be3731c4319b0a509eac920d294",
                  "label":"",
                  "parentDynamicPanel":"e51eaf74ea9c41428a330792390714fd",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Lucida Grande Regular', 'Lucida Grande'",
                    "fontSize":"20px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":9,
                      "y":31},
                    "size":{
                      "width":22,
                      "height":29}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6d2e7705150b48c590ebeadb32bed5d6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e51eaf74ea9c41428a330792390714fd",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Lucida Grande Regular', 'Lucida Grande'",
                        "fontSize":"20px",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":9,
                          "y":31},
                        "size":{
                          "width":22,
                          "height":29}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"604b308f381d4e1f91d6b920f362e3f1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":0,
              "y":74},
            "size":{
              "width":320,
              "height":66}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e016d3477c046b7b509b02d351eb5b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":0,
                  "y":74},
                "size":{
                  "width":320,
                  "height":66}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值/u19.png"}},
{
          "id":"61471fbe82e64b3fb7075ef6e610cd7e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":10,
              "y":80},
            "size":{
              "width":60,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"37aa14645fe24fb8be16aa2e1915a57b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":10,
                  "y":80},
                "size":{
                  "width":60,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值/u21.png"}},
{
          "id":"e53f593a181b40848ee7275ac15dc31e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":80,
              "y":80},
            "size":{
              "width":100,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ccbaaa6fee044b2be61b7d836b59535",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":80,
                  "y":80},
                "size":{
                  "width":100,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"66c67f6f186b4fcf9e4d470ed0604062",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "location":{
              "x":0,
              "y":150},
            "size":{
              "width":320,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1694633bc14c4fb79de05bc30b6040e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "location":{
                  "x":0,
                  "y":150},
                "size":{
                  "width":320,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择号码-双色球/u137.png"}},
{
          "id":"db7cf42a19d24d3ea75fff88cf565c4e",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "stateStyles":{
              "hint":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1}}},
            "location":{
              "x":60,
              "y":157.5},
            "size":{
              "width":200,
              "height":35}},
          "adaptiveStyles":{
},
          "placeholderText":"请输入提现金额"},
{
          "id":"e9adb519c70148df87ed17efc7065abc",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":10,
              "y":240},
            "size":{
              "width":280,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"4b698d4a33044dea9720c704b6d6d376",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":10,
              "y":210},
            "size":{
              "width":290,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ca262c7f2064af3a3f68b59ddd05418",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":10,
                  "y":210},
                "size":{
                  "width":290,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0cf7cbf28faa4881b7e82a21a2f116b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":80,
              "y":114},
            "size":{
              "width":120,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7428edc156a54f69b7f7d734d08a1d44",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":80,
                  "y":114},
                "size":{
                  "width":120,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "94ffec0e070e4397953d8fb8c4d34147":{
      "scriptId":"u0"},
    "b86101514b6c4eacb8a255a02760afaf":{
      "scriptId":"u1"},
    "e51eaf74ea9c41428a330792390714fd":{
      "scriptId":"u2"},
    "dcba0ad79ef2496a8436285ac1f00b54":{
      "scriptId":"u3"},
    "173d9d5884364164b1f021d65e67ff3c":{
      "scriptId":"u4"},
    "f6d2e9fd24354e728f70ae920d28eece":{
      "scriptId":"u5"},
    "aa01f7e008cb4e99b383ee41c8be7af6":{
      "scriptId":"u6"},
    "156ec34216df426c97ebaef4d4a5c92e":{
      "scriptId":"u7"},
    "308b426ba5994a89a5bde8b26e169863":{
      "scriptId":"u8"},
    "d628ad00b39a4035a3ec2f6a2dfa3d72":{
      "scriptId":"u9"},
    "c3aee1a1b5a946fe945eb8c5bab7b314":{
      "scriptId":"u10"},
    "63bc6be3731c4319b0a509eac920d294":{
      "scriptId":"u11"},
    "6d2e7705150b48c590ebeadb32bed5d6":{
      "scriptId":"u12"},
    "604b308f381d4e1f91d6b920f362e3f1":{
      "scriptId":"u13"},
    "6e016d3477c046b7b509b02d351eb5b4":{
      "scriptId":"u14"},
    "61471fbe82e64b3fb7075ef6e610cd7e":{
      "scriptId":"u15"},
    "37aa14645fe24fb8be16aa2e1915a57b":{
      "scriptId":"u16"},
    "e53f593a181b40848ee7275ac15dc31e":{
      "scriptId":"u17"},
    "7ccbaaa6fee044b2be61b7d836b59535":{
      "scriptId":"u18"},
    "66c67f6f186b4fcf9e4d470ed0604062":{
      "scriptId":"u19"},
    "1694633bc14c4fb79de05bc30b6040e8":{
      "scriptId":"u20"},
    "db7cf42a19d24d3ea75fff88cf565c4e":{
      "scriptId":"u21"},
    "e9adb519c70148df87ed17efc7065abc":{
      "scriptId":"u22"},
    "4b698d4a33044dea9720c704b6d6d376":{
      "scriptId":"u23"},
    "4ca262c7f2064af3a3f68b59ddd05418":{
      "scriptId":"u24"},
    "0cf7cbf28faa4881b7e82a21a2f116b4":{
      "scriptId":"u25"},
    "7428edc156a54f69b7f7d734d08a1d44":{
      "scriptId":"u26"}}});