$axure.loadCurrentPage({
  "url":"店主中心.html",
  "generationDate":new Date(1496903835873.76),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"sfz",
"sfz_n"],
  "page":{
    "packageId":"9c38a2c8ca034c5183e61efd80cc2696",
    "type":"Axure:Page",
    "name":"店主中心",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"2ab24f8ebbee4de98ad21cbb8686479b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "size":{
              "width":320,
              "height":700},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7ad8b2d40fa4389944635d2e427e1b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "size":{
                  "width":320,
                  "height":700},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/店主中心/u0.png"}},
{
          "id":"fdac3eb5757443d2a7983594cfa53e96",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "fixedHorizontal":"left",
          "fixedMarginHorizontal":0,
          "fixedVertical":"top",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"fe645f27427e48d09f7ee59b9f7c98b3",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"9592d30c7a5149c1bc7a5d98143f4d88",
                  "label":"",
                  "parentDynamicPanel":"fdac3eb5757443d2a7983594cfa53e96",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF1C222E},
                    "size":{
                      "width":320,
                      "height":64},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"812f561c9e924533967aa5d36ad1a9df",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"fdac3eb5757443d2a7983594cfa53e96",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF1C222E},
                        "size":{
                          "width":320,
                          "height":64},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u3.png"}},
{
                  "id":"474fabfc587e4490b84e7cc6ddeeab79",
                  "label":"",
                  "parentDynamicPanel":"fdac3eb5757443d2a7983594cfa53e96",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Heiti SC Regular', 'Heiti SC'",
                    "fontSize":"18px",
                    "fontWeight":"200",
                    "horizontalAlignment":"center",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":78,
                      "y":35},
                    "size":{
                      "width":163,
                      "height":22},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9938d3ce84ec4c3b83d2f3a6dcec0f6c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"fdac3eb5757443d2a7983594cfa53e96",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Heiti SC Regular', 'Heiti SC'",
                        "fontSize":"18px",
                        "fontWeight":"200",
                        "horizontalAlignment":"center",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":78,
                          "y":35},
                        "size":{
                          "width":163,
                          "height":22},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"a90ebf0079964dd9a9e66363bb1da9db",
                  "label":"",
                  "parentDynamicPanel":"fdac3eb5757443d2a7983594cfa53e96",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":320,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0cab16aee17749adac24c2e1d5736cb0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"fdac3eb5757443d2a7983594cfa53e96",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":320,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u7.png"}},
{
                  "id":"bf211944d2934e168354614c411d732d",
                  "label":"",
                  "parentDynamicPanel":"fdac3eb5757443d2a7983594cfa53e96",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Heiti SC Regular', 'Heiti SC'",
                    "fontSize":"16px",
                    "fontWeight":"200",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":27,
                      "y":36},
                    "size":{
                      "width":63,
                      "height":19},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2740c4083df24f18a78dded43455db16",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"fdac3eb5757443d2a7983594cfa53e96",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Heiti SC Regular', 'Heiti SC'",
                        "fontSize":"16px",
                        "fontWeight":"200",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":27,
                          "y":36},
                        "size":{
                          "width":63,
                          "height":19},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"7e3a5710a3f64d8ca38f57752443187d",
                  "label":"",
                  "parentDynamicPanel":"fdac3eb5757443d2a7983594cfa53e96",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Lucida Grande Regular', 'Lucida Grande'",
                    "fontSize":"20px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":9,
                      "y":31},
                    "size":{
                      "width":22,
                      "height":29}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"89b4d0a9d5c943ee9a4a0b3935c65dfd",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"fdac3eb5757443d2a7983594cfa53e96",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Lucida Grande Regular', 'Lucida Grande'",
                        "fontSize":"20px",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":9,
                          "y":31},
                        "size":{
                          "width":22,
                          "height":29}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"e42ff94912c84e6080e2db7deb5119ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":0,
              "y":63},
            "size":{
              "width":320,
              "height":96}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e3e4d809d914049ac335a47b57b0726",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":0,
                  "y":63},
                "size":{
                  "width":320,
                  "height":96}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的/u21.png"}},
{
          "id":"9806c0a10010490091dc222b155b4976",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":10,
              "y":74},
            "size":{
              "width":71,
              "height":66}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79bb53ffa70c4367a91ce77c3ec5e577",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":10,
                  "y":74},
                "size":{
                  "width":71,
                  "height":66}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的/u23.png"}},
{
          "id":"da858e059d8f44b7a881664b7eaeb83e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":100,
              "y":98},
            "size":{
              "width":99,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53bf309246ab4644858c8723e920aa70",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":100,
                  "y":98},
                "size":{
                  "width":99,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"868b64a38c2a418c89ed4f5b5004862b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":230,
              "y":95},
            "size":{
              "width":60,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f01742c48a25445d817461136f9ec76f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":230,
                  "y":95},
                "size":{
                  "width":60,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的/u29.png"}},
{
          "id":"eefd609b94b540aa8a18ae8e08dfd3fc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "location":{
              "x":0,
              "y":169},
            "size":{
              "width":320,
              "height":51}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd59df19847b442c8846f72db6f87209",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "location":{
                  "x":0,
                  "y":169},
                "size":{
                  "width":320,
                  "height":51}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/确认订单-双色球/u25.png"}},
{
          "id":"5ff2c99e31a848949f1b1d119eb1c6f6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "location":{
              "x":0,
              "y":231},
            "size":{
              "width":320,
              "height":51}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7e40dce7b2a48f8ba30c320bc708bfa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "location":{
                  "x":0,
                  "y":231},
                "size":{
                  "width":320,
                  "height":51}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/确认订单-双色球/u25.png"}},
{
          "id":"60fcee0b3ce742369a0a94776bb03752",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":180},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c3610a5f1704381b3234ebc1da43d48",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":180},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u262.png"}},
{
          "id":"ec29c28bbb13430dba6c1904b3fdf19a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":241},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad265c00df6b4859a2d3685b37b1efcb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":241},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u262.png"}},
{
          "id":"ae65c6fbe0f64b5a9ce2c8ee868f6bd9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":230,
              "y":186},
            "size":{
              "width":48,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af9566751fa6496d9967b8a17770116c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":230,
                  "y":186},
                "size":{
                  "width":48,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2532273d915c4b00b40f0a8250e0354a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "location":{
              "x":0,
              "y":292},
            "size":{
              "width":320,
              "height":51}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64dc81394d1c4333af2ff304b0df1c5e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "location":{
                  "x":0,
                  "y":292},
                "size":{
                  "width":320,
                  "height":51}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/确认订单-双色球/u25.png"}},
{
          "id":"b183a43464394cfdb23f542ab8328f38",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":302},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ba07f1a68cf4c8598bd666710fbaf88",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":302},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u262.png"}},
{
          "id":"6f657f823b7e4f01973f67b243f68d9c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "location":{
              "x":0,
              "y":353},
            "size":{
              "width":320,
              "height":51}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de3590e501ce495cb479189f3d6df93a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "location":{
                  "x":0,
                  "y":353},
                "size":{
                  "width":320,
                  "height":51}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/确认订单-双色球/u25.png"}},
{
          "id":"c7c9a33326dd4d09a41337cfec9db01b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":363},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba755e34977a4dbba1a85993e9f55bac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":363},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u262.png"}},
{
          "id":"4e6b8a774b0c40af91fd85d6bc422c88",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":25,
              "y":630},
            "size":{
              "width":270,
              "height":45}},
          "adaptiveStyles":{
}},
{
          "id":"4e2e25350637443bb04bb794a30a9be3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "location":{
              "x":245,
              "y":238},
            "size":{
              "width":35,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64eacc7f1e314640a27841c9c679e317",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "location":{
                  "x":245,
                  "y":238},
                "size":{
                  "width":35,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/店主中心/u40.png"}},
{
          "id":"3346dfbd48014ac39baf4f12ed9c139e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "location":{
              "x":245,
              "y":300},
            "size":{
              "width":35,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"08586cd3123f4476af2d2492cd32670f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "location":{
                  "x":245,
                  "y":300},
                "size":{
                  "width":35,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/店主中心/u40.png"}},
{
          "id":"59c14b12c759432e9137de727571a54d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "location":{
              "x":0,
              "y":414},
            "size":{
              "width":320,
              "height":51}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5dbe5a5d7a5f4ad9981eef55578cac51",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "location":{
                  "x":0,
                  "y":414},
                "size":{
                  "width":320,
                  "height":51}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/确认订单-双色球/u25.png"}},
{
          "id":"4782d34e42c140f183f16755ab53cb04",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":424},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8bb412fb390d42d5af367f50b7b1e5e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":424},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u262.png"}},
{
          "id":"c10fb8721a5442bcac3d370e84d7b505",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "location":{
              "x":0,
              "y":475},
            "size":{
              "width":320,
              "height":51}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"03bce6221cc1460bb56a5c50443d2dc2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "location":{
                  "x":0,
                  "y":475},
                "size":{
                  "width":320,
                  "height":51}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/确认订单-双色球/u25.png"}},
{
          "id":"d15ea48663d443ee882aef08c792971d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":485},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"51be8f633a034f4897c5c7b6cd70f438",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":485},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u262.png"}},
{
          "id":"b4a5a3251e6c4177b7a1f9a21ab271ac",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "location":{
              "x":0,
              "y":536},
            "size":{
              "width":320,
              "height":51}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6310f2b50ea34535a846e2f24a54827b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "location":{
                  "x":0,
                  "y":536},
                "size":{
                  "width":320,
                  "height":51}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/确认订单-双色球/u25.png"}},
{
          "id":"17e564536cf848b9b802ad238dd657ee",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":546},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f92a6cd6afb54625b90aa7cf910eb4bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":546},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u262.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "2ab24f8ebbee4de98ad21cbb8686479b":{
      "scriptId":"u0"},
    "e7ad8b2d40fa4389944635d2e427e1b6":{
      "scriptId":"u1"},
    "fdac3eb5757443d2a7983594cfa53e96":{
      "scriptId":"u2"},
    "9592d30c7a5149c1bc7a5d98143f4d88":{
      "scriptId":"u3"},
    "812f561c9e924533967aa5d36ad1a9df":{
      "scriptId":"u4"},
    "474fabfc587e4490b84e7cc6ddeeab79":{
      "scriptId":"u5"},
    "9938d3ce84ec4c3b83d2f3a6dcec0f6c":{
      "scriptId":"u6"},
    "a90ebf0079964dd9a9e66363bb1da9db":{
      "scriptId":"u7"},
    "0cab16aee17749adac24c2e1d5736cb0":{
      "scriptId":"u8"},
    "bf211944d2934e168354614c411d732d":{
      "scriptId":"u9"},
    "2740c4083df24f18a78dded43455db16":{
      "scriptId":"u10"},
    "7e3a5710a3f64d8ca38f57752443187d":{
      "scriptId":"u11"},
    "89b4d0a9d5c943ee9a4a0b3935c65dfd":{
      "scriptId":"u12"},
    "e42ff94912c84e6080e2db7deb5119ab":{
      "scriptId":"u13"},
    "9e3e4d809d914049ac335a47b57b0726":{
      "scriptId":"u14"},
    "9806c0a10010490091dc222b155b4976":{
      "scriptId":"u15"},
    "79bb53ffa70c4367a91ce77c3ec5e577":{
      "scriptId":"u16"},
    "da858e059d8f44b7a881664b7eaeb83e":{
      "scriptId":"u17"},
    "53bf309246ab4644858c8723e920aa70":{
      "scriptId":"u18"},
    "868b64a38c2a418c89ed4f5b5004862b":{
      "scriptId":"u19"},
    "f01742c48a25445d817461136f9ec76f":{
      "scriptId":"u20"},
    "eefd609b94b540aa8a18ae8e08dfd3fc":{
      "scriptId":"u21"},
    "cd59df19847b442c8846f72db6f87209":{
      "scriptId":"u22"},
    "5ff2c99e31a848949f1b1d119eb1c6f6":{
      "scriptId":"u23"},
    "b7e40dce7b2a48f8ba30c320bc708bfa":{
      "scriptId":"u24"},
    "60fcee0b3ce742369a0a94776bb03752":{
      "scriptId":"u25"},
    "7c3610a5f1704381b3234ebc1da43d48":{
      "scriptId":"u26"},
    "ec29c28bbb13430dba6c1904b3fdf19a":{
      "scriptId":"u27"},
    "ad265c00df6b4859a2d3685b37b1efcb":{
      "scriptId":"u28"},
    "ae65c6fbe0f64b5a9ce2c8ee868f6bd9":{
      "scriptId":"u29"},
    "af9566751fa6496d9967b8a17770116c":{
      "scriptId":"u30"},
    "2532273d915c4b00b40f0a8250e0354a":{
      "scriptId":"u31"},
    "64dc81394d1c4333af2ff304b0df1c5e":{
      "scriptId":"u32"},
    "b183a43464394cfdb23f542ab8328f38":{
      "scriptId":"u33"},
    "5ba07f1a68cf4c8598bd666710fbaf88":{
      "scriptId":"u34"},
    "6f657f823b7e4f01973f67b243f68d9c":{
      "scriptId":"u35"},
    "de3590e501ce495cb479189f3d6df93a":{
      "scriptId":"u36"},
    "c7c9a33326dd4d09a41337cfec9db01b":{
      "scriptId":"u37"},
    "ba755e34977a4dbba1a85993e9f55bac":{
      "scriptId":"u38"},
    "4e6b8a774b0c40af91fd85d6bc422c88":{
      "scriptId":"u39"},
    "4e2e25350637443bb04bb794a30a9be3":{
      "scriptId":"u40"},
    "64eacc7f1e314640a27841c9c679e317":{
      "scriptId":"u41"},
    "3346dfbd48014ac39baf4f12ed9c139e":{
      "scriptId":"u42"},
    "08586cd3123f4476af2d2492cd32670f":{
      "scriptId":"u43"},
    "59c14b12c759432e9137de727571a54d":{
      "scriptId":"u44"},
    "5dbe5a5d7a5f4ad9981eef55578cac51":{
      "scriptId":"u45"},
    "4782d34e42c140f183f16755ab53cb04":{
      "scriptId":"u46"},
    "8bb412fb390d42d5af367f50b7b1e5e5":{
      "scriptId":"u47"},
    "c10fb8721a5442bcac3d370e84d7b505":{
      "scriptId":"u48"},
    "03bce6221cc1460bb56a5c50443d2dc2":{
      "scriptId":"u49"},
    "d15ea48663d443ee882aef08c792971d":{
      "scriptId":"u50"},
    "51be8f633a034f4897c5c7b6cd70f438":{
      "scriptId":"u51"},
    "b4a5a3251e6c4177b7a1f9a21ab271ac":{
      "scriptId":"u52"},
    "6310f2b50ea34535a846e2f24a54827b":{
      "scriptId":"u53"},
    "17e564536cf848b9b802ad238dd657ee":{
      "scriptId":"u54"},
    "f92a6cd6afb54625b90aa7cf910eb4bb":{
      "scriptId":"u55"}}});