$axure.loadCurrentPage({
  "url":"支付成功.html",
  "generationDate":new Date(1496903828609.76),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"sfz",
"sfz_n"],
  "page":{
    "packageId":"5c777fa816464550b988c9939e1830a2",
    "type":"Axure:Page",
    "name":"支付成功",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"76331a6ebcd64681844ff63a19ded8aa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "size":{
              "width":320,
              "height":470},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d174536655cc42c28848944ced39570a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "size":{
                  "width":320,
                  "height":470},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付订单/u0.png"}},
{
          "id":"dcd2e885899c4b64a0da067e6fc4b1a1",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "fixedHorizontal":"left",
          "fixedMarginHorizontal":0,
          "fixedVertical":"top",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"217c80bdf3a04eec86b3f69ec0c705e0",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"6a3ab268a7a8413c9353ef5d78f7e0ad",
                  "label":"",
                  "parentDynamicPanel":"dcd2e885899c4b64a0da067e6fc4b1a1",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF1C222E},
                    "size":{
                      "width":320,
                      "height":64},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"557ffb84340d4b0489c68330098154fd",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"dcd2e885899c4b64a0da067e6fc4b1a1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF1C222E},
                        "size":{
                          "width":320,
                          "height":64},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u3.png"}},
{
                  "id":"ced1379508514cfc9e26d477995eff73",
                  "label":"",
                  "parentDynamicPanel":"dcd2e885899c4b64a0da067e6fc4b1a1",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Heiti SC Regular', 'Heiti SC'",
                    "fontSize":"18px",
                    "fontWeight":"200",
                    "horizontalAlignment":"center",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":78,
                      "y":35},
                    "size":{
                      "width":163,
                      "height":22},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ead23169eeb7440fb6be66a6906a74c5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"dcd2e885899c4b64a0da067e6fc4b1a1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Heiti SC Regular', 'Heiti SC'",
                        "fontSize":"18px",
                        "fontWeight":"200",
                        "horizontalAlignment":"center",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":78,
                          "y":35},
                        "size":{
                          "width":163,
                          "height":22},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"2a1a72c44c5942498d71e931a7d4b453",
                  "label":"",
                  "parentDynamicPanel":"dcd2e885899c4b64a0da067e6fc4b1a1",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":320,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4ee5bcd24aa54632a44b4a006a4cadbd",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"dcd2e885899c4b64a0da067e6fc4b1a1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":320,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u7.png"}},
{
                  "id":"ffbfe1df980a4673b3b3124f123e38ea",
                  "label":"",
                  "parentDynamicPanel":"dcd2e885899c4b64a0da067e6fc4b1a1",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Heiti SC Regular', 'Heiti SC'",
                    "fontSize":"16px",
                    "fontWeight":"200",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":27,
                      "y":36},
                    "size":{
                      "width":63,
                      "height":19},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"79a2290d3ad248bc94844359de8e759f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"dcd2e885899c4b64a0da067e6fc4b1a1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Heiti SC Regular', 'Heiti SC'",
                        "fontSize":"16px",
                        "fontWeight":"200",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":27,
                          "y":36},
                        "size":{
                          "width":63,
                          "height":19},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"60739d5ecc1d488491060b5ab31ebe60",
                  "label":"",
                  "parentDynamicPanel":"dcd2e885899c4b64a0da067e6fc4b1a1",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Lucida Grande Regular', 'Lucida Grande'",
                    "fontSize":"20px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":9,
                      "y":31},
                    "size":{
                      "width":22,
                      "height":29}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b23058ade3fc4620825dfc830f25ae95",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"dcd2e885899c4b64a0da067e6fc4b1a1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Lucida Grande Regular', 'Lucida Grande'",
                        "fontSize":"20px",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":9,
                          "y":31},
                        "size":{
                          "width":22,
                          "height":29}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"15692424277a41bfb4cbe9c2b163ea12",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":100},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"651c990be58f43049ac6d2a727c1b5cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":100},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付成功/u13.png"}},
{
          "id":"90fe96272ec54e0abdf07d50634f0906",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":39.5,
              "y":221},
            "size":{
              "width":241,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"346e8c41b0694acfbbe77600c14c2c4d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":39.5,
                  "y":221},
                "size":{
                  "width":241,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fe1879093d45456496b667ba877b2d47",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":90,
              "y":300},
            "size":{
              "width":141,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c77dfd2d723427fb92ba966bdad382d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":90,
                  "y":300},
                "size":{
                  "width":141,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5b205558ce194e66893f6c81c71bfe47",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":10,
              "y":350},
            "size":{
              "width":61,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"68631b9a5a8f4dfbb721f368d60171f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":10,
                  "y":350},
                "size":{
                  "width":61,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付成功/u19.png"}},
{
          "id":"55f91378726a4bf791d5dd519c92cedf",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":280},
            "size":{
              "width":320,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/支付成功/u21_line.png"}},
{
          "id":"a9741df5651c4d4abd731bc1ad9c2650",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":90,
              "y":350},
            "size":{
              "width":61,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ab5682f054945eaa075fea375d4cd60",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":90,
                  "y":350},
                "size":{
                  "width":61,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付成功/u19.png"}},
{
          "id":"7731e75b610d498ca9dce866c44c8431",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":170,
              "y":350},
            "size":{
              "width":61,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c26c4d81e274473953378a02708d46a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":170,
                  "y":350},
                "size":{
                  "width":61,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付成功/u19.png"}},
{
          "id":"c4947e6c1a524acf923cfc2d4fcfe76b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":249,
              "y":350},
            "size":{
              "width":61,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0787506a1209479e9ecc3a4258f4d0b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":249,
                  "y":350},
                "size":{
                  "width":61,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付成功/u19.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "76331a6ebcd64681844ff63a19ded8aa":{
      "scriptId":"u0"},
    "d174536655cc42c28848944ced39570a":{
      "scriptId":"u1"},
    "dcd2e885899c4b64a0da067e6fc4b1a1":{
      "scriptId":"u2"},
    "6a3ab268a7a8413c9353ef5d78f7e0ad":{
      "scriptId":"u3"},
    "557ffb84340d4b0489c68330098154fd":{
      "scriptId":"u4"},
    "ced1379508514cfc9e26d477995eff73":{
      "scriptId":"u5"},
    "ead23169eeb7440fb6be66a6906a74c5":{
      "scriptId":"u6"},
    "2a1a72c44c5942498d71e931a7d4b453":{
      "scriptId":"u7"},
    "4ee5bcd24aa54632a44b4a006a4cadbd":{
      "scriptId":"u8"},
    "ffbfe1df980a4673b3b3124f123e38ea":{
      "scriptId":"u9"},
    "79a2290d3ad248bc94844359de8e759f":{
      "scriptId":"u10"},
    "60739d5ecc1d488491060b5ab31ebe60":{
      "scriptId":"u11"},
    "b23058ade3fc4620825dfc830f25ae95":{
      "scriptId":"u12"},
    "15692424277a41bfb4cbe9c2b163ea12":{
      "scriptId":"u13"},
    "651c990be58f43049ac6d2a727c1b5cd":{
      "scriptId":"u14"},
    "90fe96272ec54e0abdf07d50634f0906":{
      "scriptId":"u15"},
    "346e8c41b0694acfbbe77600c14c2c4d":{
      "scriptId":"u16"},
    "fe1879093d45456496b667ba877b2d47":{
      "scriptId":"u17"},
    "6c77dfd2d723427fb92ba966bdad382d":{
      "scriptId":"u18"},
    "5b205558ce194e66893f6c81c71bfe47":{
      "scriptId":"u19"},
    "68631b9a5a8f4dfbb721f368d60171f2":{
      "scriptId":"u20"},
    "55f91378726a4bf791d5dd519c92cedf":{
      "scriptId":"u21"},
    "a9741df5651c4d4abd731bc1ad9c2650":{
      "scriptId":"u22"},
    "0ab5682f054945eaa075fea375d4cd60":{
      "scriptId":"u23"},
    "7731e75b610d498ca9dce866c44c8431":{
      "scriptId":"u24"},
    "8c26c4d81e274473953378a02708d46a":{
      "scriptId":"u25"},
    "c4947e6c1a524acf923cfc2d4fcfe76b":{
      "scriptId":"u26"},
    "0787506a1209479e9ecc3a4258f4d0b7":{
      "scriptId":"u27"}}});