$axure.loadCurrentPage({
  "url":"选择彩票店.html",
  "generationDate":new Date(1496903819970.76),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"sfz",
"sfz_n"],
  "page":{
    "packageId":"fdaa29a703e34515ac291c8e30556e2f",
    "type":"Axure:Page",
    "name":"选择彩票店",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7a4cc34948104fb09f3c45417ef81c24",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "size":{
              "width":320,
              "height":600},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cac992caa8484e2989fd3e5b236055ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "size":{
                  "width":320,
                  "height":600},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择彩票店/u0.png"}},
{
          "id":"f51e7c47a12f479ab86b3c00aca69862",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "fixedHorizontal":"left",
          "fixedMarginHorizontal":0,
          "fixedVertical":"top",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"37d43719d7c24751a0e6aef060762eab",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"fceab7c049c8442ebb71c5be4a5314f3",
                  "label":"",
                  "parentDynamicPanel":"f51e7c47a12f479ab86b3c00aca69862",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF1C222E},
                    "size":{
                      "width":320,
                      "height":64},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7637def569634697a707f311e621283c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f51e7c47a12f479ab86b3c00aca69862",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF1C222E},
                        "size":{
                          "width":320,
                          "height":64},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u3.png"}},
{
                  "id":"c61985ebf9c14412a9c7ee3adaa9e24a",
                  "label":"",
                  "parentDynamicPanel":"f51e7c47a12f479ab86b3c00aca69862",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Heiti SC Regular', 'Heiti SC'",
                    "fontSize":"18px",
                    "fontWeight":"200",
                    "horizontalAlignment":"center",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":78,
                      "y":35},
                    "size":{
                      "width":163,
                      "height":22},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"38bf1f43a8f5444a82ccaafdd4ef912a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f51e7c47a12f479ab86b3c00aca69862",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Heiti SC Regular', 'Heiti SC'",
                        "fontSize":"18px",
                        "fontWeight":"200",
                        "horizontalAlignment":"center",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":78,
                          "y":35},
                        "size":{
                          "width":163,
                          "height":22},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"bb67431e2e8840b2982ec8faccec0af4",
                  "label":"",
                  "parentDynamicPanel":"f51e7c47a12f479ab86b3c00aca69862",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":320,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"929773c19243442d8aa1d7d20f008f79",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f51e7c47a12f479ab86b3c00aca69862",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":320,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u7.png"}},
{
                  "id":"6bd7cf8e2d1a40b4a5284869b492d72a",
                  "label":"",
                  "parentDynamicPanel":"f51e7c47a12f479ab86b3c00aca69862",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Heiti SC Regular', 'Heiti SC'",
                    "fontSize":"16px",
                    "fontWeight":"200",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":27,
                      "y":36},
                    "size":{
                      "width":63,
                      "height":19},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fca4dd5bf05a4b0db71064ea49330f5d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f51e7c47a12f479ab86b3c00aca69862",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Heiti SC Regular', 'Heiti SC'",
                        "fontSize":"16px",
                        "fontWeight":"200",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":27,
                          "y":36},
                        "size":{
                          "width":63,
                          "height":19},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"cff799a79ecd424a89effbf4f31a8420",
                  "label":"",
                  "parentDynamicPanel":"f51e7c47a12f479ab86b3c00aca69862",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Lucida Grande Regular', 'Lucida Grande'",
                    "fontSize":"20px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":9,
                      "y":31},
                    "size":{
                      "width":22,
                      "height":29}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"76a093b0aa0c4ec5b57469779be7b47b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f51e7c47a12f479ab86b3c00aca69862",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Lucida Grande Regular', 'Lucida Grande'",
                        "fontSize":"20px",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":9,
                          "y":31},
                        "size":{
                          "width":22,
                          "height":29}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"d875e9f9229f42fab85a8f8697c60f2f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":0,
              "y":69},
            "size":{
              "width":320,
              "height":157},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"628b36f175084e86b98806255a868c73",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":0,
                  "y":69},
                "size":{
                  "width":320,
                  "height":157},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u21.png"}},
{
          "id":"19ea0a40f81a403693b9892723d868f0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":4,
              "y":84},
            "size":{
              "width":89,
              "height":84}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b1939e4629c48acbe361e01df3a5ad2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":4,
                  "y":84},
                "size":{
                  "width":89,
                  "height":84}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u23.png"}},
{
          "id":"1040e9cf250c407fa6f5a5de22cc0baf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "location":{
              "x":99,
              "y":79},
            "size":{
              "width":201,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"644f68fa9827430285e8fac11d733cf8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "location":{
                  "x":99,
                  "y":79},
                "size":{
                  "width":201,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"57603fffa6fd4b6d8131d9fb0fb63aaf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF009DD9},
            "location":{
              "x":250,
              "y":77},
            "size":{
              "width":60,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"17e102e6b6d24e05b3c133eaf940d011",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009DD9},
                "location":{
                  "x":250,
                  "y":77},
                "size":{
                  "width":60,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u27.png"}},
{
          "id":"bb1e631d56904d4f825da329783f2f04",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":180},
            "size":{
              "width":320,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页/u29_line.png"}},
{
          "id":"8843c808723b46609126227e1f8504f4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":129,
              "y":104},
            "size":{
              "width":37,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c03d9a6cd7b41298c8d5595e1159dee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":129,
                  "y":104},
                "size":{
                  "width":37,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0e8fa7b5e7a94d67855302b3daf41037",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":99,
              "y":102},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e5396e354bf642a7a3cffc64585758dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":99,
                  "y":102},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u51.png"}},
{
          "id":"eb174cf3bd224fe3918480c662027f45",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":99,
              "y":126},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a2a2a359d5c49f9926682b99e1727ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":99,
                  "y":126},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u53.png"}},
{
          "id":"333a9f834480409bb498d8d81bbada9e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":99,
              "y":152},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac44368d213c457b999ec5eaf1ec60e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":99,
                  "y":152},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u55.png"}},
{
          "id":"4439025187534254aafb6d0a6c62af95",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":129,
              "y":126},
            "size":{
              "width":181,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b83a92cdcb047edb1d949343325b827",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":129,
                  "y":126},
                "size":{
                  "width":181,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f2c626013ece4268bdae37ba06d14192",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":129,
              "y":152},
            "size":{
              "width":113,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc10c2c4d2524be2a9a520e181bb2c52",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":129,
                  "y":152},
                "size":{
                  "width":113,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7ddc38cd869b4340a90f595e8dde8a39",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":275.5,
              "y":118.5},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28f6d571ac084d6e94f9ea49d5e835b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":275.5,
                  "y":118.5},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u262.png"}},
{
          "id":"9844e4a455c64d08a703c0e067a1e9f9",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":10,
              "y":198},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"15200915f8b34083a0f5c0f9345cb511",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":10,
                  "y":198},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"edbf7dbbddbb4a89955315dddda59d28",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":230,
              "y":190},
            "size":{
              "width":76,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1450c198fc9b4d35ad00bc44841140b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":230,
                  "y":190},
                "size":{
                  "width":76,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择彩票店/u38.png"}},
{
          "id":"b2ddd0086b6c46679d8e8915da04a67c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":0,
              "y":232},
            "size":{
              "width":320,
              "height":157},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"34e57dee2f7b437e9728810323b91023",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":0,
                  "y":232},
                "size":{
                  "width":320,
                  "height":157},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u21.png"}},
{
          "id":"9663360435b04551bff25fb64a49cdf1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":4,
              "y":247},
            "size":{
              "width":89,
              "height":84}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"13a6b99bc418444899a4d6ff1cbd6c84",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":4,
                  "y":247},
                "size":{
                  "width":89,
                  "height":84}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u23.png"}},
{
          "id":"9e88af31da3748cb80453698be0e7054",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "location":{
              "x":99,
              "y":242},
            "size":{
              "width":201,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4d92c6714b245cf93147f88d584c818",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "location":{
                  "x":99,
                  "y":242},
                "size":{
                  "width":201,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f43ad3654e8f401bad8cc7bad03f6b31",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF009DD9},
            "location":{
              "x":250,
              "y":240},
            "size":{
              "width":60,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f045038be78c428689ae74171812b699",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009DD9},
                "location":{
                  "x":250,
                  "y":240},
                "size":{
                  "width":60,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u27.png"}},
{
          "id":"b5a720377e1440208b6d5c041699085e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":343},
            "size":{
              "width":320,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页/u29_line.png"}},
{
          "id":"37fb151182af4102a50a56de628c41b6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":129,
              "y":267},
            "size":{
              "width":37,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9818741b225b43e9adb3ffe73bf3ad2b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":129,
                  "y":267},
                "size":{
                  "width":37,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2760125ffd0d48a4ad0e3e34f14b0d48",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":99,
              "y":265},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a011c6074ad84e7f9c00129358862145",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":99,
                  "y":265},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u51.png"}},
{
          "id":"c9256ad5d3a04a139a0d2fd4f2a69c49",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":99,
              "y":289},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"32ba8089333845e580962e24c42b71d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":99,
                  "y":289},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u53.png"}},
{
          "id":"e2fe66d5f2bc4adc829eeecfc67223a0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":99,
              "y":315},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e17a89a56dc8411ebe2ea35daf3e6ac5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":99,
                  "y":315},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u55.png"}},
{
          "id":"6a3c6889777c40cfb6de87e0f9db8708",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":129,
              "y":289},
            "size":{
              "width":181,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b4e2d4e5e514855b94d1e5f7f7e30f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":129,
                  "y":289},
                "size":{
                  "width":181,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f4e7ccfc3677420bbf2b5edb84d89e0a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":129,
              "y":315},
            "size":{
              "width":113,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"590f46a9a62a4dd1bc2e4ccb0e11daf5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":129,
                  "y":315},
                "size":{
                  "width":113,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"65191ec406de4ef8a2d1ca7bd24fe9ff",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":276,
              "y":281},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"593ea5075a824fee916e9a37cc6cf811",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":276,
                  "y":281},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u262.png"}},
{
          "id":"d05740cd8cef4e948d754b4ebd427c6a",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":10,
              "y":361},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da9b5ad776404417a0abd80fef8ca2c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":10,
                  "y":361},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"d0c5e695e3d243e980d51d1b5932e158",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":230,
              "y":353},
            "size":{
              "width":76,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6904e351502e4dc8a10a0eb82edd11a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":230,
                  "y":353},
                "size":{
                  "width":76,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择彩票店/u38.png"}},
{
          "id":"5a6781c0b8c947399616c5ffbfee1356",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":0,
              "y":396},
            "size":{
              "width":320,
              "height":157},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b90173863ff4dd9952dbfd08b5f3c9b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":0,
                  "y":396},
                "size":{
                  "width":320,
                  "height":157},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u21.png"}},
{
          "id":"df8124eae4d441ab8aabc910d528a7bd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":4,
              "y":411},
            "size":{
              "width":89,
              "height":84}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"181655c5a6c44311bc171b895cf20656",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":4,
                  "y":411},
                "size":{
                  "width":89,
                  "height":84}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u23.png"}},
{
          "id":"52c6199e4a45478eb73daff2621a094d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "location":{
              "x":99,
              "y":406},
            "size":{
              "width":201,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98912862342c4bc7ae0669662c867a78",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "location":{
                  "x":99,
                  "y":406},
                "size":{
                  "width":201,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"100d5ea927474f8bb4f4e6673a66420d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF009DD9},
            "location":{
              "x":250,
              "y":404},
            "size":{
              "width":60,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9638a857b61342e8a030f8bfe2b38818",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009DD9},
                "location":{
                  "x":250,
                  "y":404},
                "size":{
                  "width":60,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u27.png"}},
{
          "id":"913066f2417a4d0cad1d8c2f406052e6",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":507},
            "size":{
              "width":320,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页/u29_line.png"}},
{
          "id":"a63d687cfaee4aca9ec9f7bfc8c748f6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":129,
              "y":431},
            "size":{
              "width":37,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"436c4002a4d04fbc9ce5890c1e66253c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":129,
                  "y":431},
                "size":{
                  "width":37,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"81fc4f6118ae41ee9bd1847cfbbcab62",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":99,
              "y":429},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"213175200e0d434093db636b0b43dbd8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":99,
                  "y":429},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u51.png"}},
{
          "id":"9778f7dc76bf42f48367f9b30277c6cf",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":99,
              "y":453},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41d4794647e549499ad3b4aabb757559",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":99,
                  "y":453},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u53.png"}},
{
          "id":"97e19a543ee247619d04ed973ceca434",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":99,
              "y":479},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e3f8f9e3631049719dcf0f776d848439",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":99,
                  "y":479},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u55.png"}},
{
          "id":"2311bae8d53f481d878890e37aa89559",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":129,
              "y":453},
            "size":{
              "width":181,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"18b098dbbdec4a5894b2227549ed977e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":129,
                  "y":453},
                "size":{
                  "width":181,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"88ea424ff5504de1b3bee0c9d3cea2b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":129,
              "y":479},
            "size":{
              "width":113,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aaade782c7884edfabbf7d25e7e6d0a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":129,
                  "y":479},
                "size":{
                  "width":113,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ada3cfe29ed042c68f5c9435631f13f9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":276,
              "y":445},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1318fb7b2e0340f08a4c775a405bc33e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":276,
                  "y":445},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u262.png"}},
{
          "id":"371dc7dae402448dae817cf3ba3c5210",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":10,
              "y":525},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7827178e05024f2a8565e101e9e4536a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":10,
                  "y":525},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"f6ec45a5cc294d10a9069f499eedc57c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":230,
              "y":517},
            "size":{
              "width":76,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"403d6eea11144ac9a3f8208934960f99",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":230,
                  "y":517},
                "size":{
                  "width":76,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择彩票店/u38.png"}},
{
          "id":"eaf12a04ceac4793be17d8111f760f20",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":98,
              "y":569},
            "size":{
              "width":139,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6a73f55e29b6401dade01d8dc28d3a7d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":98,
                  "y":569},
                "size":{
                  "width":139,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2aa70292431d47b79252a43c5955d8cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":340,
              "y":0},
            "size":{
              "width":320,
              "height":600},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"86b7d5ef782b4991bba17d9069641b67",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":340,
                  "y":0},
                "size":{
                  "width":320,
                  "height":600},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择彩票店/u0.png"}},
{
          "id":"31e0b3b7e63044e5bc20ae3c47320c4d",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":340,
              "y":0},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "fixedHorizontal":"left",
          "fixedMarginHorizontal":340,
          "fixedVertical":"top",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"9a95d1a8230e4ac6b093a64596d98906",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"bc99af2b2372404b908c992578fd9439",
                  "label":"",
                  "parentDynamicPanel":"31e0b3b7e63044e5bc20ae3c47320c4d",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF1C222E},
                    "size":{
                      "width":320,
                      "height":64},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fd4b9dc2014f48119eb5b3565182bf7a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31e0b3b7e63044e5bc20ae3c47320c4d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF1C222E},
                        "size":{
                          "width":320,
                          "height":64},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u3.png"}},
{
                  "id":"a8e857d228bc4e0b9a9d419f462f00e7",
                  "label":"",
                  "parentDynamicPanel":"31e0b3b7e63044e5bc20ae3c47320c4d",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Heiti SC Regular', 'Heiti SC'",
                    "fontSize":"18px",
                    "fontWeight":"200",
                    "horizontalAlignment":"center",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":78,
                      "y":35},
                    "size":{
                      "width":163,
                      "height":22},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a0685ba8773b4282928481dda46961d9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31e0b3b7e63044e5bc20ae3c47320c4d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Heiti SC Regular', 'Heiti SC'",
                        "fontSize":"18px",
                        "fontWeight":"200",
                        "horizontalAlignment":"center",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":78,
                          "y":35},
                        "size":{
                          "width":163,
                          "height":22},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"bdb9db71502d429db1f2a29b835e3025",
                  "label":"",
                  "parentDynamicPanel":"31e0b3b7e63044e5bc20ae3c47320c4d",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":320,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"658627f64705469188dd742ba8847265",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31e0b3b7e63044e5bc20ae3c47320c4d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":320,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u7.png"}},
{
                  "id":"95b6677ef76148dfbe51a6b12afdf281",
                  "label":"",
                  "parentDynamicPanel":"31e0b3b7e63044e5bc20ae3c47320c4d",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Heiti SC Regular', 'Heiti SC'",
                    "fontSize":"16px",
                    "fontWeight":"200",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":27,
                      "y":36},
                    "size":{
                      "width":63,
                      "height":19},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"aa69a069ab2f4fa18b241ede86827a8f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31e0b3b7e63044e5bc20ae3c47320c4d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Heiti SC Regular', 'Heiti SC'",
                        "fontSize":"16px",
                        "fontWeight":"200",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":27,
                          "y":36},
                        "size":{
                          "width":63,
                          "height":19},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"0fb397b186b74b15a321e2b23a3e270a",
                  "label":"",
                  "parentDynamicPanel":"31e0b3b7e63044e5bc20ae3c47320c4d",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Lucida Grande Regular', 'Lucida Grande'",
                    "fontSize":"20px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":9,
                      "y":31},
                    "size":{
                      "width":22,
                      "height":29}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b8a5847fc56b4d149bff304f87d6a085",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31e0b3b7e63044e5bc20ae3c47320c4d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Lucida Grande Regular', 'Lucida Grande'",
                        "fontSize":"20px",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":9,
                          "y":31},
                        "size":{
                          "width":22,
                          "height":29}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"54004fbc83d647c7a0c8d3d49c084e1b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":379.5,
              "y":281},
            "size":{
              "width":241,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed9b3dbf26154b63a1368256ed1e4d97",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":379.5,
                  "y":281},
                "size":{
                  "width":241,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5bae2ab4a3fc4801a2bfb4eaf5413924",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":668},
            "size":{
              "width":230,
              "height":122},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"7"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"acc9dce1e7d44dfba177d5dc57b8db8e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":668},
                "size":{
                  "width":230,
                  "height":122},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"7"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u242.png"}},
{
          "id":"96d4c439a45d4573b474c5f997d60bd5",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":745},
            "size":{
              "width":230,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页/u244_line.png"}},
{
          "id":"4f19907a52004323a3c518c0a189d6be",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":110,
              "y":755},
            "size":{
              "width":90,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d1a26c445614234871af9a7fe98732a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":110,
                  "y":755},
                "size":{
                  "width":90,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u246.png"}},
{
          "id":"6df662f3f5434d8fb17897ff8973648c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "location":{
              "x":61.5,
              "y":678},
            "size":{
              "width":187,
              "height":57}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a4e2199ca884a65a1a4473034137404",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "location":{
                  "x":61.5,
                  "y":678},
                "size":{
                  "width":187,
                  "height":57}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "7a4cc34948104fb09f3c45417ef81c24":{
      "scriptId":"u0"},
    "cac992caa8484e2989fd3e5b236055ad":{
      "scriptId":"u1"},
    "f51e7c47a12f479ab86b3c00aca69862":{
      "scriptId":"u2"},
    "fceab7c049c8442ebb71c5be4a5314f3":{
      "scriptId":"u3"},
    "7637def569634697a707f311e621283c":{
      "scriptId":"u4"},
    "c61985ebf9c14412a9c7ee3adaa9e24a":{
      "scriptId":"u5"},
    "38bf1f43a8f5444a82ccaafdd4ef912a":{
      "scriptId":"u6"},
    "bb67431e2e8840b2982ec8faccec0af4":{
      "scriptId":"u7"},
    "929773c19243442d8aa1d7d20f008f79":{
      "scriptId":"u8"},
    "6bd7cf8e2d1a40b4a5284869b492d72a":{
      "scriptId":"u9"},
    "fca4dd5bf05a4b0db71064ea49330f5d":{
      "scriptId":"u10"},
    "cff799a79ecd424a89effbf4f31a8420":{
      "scriptId":"u11"},
    "76a093b0aa0c4ec5b57469779be7b47b":{
      "scriptId":"u12"},
    "d875e9f9229f42fab85a8f8697c60f2f":{
      "scriptId":"u13"},
    "628b36f175084e86b98806255a868c73":{
      "scriptId":"u14"},
    "19ea0a40f81a403693b9892723d868f0":{
      "scriptId":"u15"},
    "8b1939e4629c48acbe361e01df3a5ad2":{
      "scriptId":"u16"},
    "1040e9cf250c407fa6f5a5de22cc0baf":{
      "scriptId":"u17"},
    "644f68fa9827430285e8fac11d733cf8":{
      "scriptId":"u18"},
    "57603fffa6fd4b6d8131d9fb0fb63aaf":{
      "scriptId":"u19"},
    "17e102e6b6d24e05b3c133eaf940d011":{
      "scriptId":"u20"},
    "bb1e631d56904d4f825da329783f2f04":{
      "scriptId":"u21"},
    "8843c808723b46609126227e1f8504f4":{
      "scriptId":"u22"},
    "4c03d9a6cd7b41298c8d5595e1159dee":{
      "scriptId":"u23"},
    "0e8fa7b5e7a94d67855302b3daf41037":{
      "scriptId":"u24"},
    "e5396e354bf642a7a3cffc64585758dc":{
      "scriptId":"u25"},
    "eb174cf3bd224fe3918480c662027f45":{
      "scriptId":"u26"},
    "0a2a2a359d5c49f9926682b99e1727ab":{
      "scriptId":"u27"},
    "333a9f834480409bb498d8d81bbada9e":{
      "scriptId":"u28"},
    "ac44368d213c457b999ec5eaf1ec60e1":{
      "scriptId":"u29"},
    "4439025187534254aafb6d0a6c62af95":{
      "scriptId":"u30"},
    "4b83a92cdcb047edb1d949343325b827":{
      "scriptId":"u31"},
    "f2c626013ece4268bdae37ba06d14192":{
      "scriptId":"u32"},
    "bc10c2c4d2524be2a9a520e181bb2c52":{
      "scriptId":"u33"},
    "7ddc38cd869b4340a90f595e8dde8a39":{
      "scriptId":"u34"},
    "28f6d571ac084d6e94f9ea49d5e835b7":{
      "scriptId":"u35"},
    "9844e4a455c64d08a703c0e067a1e9f9":{
      "scriptId":"u36"},
    "15200915f8b34083a0f5c0f9345cb511":{
      "scriptId":"u37"},
    "edbf7dbbddbb4a89955315dddda59d28":{
      "scriptId":"u38"},
    "1450c198fc9b4d35ad00bc44841140b2":{
      "scriptId":"u39"},
    "b2ddd0086b6c46679d8e8915da04a67c":{
      "scriptId":"u40"},
    "34e57dee2f7b437e9728810323b91023":{
      "scriptId":"u41"},
    "9663360435b04551bff25fb64a49cdf1":{
      "scriptId":"u42"},
    "13a6b99bc418444899a4d6ff1cbd6c84":{
      "scriptId":"u43"},
    "9e88af31da3748cb80453698be0e7054":{
      "scriptId":"u44"},
    "e4d92c6714b245cf93147f88d584c818":{
      "scriptId":"u45"},
    "f43ad3654e8f401bad8cc7bad03f6b31":{
      "scriptId":"u46"},
    "f045038be78c428689ae74171812b699":{
      "scriptId":"u47"},
    "b5a720377e1440208b6d5c041699085e":{
      "scriptId":"u48"},
    "37fb151182af4102a50a56de628c41b6":{
      "scriptId":"u49"},
    "9818741b225b43e9adb3ffe73bf3ad2b":{
      "scriptId":"u50"},
    "2760125ffd0d48a4ad0e3e34f14b0d48":{
      "scriptId":"u51"},
    "a011c6074ad84e7f9c00129358862145":{
      "scriptId":"u52"},
    "c9256ad5d3a04a139a0d2fd4f2a69c49":{
      "scriptId":"u53"},
    "32ba8089333845e580962e24c42b71d9":{
      "scriptId":"u54"},
    "e2fe66d5f2bc4adc829eeecfc67223a0":{
      "scriptId":"u55"},
    "e17a89a56dc8411ebe2ea35daf3e6ac5":{
      "scriptId":"u56"},
    "6a3c6889777c40cfb6de87e0f9db8708":{
      "scriptId":"u57"},
    "4b4e2d4e5e514855b94d1e5f7f7e30f2":{
      "scriptId":"u58"},
    "f4e7ccfc3677420bbf2b5edb84d89e0a":{
      "scriptId":"u59"},
    "590f46a9a62a4dd1bc2e4ccb0e11daf5":{
      "scriptId":"u60"},
    "65191ec406de4ef8a2d1ca7bd24fe9ff":{
      "scriptId":"u61"},
    "593ea5075a824fee916e9a37cc6cf811":{
      "scriptId":"u62"},
    "d05740cd8cef4e948d754b4ebd427c6a":{
      "scriptId":"u63"},
    "da9b5ad776404417a0abd80fef8ca2c3":{
      "scriptId":"u64"},
    "d0c5e695e3d243e980d51d1b5932e158":{
      "scriptId":"u65"},
    "6904e351502e4dc8a10a0eb82edd11a8":{
      "scriptId":"u66"},
    "5a6781c0b8c947399616c5ffbfee1356":{
      "scriptId":"u67"},
    "4b90173863ff4dd9952dbfd08b5f3c9b":{
      "scriptId":"u68"},
    "df8124eae4d441ab8aabc910d528a7bd":{
      "scriptId":"u69"},
    "181655c5a6c44311bc171b895cf20656":{
      "scriptId":"u70"},
    "52c6199e4a45478eb73daff2621a094d":{
      "scriptId":"u71"},
    "98912862342c4bc7ae0669662c867a78":{
      "scriptId":"u72"},
    "100d5ea927474f8bb4f4e6673a66420d":{
      "scriptId":"u73"},
    "9638a857b61342e8a030f8bfe2b38818":{
      "scriptId":"u74"},
    "913066f2417a4d0cad1d8c2f406052e6":{
      "scriptId":"u75"},
    "a63d687cfaee4aca9ec9f7bfc8c748f6":{
      "scriptId":"u76"},
    "436c4002a4d04fbc9ce5890c1e66253c":{
      "scriptId":"u77"},
    "81fc4f6118ae41ee9bd1847cfbbcab62":{
      "scriptId":"u78"},
    "213175200e0d434093db636b0b43dbd8":{
      "scriptId":"u79"},
    "9778f7dc76bf42f48367f9b30277c6cf":{
      "scriptId":"u80"},
    "41d4794647e549499ad3b4aabb757559":{
      "scriptId":"u81"},
    "97e19a543ee247619d04ed973ceca434":{
      "scriptId":"u82"},
    "e3f8f9e3631049719dcf0f776d848439":{
      "scriptId":"u83"},
    "2311bae8d53f481d878890e37aa89559":{
      "scriptId":"u84"},
    "18b098dbbdec4a5894b2227549ed977e":{
      "scriptId":"u85"},
    "88ea424ff5504de1b3bee0c9d3cea2b3":{
      "scriptId":"u86"},
    "aaade782c7884edfabbf7d25e7e6d0a8":{
      "scriptId":"u87"},
    "ada3cfe29ed042c68f5c9435631f13f9":{
      "scriptId":"u88"},
    "1318fb7b2e0340f08a4c775a405bc33e":{
      "scriptId":"u89"},
    "371dc7dae402448dae817cf3ba3c5210":{
      "scriptId":"u90"},
    "7827178e05024f2a8565e101e9e4536a":{
      "scriptId":"u91"},
    "f6ec45a5cc294d10a9069f499eedc57c":{
      "scriptId":"u92"},
    "403d6eea11144ac9a3f8208934960f99":{
      "scriptId":"u93"},
    "eaf12a04ceac4793be17d8111f760f20":{
      "scriptId":"u94"},
    "6a73f55e29b6401dade01d8dc28d3a7d":{
      "scriptId":"u95"},
    "2aa70292431d47b79252a43c5955d8cf":{
      "scriptId":"u96"},
    "86b7d5ef782b4991bba17d9069641b67":{
      "scriptId":"u97"},
    "31e0b3b7e63044e5bc20ae3c47320c4d":{
      "scriptId":"u98"},
    "bc99af2b2372404b908c992578fd9439":{
      "scriptId":"u99"},
    "fd4b9dc2014f48119eb5b3565182bf7a":{
      "scriptId":"u100"},
    "a8e857d228bc4e0b9a9d419f462f00e7":{
      "scriptId":"u101"},
    "a0685ba8773b4282928481dda46961d9":{
      "scriptId":"u102"},
    "bdb9db71502d429db1f2a29b835e3025":{
      "scriptId":"u103"},
    "658627f64705469188dd742ba8847265":{
      "scriptId":"u104"},
    "95b6677ef76148dfbe51a6b12afdf281":{
      "scriptId":"u105"},
    "aa69a069ab2f4fa18b241ede86827a8f":{
      "scriptId":"u106"},
    "0fb397b186b74b15a321e2b23a3e270a":{
      "scriptId":"u107"},
    "b8a5847fc56b4d149bff304f87d6a085":{
      "scriptId":"u108"},
    "54004fbc83d647c7a0c8d3d49c084e1b":{
      "scriptId":"u109"},
    "ed9b3dbf26154b63a1368256ed1e4d97":{
      "scriptId":"u110"},
    "5bae2ab4a3fc4801a2bfb4eaf5413924":{
      "scriptId":"u111"},
    "acc9dce1e7d44dfba177d5dc57b8db8e":{
      "scriptId":"u112"},
    "96d4c439a45d4573b474c5f997d60bd5":{
      "scriptId":"u113"},
    "4f19907a52004323a3c518c0a189d6be":{
      "scriptId":"u114"},
    "9d1a26c445614234871af9a7fe98732a":{
      "scriptId":"u115"},
    "6df662f3f5434d8fb17897ff8973648c":{
      "scriptId":"u116"},
    "1a4e2199ca884a65a1a4473034137404":{
      "scriptId":"u117"}}});