$axure.loadCurrentPage({
  "url":"支付兑奖.html",
  "generationDate":new Date(1496903836624.76),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"sfz",
"sfz_n"],
  "page":{
    "packageId":"ee96d1560e504f58860ee4730feedff8",
    "type":"Axure:Page",
    "name":"支付兑奖",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"95def86271e64b479e13ed974a4fa6f6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "size":{
              "width":320,
              "height":470},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9f608475c554eb28a49624f36fd4971",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "size":{
                  "width":320,
                  "height":470},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付订单/u0.png"}},
{
          "id":"5946e452f4c94e6c8e7524059e055683",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "fixedHorizontal":"left",
          "fixedMarginHorizontal":0,
          "fixedVertical":"top",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"d5004ba51f9d4ab3bca1a8d44cc4a2d4",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"952838c47ec24937be485749da125ee8",
                  "label":"",
                  "parentDynamicPanel":"5946e452f4c94e6c8e7524059e055683",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF1C222E},
                    "size":{
                      "width":320,
                      "height":64},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"576008b632164948bdd3c984c6f14428",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5946e452f4c94e6c8e7524059e055683",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF1C222E},
                        "size":{
                          "width":320,
                          "height":64},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u3.png"}},
{
                  "id":"7fac66de7eda49f3ab65029a8d6a4679",
                  "label":"",
                  "parentDynamicPanel":"5946e452f4c94e6c8e7524059e055683",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Heiti SC Regular', 'Heiti SC'",
                    "fontSize":"18px",
                    "fontWeight":"200",
                    "horizontalAlignment":"center",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":78,
                      "y":35},
                    "size":{
                      "width":163,
                      "height":22},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"69c27e1df4e44515b345d2a2d24f1b20",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5946e452f4c94e6c8e7524059e055683",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Heiti SC Regular', 'Heiti SC'",
                        "fontSize":"18px",
                        "fontWeight":"200",
                        "horizontalAlignment":"center",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":78,
                          "y":35},
                        "size":{
                          "width":163,
                          "height":22},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"24b0249c720d4340bb00345424f2dae0",
                  "label":"",
                  "parentDynamicPanel":"5946e452f4c94e6c8e7524059e055683",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":320,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e5ea6cc8f55c499f949de5f75e3cf10b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5946e452f4c94e6c8e7524059e055683",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":320,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u7.png"}},
{
                  "id":"3b14e20c4fe343699d04d8281bba11cc",
                  "label":"",
                  "parentDynamicPanel":"5946e452f4c94e6c8e7524059e055683",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Heiti SC Regular', 'Heiti SC'",
                    "fontSize":"16px",
                    "fontWeight":"200",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":27,
                      "y":36},
                    "size":{
                      "width":63,
                      "height":19},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2e12f96e643849e68dc734e8c7fcba0b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5946e452f4c94e6c8e7524059e055683",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Heiti SC Regular', 'Heiti SC'",
                        "fontSize":"16px",
                        "fontWeight":"200",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":27,
                          "y":36},
                        "size":{
                          "width":63,
                          "height":19},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"1f00db41fd2e4c8b8effef12e99c77c9",
                  "label":"",
                  "parentDynamicPanel":"5946e452f4c94e6c8e7524059e055683",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Lucida Grande Regular', 'Lucida Grande'",
                    "fontSize":"20px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":9,
                      "y":31},
                    "size":{
                      "width":22,
                      "height":29}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"415c3278d0f945fdb0a0207e6d540c1d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5946e452f4c94e6c8e7524059e055683",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Lucida Grande Regular', 'Lucida Grande'",
                        "fontSize":"20px",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":9,
                          "y":31},
                        "size":{
                          "width":22,
                          "height":29}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"5eab4d1455554ebb9409eca2470a9de8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"left",
            "location":{
              "x":0,
              "y":95},
            "size":{
              "width":320,
              "height":97}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f811b97ce7d846428786ca843da8ab99",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"left",
                "location":{
                  "x":0,
                  "y":95},
                "size":{
                  "width":320,
                  "height":97}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/确认订单-双色球/u13.png"}},
{
          "id":"64e83eca27a04538bec926042e997852",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":82,
              "y":109},
            "size":{
              "width":218,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"26535e508b004b558f37ad8c502f37b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":82,
                  "y":109},
                "size":{
                  "width":218,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c9560408cd49487dabeb16e7bb738391",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":148,
              "y":112},
            "size":{
              "width":172,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e517cc14ada34a72b1ad22bb1042b1dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":148,
                  "y":112},
                "size":{
                  "width":172,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f0a92626e06247f1a5cf252a8fd6d01b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":6,
              "y":109},
            "size":{
              "width":66,
              "height":66}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58875c3b9d6f4c6c91b7d9e3530de669",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":6,
                  "y":109},
                "size":{
                  "width":66,
                  "height":66}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/确认订单-双色球/u19.png"}},
{
          "id":"bc7bf9a241cf44faba3893c2de9d8c1f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":82,
              "y":158},
            "size":{
              "width":188,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e6733407518f4d71ad07a5e0e1385607",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":82,
                  "y":158},
                "size":{
                  "width":188,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0275ba38f9d34fa895bccd33f4e384e7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "location":{
              "x":0,
              "y":202},
            "size":{
              "width":320,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35f913311dc34053bcb80c18c2009d91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "location":{
                  "x":0,
                  "y":202},
                "size":{
                  "width":320,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付订单/u23.png"}},
{
          "id":"907817a71fc14a1a919985994e53fef0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":0,
              "y":249},
            "size":{
              "width":320,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4986e6420113484780d4a5dc7b441283",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":0,
                  "y":249},
                "size":{
                  "width":320,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付订单/u27.png"}},
{
          "id":"2b5659d103474ac29c71038432a621f6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":6,
              "y":260},
            "size":{
              "width":44,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9305ebaec4704e358f2bffe9e70097a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":6,
                  "y":260},
                "size":{
                  "width":44,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付订单/u29.png"}},
{
          "id":"e7b529862ac14316bf262b0fd6e9d39e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":56,
              "y":260},
            "size":{
              "width":200,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7887bec3987844508050a18d79f3ef57",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":56,
                  "y":260},
                "size":{
                  "width":200,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8eb863df2bb74713b66f488964cc4eb3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF6B6B6B,
              "opacity":1},
            "location":{
              "x":56,
              "y":284},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d6027ffcf634e73aad8e04a3af90be0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6B6B6B,
                  "opacity":1},
                "location":{
                  "x":56,
                  "y":284},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6d0a132b32a348bebed98d17bd67dae3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":0,
              "y":308},
            "size":{
              "width":320,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"043096af451742899ca47ad420f37063",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":0,
                  "y":308},
                "size":{
                  "width":320,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付订单/u27.png"}},
{
          "id":"45a661a0cecf4bfda87fc0227f80b172",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":6,
              "y":319},
            "size":{
              "width":44,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e2fa8e09300844a28521361ce78beac0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":6,
                  "y":319},
                "size":{
                  "width":44,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付订单/u29.png"}},
{
          "id":"2e4945a7dc414afbae22c1a7acdb925a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":56,
              "y":319},
            "size":{
              "width":200,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe7972945fe34760af36f967da1d6d88",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":56,
                  "y":319},
                "size":{
                  "width":200,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"24a4cb5b6ee242f88811d5c40e738a55",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":284,
              "y":330},
            "size":{
              "width":20,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14e868eca9944966aee42b077b028bb2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":284,
                  "y":330},
                "size":{
                  "width":20,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"b803ef2cca87412882d4b2ee1762142f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF6B6B6B,
              "opacity":1},
            "location":{
              "x":56,
              "y":343},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8748e1a7a405456695dbfaf39e3796ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6B6B6B,
                  "opacity":1},
                "location":{
                  "x":56,
                  "y":343},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3fb03968e1174684812666ab11ff34f8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":0,
              "y":420},
            "size":{
              "width":320,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6205c1a6d61d46cc8fbdbb360d051729",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":0,
                  "y":420},
                "size":{
                  "width":320,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付订单/u47.png"}},
{
          "id":"09c382702ab64311b464d281f30d26ea",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":82,
              "y":156},
            "size":{
              "width":226,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b9b453bdcf6e49b597be7e09e92b1b20",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":82,
                  "y":156},
                "size":{
                  "width":226,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"434629719c084b14b066596d0681debb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":239,
              "y":264},
            "size":{
              "width":65,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3865a0e3a3e14145a94c1842e9dc5c7b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":239,
                  "y":264},
                "size":{
                  "width":65,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付兑奖/u47.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "95def86271e64b479e13ed974a4fa6f6":{
      "scriptId":"u0"},
    "f9f608475c554eb28a49624f36fd4971":{
      "scriptId":"u1"},
    "5946e452f4c94e6c8e7524059e055683":{
      "scriptId":"u2"},
    "952838c47ec24937be485749da125ee8":{
      "scriptId":"u3"},
    "576008b632164948bdd3c984c6f14428":{
      "scriptId":"u4"},
    "7fac66de7eda49f3ab65029a8d6a4679":{
      "scriptId":"u5"},
    "69c27e1df4e44515b345d2a2d24f1b20":{
      "scriptId":"u6"},
    "24b0249c720d4340bb00345424f2dae0":{
      "scriptId":"u7"},
    "e5ea6cc8f55c499f949de5f75e3cf10b":{
      "scriptId":"u8"},
    "3b14e20c4fe343699d04d8281bba11cc":{
      "scriptId":"u9"},
    "2e12f96e643849e68dc734e8c7fcba0b":{
      "scriptId":"u10"},
    "1f00db41fd2e4c8b8effef12e99c77c9":{
      "scriptId":"u11"},
    "415c3278d0f945fdb0a0207e6d540c1d":{
      "scriptId":"u12"},
    "5eab4d1455554ebb9409eca2470a9de8":{
      "scriptId":"u13"},
    "f811b97ce7d846428786ca843da8ab99":{
      "scriptId":"u14"},
    "64e83eca27a04538bec926042e997852":{
      "scriptId":"u15"},
    "26535e508b004b558f37ad8c502f37b5":{
      "scriptId":"u16"},
    "c9560408cd49487dabeb16e7bb738391":{
      "scriptId":"u17"},
    "e517cc14ada34a72b1ad22bb1042b1dd":{
      "scriptId":"u18"},
    "f0a92626e06247f1a5cf252a8fd6d01b":{
      "scriptId":"u19"},
    "58875c3b9d6f4c6c91b7d9e3530de669":{
      "scriptId":"u20"},
    "bc7bf9a241cf44faba3893c2de9d8c1f":{
      "scriptId":"u21"},
    "e6733407518f4d71ad07a5e0e1385607":{
      "scriptId":"u22"},
    "0275ba38f9d34fa895bccd33f4e384e7":{
      "scriptId":"u23"},
    "35f913311dc34053bcb80c18c2009d91":{
      "scriptId":"u24"},
    "907817a71fc14a1a919985994e53fef0":{
      "scriptId":"u25"},
    "4986e6420113484780d4a5dc7b441283":{
      "scriptId":"u26"},
    "2b5659d103474ac29c71038432a621f6":{
      "scriptId":"u27"},
    "9305ebaec4704e358f2bffe9e70097a3":{
      "scriptId":"u28"},
    "e7b529862ac14316bf262b0fd6e9d39e":{
      "scriptId":"u29"},
    "7887bec3987844508050a18d79f3ef57":{
      "scriptId":"u30"},
    "8eb863df2bb74713b66f488964cc4eb3":{
      "scriptId":"u31"},
    "0d6027ffcf634e73aad8e04a3af90be0":{
      "scriptId":"u32"},
    "6d0a132b32a348bebed98d17bd67dae3":{
      "scriptId":"u33"},
    "043096af451742899ca47ad420f37063":{
      "scriptId":"u34"},
    "45a661a0cecf4bfda87fc0227f80b172":{
      "scriptId":"u35"},
    "e2fa8e09300844a28521361ce78beac0":{
      "scriptId":"u36"},
    "2e4945a7dc414afbae22c1a7acdb925a":{
      "scriptId":"u37"},
    "fe7972945fe34760af36f967da1d6d88":{
      "scriptId":"u38"},
    "24a4cb5b6ee242f88811d5c40e738a55":{
      "scriptId":"u39"},
    "14e868eca9944966aee42b077b028bb2":{
      "scriptId":"u40"},
    "b803ef2cca87412882d4b2ee1762142f":{
      "scriptId":"u41"},
    "8748e1a7a405456695dbfaf39e3796ef":{
      "scriptId":"u42"},
    "3fb03968e1174684812666ab11ff34f8":{
      "scriptId":"u43"},
    "6205c1a6d61d46cc8fbdbb360d051729":{
      "scriptId":"u44"},
    "09c382702ab64311b464d281f30d26ea":{
      "scriptId":"u45"},
    "b9b453bdcf6e49b597be7e09e92b1b20":{
      "scriptId":"u46"},
    "434629719c084b14b066596d0681debb":{
      "scriptId":"u47"},
    "3865a0e3a3e14145a94c1842e9dc5c7b":{
      "scriptId":"u48"}}});