$axure.loadCurrentPage({
  "url":"意见反馈_1.html",
  "generationDate":new Date(1496903836715.76),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"sfz",
"sfz_n"],
  "page":{
    "packageId":"0babee1eb9a444ff922699532ecb3f9d",
    "type":"Axure:Page",
    "name":"意见反馈",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"02c9509433cd4b89b68ca963c8af4a26",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "size":{
              "width":320,
              "height":500},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67962d689e494a0ea8c4b8a8706386c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "size":{
                  "width":320,
                  "height":500},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/钱包/u0.png"}},
{
          "id":"04c2879e18ec419f8f1eaa556cdbe393",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "fixedHorizontal":"left",
          "fixedMarginHorizontal":0,
          "fixedVertical":"top",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"813c126951eb4b7db46fe88d356e2b75",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"662058cb637f451d9f8c515e0dd56a75",
                  "label":"",
                  "parentDynamicPanel":"04c2879e18ec419f8f1eaa556cdbe393",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF1C222E},
                    "size":{
                      "width":320,
                      "height":64},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7c7c79f0c3294f159ad6d402981e728d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"04c2879e18ec419f8f1eaa556cdbe393",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF1C222E},
                        "size":{
                          "width":320,
                          "height":64},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u3.png"}},
{
                  "id":"e4096e47257a48d49dd7957be70f12e2",
                  "label":"",
                  "parentDynamicPanel":"04c2879e18ec419f8f1eaa556cdbe393",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Heiti SC Regular', 'Heiti SC'",
                    "fontSize":"18px",
                    "fontWeight":"200",
                    "horizontalAlignment":"center",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":78,
                      "y":35},
                    "size":{
                      "width":163,
                      "height":22},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0ba0a173e2fe44da986545f7e68b4242",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"04c2879e18ec419f8f1eaa556cdbe393",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Heiti SC Regular', 'Heiti SC'",
                        "fontSize":"18px",
                        "fontWeight":"200",
                        "horizontalAlignment":"center",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":78,
                          "y":35},
                        "size":{
                          "width":163,
                          "height":22},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"a96b1fb0e451483f8ec7928a1eb79854",
                  "label":"",
                  "parentDynamicPanel":"04c2879e18ec419f8f1eaa556cdbe393",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":320,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"53b24939acb04fec9b1274534d287434",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"04c2879e18ec419f8f1eaa556cdbe393",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":320,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u7.png"}},
{
                  "id":"fdd3a9a8543a412fb29a10f23747d84a",
                  "label":"",
                  "parentDynamicPanel":"04c2879e18ec419f8f1eaa556cdbe393",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Heiti SC Regular', 'Heiti SC'",
                    "fontSize":"16px",
                    "fontWeight":"200",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":27,
                      "y":36},
                    "size":{
                      "width":63,
                      "height":19},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"754dc00159f048e6874d4e03a3a9f666",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"04c2879e18ec419f8f1eaa556cdbe393",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Heiti SC Regular', 'Heiti SC'",
                        "fontSize":"16px",
                        "fontWeight":"200",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":27,
                          "y":36},
                        "size":{
                          "width":63,
                          "height":19},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"391d5d4dcd2f4609b7c0602c2fe57d09",
                  "label":"",
                  "parentDynamicPanel":"04c2879e18ec419f8f1eaa556cdbe393",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Lucida Grande Regular', 'Lucida Grande'",
                    "fontSize":"20px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":9,
                      "y":31},
                    "size":{
                      "width":22,
                      "height":29}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8e4bcda7707948d3b29bdee66dfa9c0f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"04c2879e18ec419f8f1eaa556cdbe393",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Lucida Grande Regular', 'Lucida Grande'",
                        "fontSize":"20px",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":9,
                          "y":31},
                        "size":{
                          "width":22,
                          "height":29}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"132d13d66dab4d479eea636010ce30f8",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "stateStyles":{
              "hint":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1}}},
            "location":{
              "x":20,
              "y":80},
            "size":{
              "width":280,
              "height":130}},
          "adaptiveStyles":{
},
          "placeholderText":"在这里输入您的意见和建议"},
{
          "id":"1586749470ee4fb284e5873e147baf7c",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":20,
              "y":275},
            "size":{
              "width":270,
              "height":45}},
          "adaptiveStyles":{
}},
{
          "id":"261da8471edd438596123e2fec816937",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":20,
              "y":220},
            "size":{
              "width":280,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1eee0011dba40ba9faa18bae1bfc589",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":20,
                  "y":220},
                "size":{
                  "width":280,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "02c9509433cd4b89b68ca963c8af4a26":{
      "scriptId":"u0"},
    "67962d689e494a0ea8c4b8a8706386c2":{
      "scriptId":"u1"},
    "04c2879e18ec419f8f1eaa556cdbe393":{
      "scriptId":"u2"},
    "662058cb637f451d9f8c515e0dd56a75":{
      "scriptId":"u3"},
    "7c7c79f0c3294f159ad6d402981e728d":{
      "scriptId":"u4"},
    "e4096e47257a48d49dd7957be70f12e2":{
      "scriptId":"u5"},
    "0ba0a173e2fe44da986545f7e68b4242":{
      "scriptId":"u6"},
    "a96b1fb0e451483f8ec7928a1eb79854":{
      "scriptId":"u7"},
    "53b24939acb04fec9b1274534d287434":{
      "scriptId":"u8"},
    "fdd3a9a8543a412fb29a10f23747d84a":{
      "scriptId":"u9"},
    "754dc00159f048e6874d4e03a3a9f666":{
      "scriptId":"u10"},
    "391d5d4dcd2f4609b7c0602c2fe57d09":{
      "scriptId":"u11"},
    "8e4bcda7707948d3b29bdee66dfa9c0f":{
      "scriptId":"u12"},
    "132d13d66dab4d479eea636010ce30f8":{
      "scriptId":"u13"},
    "1586749470ee4fb284e5873e147baf7c":{
      "scriptId":"u14"},
    "261da8471edd438596123e2fec816937":{
      "scriptId":"u15"},
    "b1eee0011dba40ba9faa18bae1bfc589":{
      "scriptId":"u16"}}});