$axure.loadCurrentPage({
  "url":"支付订单.html",
  "generationDate":new Date(1496903828546.76),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"sfz",
"sfz_n"],
  "page":{
    "packageId":"a135fd26254b4236b7fbf55f8cc6e38b",
    "type":"Axure:Page",
    "name":"支付订单",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"3b53359466df43dc9c3e475e0b63b33d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "size":{
              "width":320,
              "height":470},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"515476cc58914867bdbeae7a995ceab8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "size":{
                  "width":320,
                  "height":470},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付订单/u0.png"}},
{
          "id":"13a0d13853e24a019ce739c97c050481",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "fixedHorizontal":"left",
          "fixedMarginHorizontal":0,
          "fixedVertical":"top",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"b813ce2b736e484d83f944515f410d19",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"4330e1ecefb94ea99372fe4a2a73d4c0",
                  "label":"",
                  "parentDynamicPanel":"13a0d13853e24a019ce739c97c050481",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF1C222E},
                    "size":{
                      "width":320,
                      "height":64},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0b39a7bbda704886810da52ab4a8a468",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"13a0d13853e24a019ce739c97c050481",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF1C222E},
                        "size":{
                          "width":320,
                          "height":64},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u3.png"}},
{
                  "id":"c820ef932b6f41bfa26f241a5104fbf0",
                  "label":"",
                  "parentDynamicPanel":"13a0d13853e24a019ce739c97c050481",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Heiti SC Regular', 'Heiti SC'",
                    "fontSize":"18px",
                    "fontWeight":"200",
                    "horizontalAlignment":"center",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":78,
                      "y":35},
                    "size":{
                      "width":163,
                      "height":22},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a013e379e10e40a9afdca4f138ac48e2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"13a0d13853e24a019ce739c97c050481",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Heiti SC Regular', 'Heiti SC'",
                        "fontSize":"18px",
                        "fontWeight":"200",
                        "horizontalAlignment":"center",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":78,
                          "y":35},
                        "size":{
                          "width":163,
                          "height":22},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"eca813b3281847248e22f71bc62260c3",
                  "label":"",
                  "parentDynamicPanel":"13a0d13853e24a019ce739c97c050481",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":320,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"747b3d3b23074faa8bb3b299d8f9794d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"13a0d13853e24a019ce739c97c050481",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":320,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u7.png"}},
{
                  "id":"a264cbe716e44ecaa96a9be5e0234ede",
                  "label":"",
                  "parentDynamicPanel":"13a0d13853e24a019ce739c97c050481",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Heiti SC Regular', 'Heiti SC'",
                    "fontSize":"16px",
                    "fontWeight":"200",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":27,
                      "y":36},
                    "size":{
                      "width":63,
                      "height":19},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d15668f63e684f27b8d248aa89ce77c9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"13a0d13853e24a019ce739c97c050481",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Heiti SC Regular', 'Heiti SC'",
                        "fontSize":"16px",
                        "fontWeight":"200",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":27,
                          "y":36},
                        "size":{
                          "width":63,
                          "height":19},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"46d37f1c0e7043f9a0a4a0d9f58d760f",
                  "label":"",
                  "parentDynamicPanel":"13a0d13853e24a019ce739c97c050481",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Lucida Grande Regular', 'Lucida Grande'",
                    "fontSize":"20px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":9,
                      "y":31},
                    "size":{
                      "width":22,
                      "height":29}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"014df6b7b1c1442596a54302e34afeb0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"13a0d13853e24a019ce739c97c050481",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Lucida Grande Regular', 'Lucida Grande'",
                        "fontSize":"20px",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":9,
                          "y":31},
                        "size":{
                          "width":22,
                          "height":29}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"12d0a76bb4ce43e9bbd624ffb5b3462d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"left",
            "location":{
              "x":0,
              "y":95},
            "size":{
              "width":320,
              "height":97}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"33684b4d79cb42148685917f90262542",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"left",
                "location":{
                  "x":0,
                  "y":95},
                "size":{
                  "width":320,
                  "height":97}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/确认订单-双色球/u13.png"}},
{
          "id":"5583952da813414c85d91c12adfc5cf9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":82,
              "y":109},
            "size":{
              "width":218,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9189293acb4d4cb3be561cc47d8d5a3e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":82,
                  "y":109},
                "size":{
                  "width":218,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"621eafea62d242e0b28d46fe9bc52cdb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":148,
              "y":112},
            "size":{
              "width":172,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"568261f9b76f425c942fabccf280c075",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":148,
                  "y":112},
                "size":{
                  "width":172,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"40c2ba35010f4e5cb921079dc1f9337e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":6,
              "y":109},
            "size":{
              "width":66,
              "height":66}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52577313455f467b90d3ac9ff79213a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":6,
                  "y":109},
                "size":{
                  "width":66,
                  "height":66}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/确认订单-双色球/u19.png"}},
{
          "id":"f858cb234a61418691ef421039559de6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":0,
              "y":63},
            "size":{
              "width":320,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46df86853bf741f0bd29e4ad3e1e3109",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":0,
                  "y":63},
                "size":{
                  "width":320,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/确认订单-双色球/u23.png"}},
{
          "id":"e36991a4e6dd42da89abad0f58470e6a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "location":{
              "x":0,
              "y":202},
            "size":{
              "width":320,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0c0daf5d90df4b7ca7d2dd94f1fadcdd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "location":{
                  "x":0,
                  "y":202},
                "size":{
                  "width":320,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付订单/u23.png"}},
{
          "id":"e59ac441917a4beebd5bdec253547d9c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":82,
              "y":156},
            "size":{
              "width":174,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52f7171671f34e7392e89067e46f6c48",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":82,
                  "y":156},
                "size":{
                  "width":174,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0bdc962b50f74e45bab3588982fe4898",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":0,
              "y":249},
            "size":{
              "width":320,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0bdd12ce15bd46b0a0acdc384d42526d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":0,
                  "y":249},
                "size":{
                  "width":320,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付订单/u27.png"}},
{
          "id":"f23f32937b254cc1b913802af3a0acf4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":6,
              "y":260},
            "size":{
              "width":44,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dbbe337f033e440f88170cad8ad98f02",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":6,
                  "y":260},
                "size":{
                  "width":44,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付订单/u29.png"}},
{
          "id":"24b183b7265e4d7595bcc723e539445b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":56,
              "y":260},
            "size":{
              "width":200,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f044e4ffc3244accaa0a8489766448eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":56,
                  "y":260},
                "size":{
                  "width":200,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6fe4fac7ddaf48a98edf5bf631263250",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":284,
              "y":271},
            "size":{
              "width":20,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"991ff3af4525403981f3a433f8137703",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":284,
                  "y":271},
                "size":{
                  "width":20,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"b442d87d41fe4116b9d777fa9ff0560b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF6B6B6B,
              "opacity":1},
            "location":{
              "x":56,
              "y":284},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2115ad33d82e4b13b28fcb406f8ae477",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6B6B6B,
                  "opacity":1},
                "location":{
                  "x":56,
                  "y":284},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"45d26655d97e4354a294b1592711823e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":0,
              "y":308},
            "size":{
              "width":320,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"746f062295f2436096a65c7f81676359",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":0,
                  "y":308},
                "size":{
                  "width":320,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付订单/u27.png"}},
{
          "id":"4f9335a2ed4d4a9399c7091d7b780228",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":6,
              "y":319},
            "size":{
              "width":44,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a88159b965b450bbded04e144d3d235",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":6,
                  "y":319},
                "size":{
                  "width":44,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付订单/u29.png"}},
{
          "id":"d872ba8afd8e4e98a53059269d4f75b0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":56,
              "y":319},
            "size":{
              "width":200,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27fde7d454334144b191e898485fd95e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":56,
                  "y":319},
                "size":{
                  "width":200,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ca0a94b736254070965fdcf14bf429a0",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":284,
              "y":330},
            "size":{
              "width":20,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d52bd89376434f0fa82fa3f036b3895d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":284,
                  "y":330},
                "size":{
                  "width":20,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"c8bad96fe4964fae836d2f936833061d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF6B6B6B,
              "opacity":1},
            "location":{
              "x":56,
              "y":343},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cfd9ed9985114fbc85194f49da6e148c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6B6B6B,
                  "opacity":1},
                "location":{
                  "x":56,
                  "y":343},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5478a9cb61214c4bb7b46c18fcfdec1d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":0,
              "y":420},
            "size":{
              "width":320,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1980684ab4c447c2b94c44bdb7bdfc2f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":0,
                  "y":420},
                "size":{
                  "width":320,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付订单/u47.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "3b53359466df43dc9c3e475e0b63b33d":{
      "scriptId":"u0"},
    "515476cc58914867bdbeae7a995ceab8":{
      "scriptId":"u1"},
    "13a0d13853e24a019ce739c97c050481":{
      "scriptId":"u2"},
    "4330e1ecefb94ea99372fe4a2a73d4c0":{
      "scriptId":"u3"},
    "0b39a7bbda704886810da52ab4a8a468":{
      "scriptId":"u4"},
    "c820ef932b6f41bfa26f241a5104fbf0":{
      "scriptId":"u5"},
    "a013e379e10e40a9afdca4f138ac48e2":{
      "scriptId":"u6"},
    "eca813b3281847248e22f71bc62260c3":{
      "scriptId":"u7"},
    "747b3d3b23074faa8bb3b299d8f9794d":{
      "scriptId":"u8"},
    "a264cbe716e44ecaa96a9be5e0234ede":{
      "scriptId":"u9"},
    "d15668f63e684f27b8d248aa89ce77c9":{
      "scriptId":"u10"},
    "46d37f1c0e7043f9a0a4a0d9f58d760f":{
      "scriptId":"u11"},
    "014df6b7b1c1442596a54302e34afeb0":{
      "scriptId":"u12"},
    "12d0a76bb4ce43e9bbd624ffb5b3462d":{
      "scriptId":"u13"},
    "33684b4d79cb42148685917f90262542":{
      "scriptId":"u14"},
    "5583952da813414c85d91c12adfc5cf9":{
      "scriptId":"u15"},
    "9189293acb4d4cb3be561cc47d8d5a3e":{
      "scriptId":"u16"},
    "621eafea62d242e0b28d46fe9bc52cdb":{
      "scriptId":"u17"},
    "568261f9b76f425c942fabccf280c075":{
      "scriptId":"u18"},
    "40c2ba35010f4e5cb921079dc1f9337e":{
      "scriptId":"u19"},
    "52577313455f467b90d3ac9ff79213a0":{
      "scriptId":"u20"},
    "f858cb234a61418691ef421039559de6":{
      "scriptId":"u21"},
    "46df86853bf741f0bd29e4ad3e1e3109":{
      "scriptId":"u22"},
    "e36991a4e6dd42da89abad0f58470e6a":{
      "scriptId":"u23"},
    "0c0daf5d90df4b7ca7d2dd94f1fadcdd":{
      "scriptId":"u24"},
    "e59ac441917a4beebd5bdec253547d9c":{
      "scriptId":"u25"},
    "52f7171671f34e7392e89067e46f6c48":{
      "scriptId":"u26"},
    "0bdc962b50f74e45bab3588982fe4898":{
      "scriptId":"u27"},
    "0bdd12ce15bd46b0a0acdc384d42526d":{
      "scriptId":"u28"},
    "f23f32937b254cc1b913802af3a0acf4":{
      "scriptId":"u29"},
    "dbbe337f033e440f88170cad8ad98f02":{
      "scriptId":"u30"},
    "24b183b7265e4d7595bcc723e539445b":{
      "scriptId":"u31"},
    "f044e4ffc3244accaa0a8489766448eb":{
      "scriptId":"u32"},
    "6fe4fac7ddaf48a98edf5bf631263250":{
      "scriptId":"u33"},
    "991ff3af4525403981f3a433f8137703":{
      "scriptId":"u34"},
    "b442d87d41fe4116b9d777fa9ff0560b":{
      "scriptId":"u35"},
    "2115ad33d82e4b13b28fcb406f8ae477":{
      "scriptId":"u36"},
    "45d26655d97e4354a294b1592711823e":{
      "scriptId":"u37"},
    "746f062295f2436096a65c7f81676359":{
      "scriptId":"u38"},
    "4f9335a2ed4d4a9399c7091d7b780228":{
      "scriptId":"u39"},
    "3a88159b965b450bbded04e144d3d235":{
      "scriptId":"u40"},
    "d872ba8afd8e4e98a53059269d4f75b0":{
      "scriptId":"u41"},
    "27fde7d454334144b191e898485fd95e":{
      "scriptId":"u42"},
    "ca0a94b736254070965fdcf14bf429a0":{
      "scriptId":"u43"},
    "d52bd89376434f0fa82fa3f036b3895d":{
      "scriptId":"u44"},
    "c8bad96fe4964fae836d2f936833061d":{
      "scriptId":"u45"},
    "cfd9ed9985114fbc85194f49da6e148c":{
      "scriptId":"u46"},
    "5478a9cb61214c4bb7b46c18fcfdec1d":{
      "scriptId":"u47"},
    "1980684ab4c447c2b94c44bdb7bdfc2f":{
      "scriptId":"u48"}}});