$axure.loadCurrentPage({
  "url":"打票任务.html",
  "generationDate":new Date(1496903836267.76),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"sfz",
"sfz_n"],
  "page":{
    "packageId":"7b735c4f43b445ccaa1e2bbd174b2dbb",
    "type":"Axure:Page",
    "name":"打票任务",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"5285e837732946a686f168bcdc862016",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "size":{
              "width":320,
              "height":1420},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"764b24cbd48d450587c6d4d6dfc0ea52",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "size":{
                  "width":320,
                  "height":1420},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/打票任务/u0.png"}},
{
          "id":"13a417ea5ca943908b1687f1125edce1",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "fixedHorizontal":"left",
          "fixedMarginHorizontal":0,
          "fixedVertical":"top",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"14dc9dc998a94506afd9160a4f78118d",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"7ef0b4dc5f844a94ac25de523eac2ee0",
                  "label":"",
                  "parentDynamicPanel":"13a417ea5ca943908b1687f1125edce1",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF1C222E},
                    "size":{
                      "width":320,
                      "height":64},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c9ccf497b74e47979f4fb55521927389",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"13a417ea5ca943908b1687f1125edce1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF1C222E},
                        "size":{
                          "width":320,
                          "height":64},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u3.png"}},
{
                  "id":"cd1b11dddc694abbad2975224353173f",
                  "label":"",
                  "parentDynamicPanel":"13a417ea5ca943908b1687f1125edce1",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Heiti SC Regular', 'Heiti SC'",
                    "fontSize":"18px",
                    "fontWeight":"200",
                    "horizontalAlignment":"center",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":78,
                      "y":35},
                    "size":{
                      "width":163,
                      "height":22},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9694347acabe4d8e9464c0a1082d98c5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"13a417ea5ca943908b1687f1125edce1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Heiti SC Regular', 'Heiti SC'",
                        "fontSize":"18px",
                        "fontWeight":"200",
                        "horizontalAlignment":"center",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":78,
                          "y":35},
                        "size":{
                          "width":163,
                          "height":22},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"00522f6c6a75406da17d035b0481165b",
                  "label":"",
                  "parentDynamicPanel":"13a417ea5ca943908b1687f1125edce1",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":320,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6615c0a384cf475b9cf43599ad5a8115",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"13a417ea5ca943908b1687f1125edce1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":320,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u7.png"}},
{
                  "id":"8e621548b5344666ac4520850635878e",
                  "label":"",
                  "parentDynamicPanel":"13a417ea5ca943908b1687f1125edce1",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Heiti SC Regular', 'Heiti SC'",
                    "fontSize":"16px",
                    "fontWeight":"200",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":27,
                      "y":36},
                    "size":{
                      "width":63,
                      "height":19},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ff07a22662d34ae3b3d99b312f6d5ca8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"13a417ea5ca943908b1687f1125edce1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Heiti SC Regular', 'Heiti SC'",
                        "fontSize":"16px",
                        "fontWeight":"200",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":27,
                          "y":36},
                        "size":{
                          "width":63,
                          "height":19},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"d6f362f51d95467cabf17067defda941",
                  "label":"",
                  "parentDynamicPanel":"13a417ea5ca943908b1687f1125edce1",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Lucida Grande Regular', 'Lucida Grande'",
                    "fontSize":"20px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":9,
                      "y":31},
                    "size":{
                      "width":22,
                      "height":29}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9a6842e4081841728553c81bf55f2307",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"13a417ea5ca943908b1687f1125edce1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Lucida Grande Regular', 'Lucida Grande'",
                        "fontSize":"20px",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":9,
                          "y":31},
                        "size":{
                          "width":22,
                          "height":29}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"68b743cbfefa47fea9354325c3297699",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":1,
              "y":63},
            "size":{
              "width":80,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"89aa2e3e36324aa6a3b15ea8248a7e9f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":1,
                  "y":63},
                "size":{
                  "width":80,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单中心/u13.png"}},
{
          "id":"0ed3e117565348e690f68a595420a7cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"left",
            "location":{
              "x":81,
              "y":63},
            "size":{
              "width":80,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe7a269e5b6e4bd98c00596639960578",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"left",
                "location":{
                  "x":81,
                  "y":63},
                "size":{
                  "width":80,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单中心/u13.png"}},
{
          "id":"5da01be17ee946329fbaea3a40c8266e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":160,
              "y":63},
            "size":{
              "width":80,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c5fe1479d7f845568a2fb93055e8c42d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":160,
                  "y":63},
                "size":{
                  "width":80,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单中心/u13.png"}},
{
          "id":"eaa3affe85fd42ddb9f928570e0bb091",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"left",
            "location":{
              "x":240,
              "y":63},
            "size":{
              "width":80,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db82cad6deb24cff8d0498e61dfbee79",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"left",
                "location":{
                  "x":240,
                  "y":63},
                "size":{
                  "width":80,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单中心/u13.png"}},
{
          "id":"3d5be1602b304e2488a4aa17935aa594",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":0,
              "y":109},
            "size":{
              "width":320,
              "height":191}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b613c00bca374615b12d8f6ca871c639",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":0,
                  "y":109},
                "size":{
                  "width":320,
                  "height":191}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/打票任务/u21.png"}},
{
          "id":"a9a7571d17984e518f17d8ed84e14ea9",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":150},
            "size":{
              "width":320,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/合买详情/u49_line.png"}},
{
          "id":"38dff6057c264be48ae40af65a8acd13",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":4,
              "y":124},
            "size":{
              "width":226,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4cc6e195fc0a47afba107a8d79941ddc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":4,
                  "y":124},
                "size":{
                  "width":226,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b0bf4df0d75a46b3a98026b57ee8da0f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":234,
              "y":117},
            "size":{
              "width":80,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cfc6f10900ff4a5aa5b096b114de4a61",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":234,
                  "y":117},
                "size":{
                  "width":80,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单中心/u26.png"}},
{
          "id":"5863b2b7ebef488894f3c46deb24706f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":4,
              "y":160},
            "size":{
              "width":226,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"deebf83ba5be48dc95c0b7b549079b9c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":4,
                  "y":160},
                "size":{
                  "width":226,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"08ebe90eead143229eeaf244a4f3f054",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":58,
              "y":163},
            "size":{
              "width":186,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f803a20d1004d8881fae49a0b9be2e4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":58,
                  "y":163},
                "size":{
                  "width":186,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a71aab681191422f8f20f1d7351ad335",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":0,
              "y":299},
            "size":{
              "width":320,
              "height":49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"86352f857b804ac98411cada5fac166f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":0,
                  "y":299},
                "size":{
                  "width":320,
                  "height":49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/确认订单-双色球/u60.png"}},
{
          "id":"9d88cefe82d94760b4055fbd7961a92e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":6,
              "y":314},
            "size":{
              "width":226,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d3451ce8e4b449c88c700de28ed12f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":6,
                  "y":314},
                "size":{
                  "width":226,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d37af51169bc4a7f85ebdcc076033e65",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":214,
              "y":306},
            "size":{
              "width":100,
              "height":35}},
          "adaptiveStyles":{
}},
{
          "id":"42f64ea9253f4c07b3e41a1abdd85bf1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":6,
              "y":200},
            "size":{
              "width":259,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1d93a5ee7ac4a868b51ae10fcd224b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":6,
                  "y":200},
                "size":{
                  "width":259,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5512faabac294250af649053f8c29232",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":6,
              "y":232},
            "size":{
              "width":255,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bdac3944aa004e3995d3480b7804bba3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":6,
                  "y":232},
                "size":{
                  "width":255,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"42da819b246d4d03b5cc98320492d329",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":6,
              "y":267},
            "size":{
              "width":255,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8cf6cc43eadc4341a9e5b48890720865",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":6,
                  "y":267},
                "size":{
                  "width":255,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"948fe2fcb9874a28829728aa80f94064",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":0,
              "y":358},
            "size":{
              "width":320,
              "height":191}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d6544b92c68645fb917b5744066a1c5f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":0,
                  "y":358},
                "size":{
                  "width":320,
                  "height":191}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/打票任务/u21.png"}},
{
          "id":"930061dbba744cbea2259448ebde0c7b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":399},
            "size":{
              "width":320,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/合买详情/u49_line.png"}},
{
          "id":"7e03e26550e3476ea56325c1aab5ff8a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":4,
              "y":373},
            "size":{
              "width":226,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3bd42276b5648c8a02c884758390463",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":4,
                  "y":373},
                "size":{
                  "width":226,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8ac3fd2c63bc4fa2885ce1f753cd1821",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":234,
              "y":366},
            "size":{
              "width":80,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"967534325a024e199d910025c84a4142",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":234,
                  "y":366},
                "size":{
                  "width":80,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单中心/u26.png"}},
{
          "id":"5e64a3fe06dc453eaa3b4c1bb4f65bc1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":4,
              "y":409},
            "size":{
              "width":226,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb6d2035c3fa426bb10a006be9883367",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":4,
                  "y":409},
                "size":{
                  "width":226,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bcb39494f3ff42e395480265e7661bda",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":58,
              "y":412},
            "size":{
              "width":186,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f873cb6de812470daccedc49dc0e1671",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":58,
                  "y":412},
                "size":{
                  "width":186,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"abbf4341164d4125b80ec1f422b4b877",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":0,
              "y":548},
            "size":{
              "width":320,
              "height":49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"152317493ca747a0b7d33b4942bb60f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":0,
                  "y":548},
                "size":{
                  "width":320,
                  "height":49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/确认订单-双色球/u60.png"}},
{
          "id":"975e773a889441be99e7e9d7f280618a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":6,
              "y":563},
            "size":{
              "width":226,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"983d1e2306314747963cab10b3c14973",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":6,
                  "y":563},
                "size":{
                  "width":226,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3e60283531c24f8fb64d3a8a620b8a10",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":6,
              "y":449},
            "size":{
              "width":259,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b2bad18acb9e4547b8b57dc2d284781a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":6,
                  "y":449},
                "size":{
                  "width":259,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"47610e78ae89481ab02aad9cd0d43424",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":6,
              "y":481},
            "size":{
              "width":255,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"51ad11c628ed485e9345839274eac9f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":6,
                  "y":481},
                "size":{
                  "width":255,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0167cc3afb174c06861e4386a8f3e357",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":6,
              "y":516},
            "size":{
              "width":255,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b98ec199961d4e199e26a3a6750d4a74",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":6,
                  "y":516},
                "size":{
                  "width":255,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"83a7616de1644ba19458b77aeff62d43",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":0,
              "y":607},
            "size":{
              "width":320,
              "height":191}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1995905c9f404cb98b3fb82403411c9d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":0,
                  "y":607},
                "size":{
                  "width":320,
                  "height":191}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/打票任务/u21.png"}},
{
          "id":"565eff48f9324b91bb19e7f105403dbc",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":648},
            "size":{
              "width":320,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/合买详情/u49_line.png"}},
{
          "id":"ad8a38988a5e466db46644e2907046f9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":4,
              "y":622},
            "size":{
              "width":226,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5fc38eb099dd4561864d93b95b9750f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":4,
                  "y":622},
                "size":{
                  "width":226,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c1853bedc88842fb9fc340936d0cfeee",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":234,
              "y":615},
            "size":{
              "width":80,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65f7a02daf254946aed745dcd8d355ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":234,
                  "y":615},
                "size":{
                  "width":80,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单中心/u26.png"}},
{
          "id":"d6ca3d659f494e219ff88f63df620075",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":4,
              "y":658},
            "size":{
              "width":226,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ca98c614a75498cbc7a16bc69e0e1ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":4,
                  "y":658},
                "size":{
                  "width":226,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"019de19c81eb42ffbeda328bcd3a8e7e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":58,
              "y":661},
            "size":{
              "width":186,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5475a387c38f422880fb76449fa1a57c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":58,
                  "y":661},
                "size":{
                  "width":186,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eaa9ebebcd2d4158998c98f04de9cfd5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":0,
              "y":797},
            "size":{
              "width":320,
              "height":49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c9411ab5a054a629105cd8201b774b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":0,
                  "y":797},
                "size":{
                  "width":320,
                  "height":49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/确认订单-双色球/u60.png"}},
{
          "id":"79e09ad6a0f4477c976d310c8e84ddf5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":6,
              "y":812},
            "size":{
              "width":226,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f238af3bb8d94a54a81ad5cc362b825f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":6,
                  "y":812},
                "size":{
                  "width":226,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e9c2076d175145f5bad65084a3483911",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":6,
              "y":698},
            "size":{
              "width":259,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5cac1538a6814d73bdc5761f1d04784e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":6,
                  "y":698},
                "size":{
                  "width":259,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"23ad0ec5e38c42fdba1f354a71494b6c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":6,
              "y":730},
            "size":{
              "width":255,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4634d731914341eab1b9f6cdcafc1f9b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":6,
                  "y":730},
                "size":{
                  "width":255,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"945564cbf6054ae895a9105d00b81ab5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":6,
              "y":765},
            "size":{
              "width":255,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8099c3eecb5a4adc80ad6f1a4c12ee26",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":6,
                  "y":765},
                "size":{
                  "width":255,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"269631bd5e99498289a068abff7ab98c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":0,
              "y":856},
            "size":{
              "width":320,
              "height":191}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96418e935e9d44c6b4a046a5e4cdbd81",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":0,
                  "y":856},
                "size":{
                  "width":320,
                  "height":191}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/打票任务/u21.png"}},
{
          "id":"22f768b805904e3f817dba84b9edeca4",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":897},
            "size":{
              "width":320,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/合买详情/u49_line.png"}},
{
          "id":"fbcb3fa5fcc54aedbafd96f8f7ae14cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":4,
              "y":871},
            "size":{
              "width":226,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2aefd519bedb476c843a60246cfcb597",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":4,
                  "y":871},
                "size":{
                  "width":226,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f0520cf5c8354c89aac1391d089d50c7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":234,
              "y":864},
            "size":{
              "width":80,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea6dec422a944c5ea98075dd366459e4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":234,
                  "y":864},
                "size":{
                  "width":80,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单中心/u26.png"}},
{
          "id":"6bd5ccc8e7d443b6ba045812c1c5fb1b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":4,
              "y":907},
            "size":{
              "width":226,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a1b341e88014314b7e0f4e6bbbfa2a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":4,
                  "y":907},
                "size":{
                  "width":226,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ed22701e5c7849bc9165936f808527f1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":58,
              "y":910},
            "size":{
              "width":186,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fc335255957f4e11a1302d2f50b1c9fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":58,
                  "y":910},
                "size":{
                  "width":186,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a44a4fa1f6e347a7bbbe4778c2ab3c9e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":0,
              "y":1046},
            "size":{
              "width":320,
              "height":49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb5fa0848f294337b1d1035bdbf8f6cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":0,
                  "y":1046},
                "size":{
                  "width":320,
                  "height":49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/确认订单-双色球/u60.png"}},
{
          "id":"4bec2973e71f4e81a8a1e9b794c0cc72",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":6,
              "y":1061},
            "size":{
              "width":226,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e5da9de3cf0479eb3456f64fc08df07",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":6,
                  "y":1061},
                "size":{
                  "width":226,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b48476054ecb4bb2b52c110274afac0c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":6,
              "y":947},
            "size":{
              "width":259,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1d9b6886b1647efa13dc66ab5032c8c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":6,
                  "y":947},
                "size":{
                  "width":259,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"de985fa0c5d2478199d1a61111a3b5e3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":6,
              "y":979},
            "size":{
              "width":255,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d945417df6941c3b83cd98698564d50",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":6,
                  "y":979},
                "size":{
                  "width":255,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dc016d9681104ed3915ca2a93450ce29",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":6,
              "y":1014},
            "size":{
              "width":255,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e83cf81a8ee4183a7fc67ddd2a6e46e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":6,
                  "y":1014},
                "size":{
                  "width":255,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"919f8a15c49d4ac7b4dbd86ac2230aa5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":0,
              "y":1108},
            "size":{
              "width":320,
              "height":191}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb8e12abc8ca464587adfce6e6d07782",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":0,
                  "y":1108},
                "size":{
                  "width":320,
                  "height":191}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/打票任务/u21.png"}},
{
          "id":"2e8c9bb7b4ee4556b340672c3dad6f1e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1149},
            "size":{
              "width":320,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/合买详情/u49_line.png"}},
{
          "id":"9ec078992c1e402c89cd619a6a21d7fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":4,
              "y":1123},
            "size":{
              "width":226,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e5bca1e7e1d437a9b6d6aa219ea38ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":4,
                  "y":1123},
                "size":{
                  "width":226,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"112aa2f23eda41bca11dd4a1b52161ed",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":234,
              "y":1116},
            "size":{
              "width":80,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"42c98db736a747f4896805beaa18caf0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":234,
                  "y":1116},
                "size":{
                  "width":80,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单中心/u26.png"}},
{
          "id":"a310fe148de54c7abedf1d0474cac707",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":4,
              "y":1159},
            "size":{
              "width":226,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3f2e86a134d4e60b1696946e389eafe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":4,
                  "y":1159},
                "size":{
                  "width":226,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e2e00ff68dd24428b697c1701803f265",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":58,
              "y":1162},
            "size":{
              "width":186,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eef0e57cb288405c97480e3becf80594",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":58,
                  "y":1162},
                "size":{
                  "width":186,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2472739e68cb4cd5baa38b215556f677",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":0,
              "y":1298},
            "size":{
              "width":320,
              "height":49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5be946f618e04c61b111cb9761083888",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":0,
                  "y":1298},
                "size":{
                  "width":320,
                  "height":49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/确认订单-双色球/u60.png"}},
{
          "id":"46a9f495b4c647d4a7c6aa4e4eb69e04",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":6,
              "y":1313},
            "size":{
              "width":226,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"741c71aa94a140de9f3fb253cf52b7ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":6,
                  "y":1313},
                "size":{
                  "width":226,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9a6534d1c8ed4b77adb911019d63cc1e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":6,
              "y":1199},
            "size":{
              "width":259,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7496cdad232048d79fe4bdccf9136ec7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":6,
                  "y":1199},
                "size":{
                  "width":259,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"13a4dc53a78d477684f395e3224f2648",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":6,
              "y":1231},
            "size":{
              "width":255,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aae2747f115045a5968d9b3f56542bf1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":6,
                  "y":1231},
                "size":{
                  "width":255,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ff626a4b966349978b1592332ac078fe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":6,
              "y":1266},
            "size":{
              "width":255,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0c98865589eb4e21b8c0bcf9c2fbc074",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":6,
                  "y":1266},
                "size":{
                  "width":255,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9a797b1f8f784f468fb0b966be3994be",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "location":{
              "x":135,
              "y":68},
            "size":{
              "width":23,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e2b0e249e5954699bec317e185ebfab2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "location":{
                  "x":135,
                  "y":68},
                "size":{
                  "width":23,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/打票任务/u127.png"}},
{
          "id":"7be91fc3d9a84f5caf2b93c37f5b9224",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "location":{
              "x":287,
              "y":70},
            "size":{
              "width":23,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"162781eaef7940768d2cdaf15e7173e4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "location":{
                  "x":287,
                  "y":70},
                "size":{
                  "width":23,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/打票任务/u127.png"}},
{
          "id":"40e4cda43d5f40feb45d0afb6f4ccbb0",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":214,
              "y":555},
            "size":{
              "width":100,
              "height":35}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "5285e837732946a686f168bcdc862016":{
      "scriptId":"u0"},
    "764b24cbd48d450587c6d4d6dfc0ea52":{
      "scriptId":"u1"},
    "13a417ea5ca943908b1687f1125edce1":{
      "scriptId":"u2"},
    "7ef0b4dc5f844a94ac25de523eac2ee0":{
      "scriptId":"u3"},
    "c9ccf497b74e47979f4fb55521927389":{
      "scriptId":"u4"},
    "cd1b11dddc694abbad2975224353173f":{
      "scriptId":"u5"},
    "9694347acabe4d8e9464c0a1082d98c5":{
      "scriptId":"u6"},
    "00522f6c6a75406da17d035b0481165b":{
      "scriptId":"u7"},
    "6615c0a384cf475b9cf43599ad5a8115":{
      "scriptId":"u8"},
    "8e621548b5344666ac4520850635878e":{
      "scriptId":"u9"},
    "ff07a22662d34ae3b3d99b312f6d5ca8":{
      "scriptId":"u10"},
    "d6f362f51d95467cabf17067defda941":{
      "scriptId":"u11"},
    "9a6842e4081841728553c81bf55f2307":{
      "scriptId":"u12"},
    "68b743cbfefa47fea9354325c3297699":{
      "scriptId":"u13"},
    "89aa2e3e36324aa6a3b15ea8248a7e9f":{
      "scriptId":"u14"},
    "0ed3e117565348e690f68a595420a7cd":{
      "scriptId":"u15"},
    "fe7a269e5b6e4bd98c00596639960578":{
      "scriptId":"u16"},
    "5da01be17ee946329fbaea3a40c8266e":{
      "scriptId":"u17"},
    "c5fe1479d7f845568a2fb93055e8c42d":{
      "scriptId":"u18"},
    "eaa3affe85fd42ddb9f928570e0bb091":{
      "scriptId":"u19"},
    "db82cad6deb24cff8d0498e61dfbee79":{
      "scriptId":"u20"},
    "3d5be1602b304e2488a4aa17935aa594":{
      "scriptId":"u21"},
    "b613c00bca374615b12d8f6ca871c639":{
      "scriptId":"u22"},
    "a9a7571d17984e518f17d8ed84e14ea9":{
      "scriptId":"u23"},
    "38dff6057c264be48ae40af65a8acd13":{
      "scriptId":"u24"},
    "4cc6e195fc0a47afba107a8d79941ddc":{
      "scriptId":"u25"},
    "b0bf4df0d75a46b3a98026b57ee8da0f":{
      "scriptId":"u26"},
    "cfc6f10900ff4a5aa5b096b114de4a61":{
      "scriptId":"u27"},
    "5863b2b7ebef488894f3c46deb24706f":{
      "scriptId":"u28"},
    "deebf83ba5be48dc95c0b7b549079b9c":{
      "scriptId":"u29"},
    "08ebe90eead143229eeaf244a4f3f054":{
      "scriptId":"u30"},
    "7f803a20d1004d8881fae49a0b9be2e4":{
      "scriptId":"u31"},
    "a71aab681191422f8f20f1d7351ad335":{
      "scriptId":"u32"},
    "86352f857b804ac98411cada5fac166f":{
      "scriptId":"u33"},
    "9d88cefe82d94760b4055fbd7961a92e":{
      "scriptId":"u34"},
    "5d3451ce8e4b449c88c700de28ed12f2":{
      "scriptId":"u35"},
    "d37af51169bc4a7f85ebdcc076033e65":{
      "scriptId":"u36"},
    "42f64ea9253f4c07b3e41a1abdd85bf1":{
      "scriptId":"u37"},
    "b1d93a5ee7ac4a868b51ae10fcd224b4":{
      "scriptId":"u38"},
    "5512faabac294250af649053f8c29232":{
      "scriptId":"u39"},
    "bdac3944aa004e3995d3480b7804bba3":{
      "scriptId":"u40"},
    "42da819b246d4d03b5cc98320492d329":{
      "scriptId":"u41"},
    "8cf6cc43eadc4341a9e5b48890720865":{
      "scriptId":"u42"},
    "948fe2fcb9874a28829728aa80f94064":{
      "scriptId":"u43"},
    "d6544b92c68645fb917b5744066a1c5f":{
      "scriptId":"u44"},
    "930061dbba744cbea2259448ebde0c7b":{
      "scriptId":"u45"},
    "7e03e26550e3476ea56325c1aab5ff8a":{
      "scriptId":"u46"},
    "d3bd42276b5648c8a02c884758390463":{
      "scriptId":"u47"},
    "8ac3fd2c63bc4fa2885ce1f753cd1821":{
      "scriptId":"u48"},
    "967534325a024e199d910025c84a4142":{
      "scriptId":"u49"},
    "5e64a3fe06dc453eaa3b4c1bb4f65bc1":{
      "scriptId":"u50"},
    "bb6d2035c3fa426bb10a006be9883367":{
      "scriptId":"u51"},
    "bcb39494f3ff42e395480265e7661bda":{
      "scriptId":"u52"},
    "f873cb6de812470daccedc49dc0e1671":{
      "scriptId":"u53"},
    "abbf4341164d4125b80ec1f422b4b877":{
      "scriptId":"u54"},
    "152317493ca747a0b7d33b4942bb60f0":{
      "scriptId":"u55"},
    "975e773a889441be99e7e9d7f280618a":{
      "scriptId":"u56"},
    "983d1e2306314747963cab10b3c14973":{
      "scriptId":"u57"},
    "3e60283531c24f8fb64d3a8a620b8a10":{
      "scriptId":"u58"},
    "b2bad18acb9e4547b8b57dc2d284781a":{
      "scriptId":"u59"},
    "47610e78ae89481ab02aad9cd0d43424":{
      "scriptId":"u60"},
    "51ad11c628ed485e9345839274eac9f7":{
      "scriptId":"u61"},
    "0167cc3afb174c06861e4386a8f3e357":{
      "scriptId":"u62"},
    "b98ec199961d4e199e26a3a6750d4a74":{
      "scriptId":"u63"},
    "83a7616de1644ba19458b77aeff62d43":{
      "scriptId":"u64"},
    "1995905c9f404cb98b3fb82403411c9d":{
      "scriptId":"u65"},
    "565eff48f9324b91bb19e7f105403dbc":{
      "scriptId":"u66"},
    "ad8a38988a5e466db46644e2907046f9":{
      "scriptId":"u67"},
    "5fc38eb099dd4561864d93b95b9750f8":{
      "scriptId":"u68"},
    "c1853bedc88842fb9fc340936d0cfeee":{
      "scriptId":"u69"},
    "65f7a02daf254946aed745dcd8d355ca":{
      "scriptId":"u70"},
    "d6ca3d659f494e219ff88f63df620075":{
      "scriptId":"u71"},
    "6ca98c614a75498cbc7a16bc69e0e1ee":{
      "scriptId":"u72"},
    "019de19c81eb42ffbeda328bcd3a8e7e":{
      "scriptId":"u73"},
    "5475a387c38f422880fb76449fa1a57c":{
      "scriptId":"u74"},
    "eaa9ebebcd2d4158998c98f04de9cfd5":{
      "scriptId":"u75"},
    "6c9411ab5a054a629105cd8201b774b8":{
      "scriptId":"u76"},
    "79e09ad6a0f4477c976d310c8e84ddf5":{
      "scriptId":"u77"},
    "f238af3bb8d94a54a81ad5cc362b825f":{
      "scriptId":"u78"},
    "e9c2076d175145f5bad65084a3483911":{
      "scriptId":"u79"},
    "5cac1538a6814d73bdc5761f1d04784e":{
      "scriptId":"u80"},
    "23ad0ec5e38c42fdba1f354a71494b6c":{
      "scriptId":"u81"},
    "4634d731914341eab1b9f6cdcafc1f9b":{
      "scriptId":"u82"},
    "945564cbf6054ae895a9105d00b81ab5":{
      "scriptId":"u83"},
    "8099c3eecb5a4adc80ad6f1a4c12ee26":{
      "scriptId":"u84"},
    "269631bd5e99498289a068abff7ab98c":{
      "scriptId":"u85"},
    "96418e935e9d44c6b4a046a5e4cdbd81":{
      "scriptId":"u86"},
    "22f768b805904e3f817dba84b9edeca4":{
      "scriptId":"u87"},
    "fbcb3fa5fcc54aedbafd96f8f7ae14cf":{
      "scriptId":"u88"},
    "2aefd519bedb476c843a60246cfcb597":{
      "scriptId":"u89"},
    "f0520cf5c8354c89aac1391d089d50c7":{
      "scriptId":"u90"},
    "ea6dec422a944c5ea98075dd366459e4":{
      "scriptId":"u91"},
    "6bd5ccc8e7d443b6ba045812c1c5fb1b":{
      "scriptId":"u92"},
    "9a1b341e88014314b7e0f4e6bbbfa2a7":{
      "scriptId":"u93"},
    "ed22701e5c7849bc9165936f808527f1":{
      "scriptId":"u94"},
    "fc335255957f4e11a1302d2f50b1c9fa":{
      "scriptId":"u95"},
    "a44a4fa1f6e347a7bbbe4778c2ab3c9e":{
      "scriptId":"u96"},
    "bb5fa0848f294337b1d1035bdbf8f6cb":{
      "scriptId":"u97"},
    "4bec2973e71f4e81a8a1e9b794c0cc72":{
      "scriptId":"u98"},
    "6e5da9de3cf0479eb3456f64fc08df07":{
      "scriptId":"u99"},
    "b48476054ecb4bb2b52c110274afac0c":{
      "scriptId":"u100"},
    "b1d9b6886b1647efa13dc66ab5032c8c":{
      "scriptId":"u101"},
    "de985fa0c5d2478199d1a61111a3b5e3":{
      "scriptId":"u102"},
    "0d945417df6941c3b83cd98698564d50":{
      "scriptId":"u103"},
    "dc016d9681104ed3915ca2a93450ce29":{
      "scriptId":"u104"},
    "3e83cf81a8ee4183a7fc67ddd2a6e46e":{
      "scriptId":"u105"},
    "919f8a15c49d4ac7b4dbd86ac2230aa5":{
      "scriptId":"u106"},
    "bb8e12abc8ca464587adfce6e6d07782":{
      "scriptId":"u107"},
    "2e8c9bb7b4ee4556b340672c3dad6f1e":{
      "scriptId":"u108"},
    "9ec078992c1e402c89cd619a6a21d7fa":{
      "scriptId":"u109"},
    "7e5bca1e7e1d437a9b6d6aa219ea38ce":{
      "scriptId":"u110"},
    "112aa2f23eda41bca11dd4a1b52161ed":{
      "scriptId":"u111"},
    "42c98db736a747f4896805beaa18caf0":{
      "scriptId":"u112"},
    "a310fe148de54c7abedf1d0474cac707":{
      "scriptId":"u113"},
    "d3f2e86a134d4e60b1696946e389eafe":{
      "scriptId":"u114"},
    "e2e00ff68dd24428b697c1701803f265":{
      "scriptId":"u115"},
    "eef0e57cb288405c97480e3becf80594":{
      "scriptId":"u116"},
    "2472739e68cb4cd5baa38b215556f677":{
      "scriptId":"u117"},
    "5be946f618e04c61b111cb9761083888":{
      "scriptId":"u118"},
    "46a9f495b4c647d4a7c6aa4e4eb69e04":{
      "scriptId":"u119"},
    "741c71aa94a140de9f3fb253cf52b7ff":{
      "scriptId":"u120"},
    "9a6534d1c8ed4b77adb911019d63cc1e":{
      "scriptId":"u121"},
    "7496cdad232048d79fe4bdccf9136ec7":{
      "scriptId":"u122"},
    "13a4dc53a78d477684f395e3224f2648":{
      "scriptId":"u123"},
    "aae2747f115045a5968d9b3f56542bf1":{
      "scriptId":"u124"},
    "ff626a4b966349978b1592332ac078fe":{
      "scriptId":"u125"},
    "0c98865589eb4e21b8c0bcf9c2fbc074":{
      "scriptId":"u126"},
    "9a797b1f8f784f468fb0b966be3994be":{
      "scriptId":"u127"},
    "e2b0e249e5954699bec317e185ebfab2":{
      "scriptId":"u128"},
    "7be91fc3d9a84f5caf2b93c37f5b9224":{
      "scriptId":"u129"},
    "162781eaef7940768d2cdaf15e7173e4":{
      "scriptId":"u130"},
    "40e4cda43d5f40feb45d0afb6f4ccbb0":{
      "scriptId":"u131"}}});