$axure.loadCurrentPage({
  "url":"意见反馈.html",
  "generationDate":new Date(1496903835705.76),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"sfz",
"sfz_n"],
  "page":{
    "packageId":"6d86e536d81a47ce87796356c081fbcb",
    "type":"Axure:Page",
    "name":"意见反馈",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"8766c5e16fba4401b36a163c7b3a14e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "size":{
              "width":320,
              "height":500},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d19e696a6c204b6c9ed7b5fb4d51a96d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "size":{
                  "width":320,
                  "height":500},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/钱包/u0.png"}},
{
          "id":"cb7f1dd76e3f4ecca50062f86d76f6f2",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "fixedHorizontal":"left",
          "fixedMarginHorizontal":0,
          "fixedVertical":"top",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"e34f52123be5419184a52d6cbb639d84",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"29a13da610d646338fc0a82e3f1d7a62",
                  "label":"",
                  "parentDynamicPanel":"cb7f1dd76e3f4ecca50062f86d76f6f2",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF1C222E},
                    "size":{
                      "width":320,
                      "height":64},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"41c01e739bea4614ba36426d99b3992a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"cb7f1dd76e3f4ecca50062f86d76f6f2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF1C222E},
                        "size":{
                          "width":320,
                          "height":64},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u3.png"}},
{
                  "id":"b1b39eb536c64b6a9ea85c6f88aaa557",
                  "label":"",
                  "parentDynamicPanel":"cb7f1dd76e3f4ecca50062f86d76f6f2",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Heiti SC Regular', 'Heiti SC'",
                    "fontSize":"18px",
                    "fontWeight":"200",
                    "horizontalAlignment":"center",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":78,
                      "y":35},
                    "size":{
                      "width":163,
                      "height":22},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"47e050555d6a43ce959c9f8480aa33eb",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"cb7f1dd76e3f4ecca50062f86d76f6f2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Heiti SC Regular', 'Heiti SC'",
                        "fontSize":"18px",
                        "fontWeight":"200",
                        "horizontalAlignment":"center",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":78,
                          "y":35},
                        "size":{
                          "width":163,
                          "height":22},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"69bdd01759e043ba977fb34ef5ed7878",
                  "label":"",
                  "parentDynamicPanel":"cb7f1dd76e3f4ecca50062f86d76f6f2",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":320,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"75a5a82fc1954f6ca62780f4dab816c1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"cb7f1dd76e3f4ecca50062f86d76f6f2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":320,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u7.png"}},
{
                  "id":"ddc819597e504febabab324b33b69a19",
                  "label":"",
                  "parentDynamicPanel":"cb7f1dd76e3f4ecca50062f86d76f6f2",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Heiti SC Regular', 'Heiti SC'",
                    "fontSize":"16px",
                    "fontWeight":"200",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":27,
                      "y":36},
                    "size":{
                      "width":63,
                      "height":19},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f4d123c494e94139ab3a9852f467fed2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"cb7f1dd76e3f4ecca50062f86d76f6f2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Heiti SC Regular', 'Heiti SC'",
                        "fontSize":"16px",
                        "fontWeight":"200",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":27,
                          "y":36},
                        "size":{
                          "width":63,
                          "height":19},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"1a1dcebbbf0143ae8ece7c570a0c4e59",
                  "label":"",
                  "parentDynamicPanel":"cb7f1dd76e3f4ecca50062f86d76f6f2",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Lucida Grande Regular', 'Lucida Grande'",
                    "fontSize":"20px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":9,
                      "y":31},
                    "size":{
                      "width":22,
                      "height":29}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b889bc4380744d3ebdcb0ada47e1a24d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"cb7f1dd76e3f4ecca50062f86d76f6f2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Lucida Grande Regular', 'Lucida Grande'",
                        "fontSize":"20px",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":9,
                          "y":31},
                        "size":{
                          "width":22,
                          "height":29}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"5852e56980ea404992a5268f3511a51f",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "stateStyles":{
              "hint":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1}}},
            "location":{
              "x":20,
              "y":80},
            "size":{
              "width":280,
              "height":130}},
          "adaptiveStyles":{
},
          "placeholderText":"在这里输入您的意见和建议"},
{
          "id":"89b6fd348f5a4841823d5f42b42d98db",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":20,
              "y":275},
            "size":{
              "width":270,
              "height":45}},
          "adaptiveStyles":{
}},
{
          "id":"6cfc6003e6974ef28caca26fe39eb363",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":20,
              "y":220},
            "size":{
              "width":280,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b2275b27162433fbc5234bfb367c52e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":20,
                  "y":220},
                "size":{
                  "width":280,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "8766c5e16fba4401b36a163c7b3a14e9":{
      "scriptId":"u0"},
    "d19e696a6c204b6c9ed7b5fb4d51a96d":{
      "scriptId":"u1"},
    "cb7f1dd76e3f4ecca50062f86d76f6f2":{
      "scriptId":"u2"},
    "29a13da610d646338fc0a82e3f1d7a62":{
      "scriptId":"u3"},
    "41c01e739bea4614ba36426d99b3992a":{
      "scriptId":"u4"},
    "b1b39eb536c64b6a9ea85c6f88aaa557":{
      "scriptId":"u5"},
    "47e050555d6a43ce959c9f8480aa33eb":{
      "scriptId":"u6"},
    "69bdd01759e043ba977fb34ef5ed7878":{
      "scriptId":"u7"},
    "75a5a82fc1954f6ca62780f4dab816c1":{
      "scriptId":"u8"},
    "ddc819597e504febabab324b33b69a19":{
      "scriptId":"u9"},
    "f4d123c494e94139ab3a9852f467fed2":{
      "scriptId":"u10"},
    "1a1dcebbbf0143ae8ece7c570a0c4e59":{
      "scriptId":"u11"},
    "b889bc4380744d3ebdcb0ada47e1a24d":{
      "scriptId":"u12"},
    "5852e56980ea404992a5268f3511a51f":{
      "scriptId":"u13"},
    "89b6fd348f5a4841823d5f42b42d98db":{
      "scriptId":"u14"},
    "6cfc6003e6974ef28caca26fe39eb363":{
      "scriptId":"u15"},
    "9b2275b27162433fbc5234bfb367c52e":{
      "scriptId":"u16"}}});